### ISSUE TITLE
Recaf hangs on saving JAR

### ISSUE THREAD

**Issue by SkyAphid** [Col-E/Recaf#10]
I'm trying to edit the bytecode on an older program I have. The fix just requires a change to a String constant, so the simplest solution is to edit the bytecode rather than access the git for it and go through the trouble of bringing it up to the date with the other software it relies on. I'm able to successfully change the fields I'm looking for, but unfortunately when I try to save the jar, Recaf hangs indefinitely and ends up unresponsive. If you leave your contact information, I can send you the JAR in question. Otherwise, I'm impressed with this software! It's by far one of the best bytecode editors I've used.

**Comment by Col-E** [comment]
> If you leave your contact information, I can send you the JAR in question

Sure, you can add me on discord `Col-E#6255`

**Comment by SkyAphid** [comment]
Thanks! I've added you.

**Comment by Col-E** [comment]
Going to close and just point to #11 *(More detailed)* for more discussion.
