### ISSUE TITLE
Can't add new "Java bytecode instruction" on an empty method

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#100]
**Can't add new "Java bytecode instruction" on an empty method**

**To Reproduce**
1. Open any method class and delete all the bytecode instructions, emptying the method
2. Over the empty method, try to add a new instruction.
3. The "right-mouse-button" will not pop-up the contextual menu to add new instructions (or do anything) with the method.

**Screenshots**
![recaf-instructions](https://user-images.githubusercontent.com/3332674/47376178-f312e700-d6bf-11e8-9d27-07a2f645f12d.jpg)

**Comment by Col-E** [comment]
Done! 

With some method that has 0 opcodes _(make sure it is not marked as abstract)_, right clicking in the empty space will prompt you to add a starter opcode series.

```
0:  LABEL A
1:  RETURN
2:  LABEL A
```

It will also add the `this` variable _(which increments the maxLocals value, which is now editable)_ if your method is non-static. This will satisfy the verifier _(red outline)_ and let you continue from there.

**Comment by pedroflor** [comment]
Thanks a lot!
