### ISSUE TITLE
Some minor improvements :)

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#102]
## Language combo-box
Config -> Display -> Language => Should be a combo box with all the available languages.

## Themes combo-box
Config -> Display -> Language => Should be a combo box with all the available themes.
About themes, would be great if a self made theme (style sheet) could be "installed/loaded" for further personal use.

## Undo & Redo for "opecode window editor"
When editing methods (Open a class -> Methods Tab -> Instructions -> Edit) would be great if we can do a "undo & redo" for any opcode modification.

## Confirmation button for "opecode window editor"
Within the "opecode" window editor, a button to confirm and apply any changes before leaving the opcode window editor.

**Comment by Col-E** [comment]
Added combo-boxes for Language/Themes.

**Comment by pedroflor** [comment]
Thanks so much!

**Comment by Col-E** [comment]
Closing with 2/4 features implemented:

The way things are set up makes undo / redo beyond the existing save-state system very hard to implement short of rewriting the UI. The same can be said for a confirm button.

**Comment by pedroflor** [comment]
More than happy :)
