### ISSUE TITLE
Autocomple comboBox for "opcodes"

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#103]
## Autocomple comboBox for "opcodes" 

Hi Matt...

An image worth thousand words :)
![gif_auto_complete](https://user-images.githubusercontent.com/3332674/48221142-9e31ca80-e367-11e8-9dd8-c88b5b6c3fb3.gif)

Here is an example:
http://fxapps.blogspot.com/2016/03/simplest-javafx-combobox-autocomplete.html

* Thanks for your hard work!

**Comment by Col-E** [comment]
Done!
