### ISSUE TITLE
add gif in the screenshoot with basic configuration

### ISSUE THREAD

**Issue by newUserRepo** [Col-E/Recaf#105]
## Gif with basic config

 * Short description of the feature

It would be possible to add a small gift with a basic configuration of recaf
***

**Extra details**:

* More verbose details of features

It could be other gifts showing much more complex configurations of use

**Comment by Col-E** [comment]
Not sure what you mean. How are gifts and config related?

**Comment by newUserRepo** [comment]
Hello, How are you?

was somewhat busy, good a gift demonstrating how it works recaf in some steps that would be difficult sometimes not enough with only images, with short short animations would be something better for dummies like me for example.

**Comment by andylizi** [comment]
.... Do you mean 'GIF'?

**Comment by Col-E** [comment]
I'll provide a walk-through in the docs at some point. I think that would be better than a short `GIF` or video,

**Comment by rucko24** [comment]
Hi @Col-E , You have created a very extensive documentation and I think that a newbie will be able to use it more easily, I close this issue.

**Comment by Col-E** [comment]
Documentation is in Markdown form: https://github.com/Col-E/Recaf-documentation _(So its easy to update and make PR's)_
 - Compiled to HTML at: https://www.coley.software/Recaf-documentation/
