### ISSUE TITLE
IndexOutOfBoundsException when encountering an empty list in annotation values

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#106]
#### Stacktrace
```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at me.coley.recaf.ui.FormatFactory.annotation(FormatFactory.java:152)
	at me.coley.recaf.ui.component.editor.AnnotationListEditor$1.updateItem(AnnotationListEditor.java:61)
	at me.coley.recaf.ui.component.editor.AnnotationListEditor$1.updateItem(AnnotationListEditor.java:52)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
```

#### Steps to reproduce
1. Open sample [TestAnnotation.zip](https://github.com/Col-E/Recaf/files/2602850/TestAnnotation.zip)
2. Navigate to `Class Information` tab
3. Click `Visible annotations`

#### Sample code
```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@TestAnnotation(values1 = {}, values2 = {}, values4 = {})
public @interface TestAnnotation {
    String[] values1();

    int[] values2() default {1, 2, 3};

    boolean[] values3() default {};

    Class<?>[] values4();
}
```

#### Related code
Commit ec66079a8382235d34908103eee631d48256d0f7:
https://github.com/Col-E/Recaf/blob/ec66079a8382235d34908103eee631d48256d0f7/src/me/coley/recaf/ui/FormatFactory.java#L148-L152

---

Not sure how you want to fix it or I'll patch it myself. I read the relevant code in ASM and came to the conclusion that it is impossible to get the type of an empty array value using the `AnnotationNode` (i.e. `asm-tree` API), but it *can* be done with a custom-implemented `AnnotationVisitor`. As the whole program is based on the node-structure that `asm-tree` provided, I don't think it's worth it.

(Sorry about any grammatical errors or the like. I spent half an hour struggling with the wording and grammar while writing the paragraph above... Really envy the native speakers :pensive:)

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/48825564-b88b8100-ed35-11e8-81d1-9797eed83fe2.png)

Pushed a release, so this can also serve as a test for the new update prompt.

**Comment by Col-E** [comment]
> (Sorry about any grammatical errors or the like. I spent half an hour struggling with the wording and grammar while writing the paragraph above... Really envy the native speakers pensive)

Also don't worry about it. Your bug reports are excellently crafted.
