### ISSUE TITLE
Is it possible to insert a breakpoint bytecode?

### ISSUE THREAD

**Issue by brandonros** [Col-E/Recaf#109]
Is it possible to connect with IntelliJ/Eclipse debugger to a JVM running a JAR and insert breakpoints in between the decompiled instructions?

**Comment by brandonros** [comment]
The JVM will 100% blow up if you manually hex edit a 0xCA breakpoint bytecode in, for anybody wondering.

**Comment by Col-E** [comment]
I'm not aware of any libraries that would allow insertion of breakpoints that would follow what you would expect from a typical IDE. If you find one I'd be more than happy to work on implementing it.
