### ISSUE TITLE
Export classes with "source file" names

### ISSUE THREAD

**Issue by brandonros** [Col-E/Recaf#111]
Your package is amazing for resolving and matching the source filenames from the JAR.

However, it's very hard to search the left hand pane (if I start typing, it does not start finding), and `com.o.b.x.z` is not revealed to be "AwsServicesExample.java" until I click on it. Maybe show the source file with the class on the left pane when present?

An export function would literally save me... 2 hours about now lol

**Comment by Col-E** [comment]
Going to close this assuming that the _"Show SourceFile names"_ option covers this issue.
