### ISSUE TITLE
HIDPI support 

### ISSUE THREAD

**Issue by alexmaloteaux** [Col-E/Recaf#115]
Short description of the feature

Hi , is it possible to somehow implement HiDPI support , maybe through a theme or any other methods .
Im on a linux based system with a 4K display and recaf is unusable in that case.

**Comment by Col-E** [comment]
I don't have the hardware to test so I don't know how to work on fixing this. Can you post a scree shot or something so I can see what the problem is?

**Comment by Col-E** [comment]
There's a [note on running Recaf with Java 9](https://col-e.github.io/Recaf/documentation.html#gs-r). If you follow that you can try out the GDK_SCALE variable.

**Comment by Col-E** [comment]
If anyone on JDK 11+ with a HIDPI monitor can test this out I'd really appreciate it.

**Comment by alexmaloteaux** [comment]
Hi

I just tested with version 1.14 and java 11 on Arch Linux and it works perfectly now.
All is scaled perfectly on a 4K monitor.
Thanks
