### ISSUE TITLE
Fernflower Decompiler

### ISSUE THREAD

**Issue by oskar3123** [Col-E/Recaf#118]
## Fernflower Decompiler

While not absolutely critical, an option for using Fernflower as the decompiler would be nice.

**Comment by Col-E** [comment]
Can it be easily referenced as a maven dependency?

**Comment by oskar3123** [comment]
Pretty sure they don't have an official maven repo.
The code for it can be found here: https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine
Or in one of the unofficial mirrors, https://github.com/fesh0r/fernflower

**Comment by Col-E** [comment]
I asked about maven because I'd like to not go back to tracking binaries on the repo. It does look like windup just hosts mirrors of the current version, so I'll look into it.

**Comment by blshkv** [comment]
https://github.com/MinecraftForge/FernFlower/issues/1

**Comment by Col-E** [comment]
> MinecraftForge's FernFlower

Oh so there is a maven backing this. Maybe this can actually be done.

**Comment by Col-E** [comment]
While this won't be in `1.X.X` it's been completed in the `2.0.0` branch
