### ISSUE TITLE
Exported Jar does not contain directories when opened with ZipFile

### ISSUE THREAD

**Issue by McGregsen** [Col-E/Recaf#119]
When I open a jar file with Recaf and export it again (even without changing anything) the exported jar file does not contain any directories when opened programmatically using the ZipFile Java API.
Although classes and other files inside the folders are still present and are correctly found by ZipFile.

I am not sure whether this is actually a problem with Recaf or a bug in the ZipFile implementation. Do you have any idea where the problem is originating from?

1. Open any jar file with some classes and directories/packages in Recaf
2. Export it again
3. Read the exported jar using:
    
        ZipFile zipFile = new ZipFile("original.jar");
        Enumeration<? extends ZipEntry> zipFileEntries = zipFile.entries();
        while (zipFileEntries.hasMoreElements()) {
            final ZipEntry zipFileEntry = zipFileEntries.nextElement();
            System.out.println(zipFileEntry.getName());
        }

        zipFile = new ZipFile("exported.jar");

        zipFileEntries = zipFile.entries();

        while (zipFileEntries.hasMoreElements()) {
            final ZipEntry zipFileEntry = zipFileEntries.nextElement();
            System.out.println(zipFileEntry.getName());
        }
4. Compare the two outputs. The first one contains the directories/packages the second one does not.

**Comment by Col-E** [comment]
I didn't think to include the directory entries, or care about sorted order of file entries. Oops!

**Comment by Col-E** [comment]
While not in the _EXACT_ same order, the exported jar now contains the directory entries, preceding the file entries of said directory. Entries are also in alphabetical order _(default package items are always at the end of the entry set)_.
