### ISSUE TITLE
Better cross version support (Java 8 vs 11)

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#124]
## Better cross version support

Releases have always been targeting Java 8 due to it's continued popularity. However those that have adopted Java 11 can't run Recaf as easily as the Java 8 users because:

* The autoupdate pulls these targeted versions regardless of the current Java environment
* Java 11 can't run the Java 8 targeted releases due to missing dependencies
    * Java 11 no longer includes JavaFx by default
* The updated Java 11 dependencies _(Like the ControlsFx dependency)_ don't match the `NameType`s in classes compiled in the 8-centered releases

***

**Potential Solutions**:

* Multi-release jars _(Should support existing auto-update mechanic)_
* Multiple target jars per release _(May conflict with existing auto-update mechanic, causing a breakage of forward compatibility)_
* Have dependencies downloaded & resolved at runtime

**Comment by andylizi** [comment]
How about... checking the JVM version when Recaf starts, and (if it's the first time) automatically downloads the required version of JavaFx/ControlsFx, then immediately restarts itself using the accorded launch arguments? Won't be the most elegant of the solutions, but it should work... at least.

**Comment by Col-E** [comment]
> How about... 

With 549305b1829a2e540a19c0db3a3adda0cfb20723 I basically did just that. 

* If Recaf launches under Java 8 it runs normally
* If Recaf launches under Java 9 or 10 it asks you to update to 11 or downgrade to 8.
* If Recaf launches under Java 11 it checks if JavaFX is in the classpath. If it is, it runs normally. Otherwise it checks for `recaf-$version-patched.jar`. If it exists, it'll rerun using that. If not, it'll create it by cloning the Recaf files into it, then overlapping all the required dependencies on top.

**Comment by Col-E** [comment]
andy's approach works and has been implemented as of `1.14.0`
