### ISSUE TITLE
Maven build issue (weird resource location)

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#125]
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	...
Caused by: java.lang.ExceptionInInitializerError
	at me.coley.recaf.ui.FxWindow.start(FxWindow.java:47)
	...
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at me.coley.recaf.util.Lang.load(Lang.java:54)
	... 11 more
Caused by: java.lang.NullPointerException
	at me.coley.recaf.util.Streams.from(Streams.java:34)
	at me.coley.recaf.util.Streams.toString(Streams.java:51)
	at me.coley.recaf.util.Lang.load(Lang.java:50)
	... 11 more
```

After some investigation, I found that all files in `src/main/resources` are being put into the `/resources/` folder during packaging, so that `/lang/en.json` became `/resources/lang/en.json`:
https://github.com/Col-E/Recaf/blob/9ab0379f8df0d7e1247b9350a41e562ae38e794d/src/main/java/me/coley/recaf/util/Lang.java#L43-L50

But why? Why would Maven relocate them into `/resources`? As far as I know, all resource files will directly go into JAR root if you didn't specify otherwise in `pom.xml`. And I checked and double-checked, but can't find anything that seems to be related.

So I downloaded a fresh copy of this repo and ran `mvn package` using a plain command-line. This is the result:
![](https://user-images.githubusercontent.com/12008103/59146965-7acb1d00-8a27-11e9-84fc-9d9649fb3761.png)

Still didn't relocate, both before and after `shade`. But yours (downloaded from Github Release) did:
![](https://user-images.githubusercontent.com/12008103/59146990-f5943800-8a27-11e9-9ccf-75cb24eb2bf6.png)
So there seems to be a large inconsistency between your build output and mine, which shouldn't exist if you're using a project management system like Maven...

There is a comment about _"add `**/*.json` to your source filters"_ and _"refresh the project when that's done"_. But... what is a "source filter" exactly? It's not a Maven concept considering it isn't already written in `pom.xml`. And "refreshing project" is only meaningful to some particular IDEs, not a general concept either. (I'm using IDEA, and I'm guessing yours is Eclipse according to `.gitignore` commit logs)

**Comment by andylizi** [comment]
Apply the following patch to get consistent behavior when packaging:
```patch
From 879830f3b3a4e81e97cc22efd429a00cc7a92b33 Mon Sep 17 00:00:00 2001
From: andylizi <andylizi666@gmail.com>
Date: Sat, 8 Jun 2019 20:22:49 +0800
Subject: [PATCH] Copy all resources into `/resources` rather than root when packaging.

---
 pom.xml | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/pom.xml b/pom.xml
index df49743..cfa5fd0 100644
--- a/pom.xml
+++ b/pom.xml
@@ -246,6 +246,12 @@
 		</dependency>
 	</dependencies>
 	<build>
+		<resources>
+			<resource>
+				<directory>${basedir}/src/main/resources</directory>
+				<targetPath>resources/</targetPath>
+			</resource>
+		</resources>
 		<plugins>
 			<!-- Maven version enforcement -->
 			<plugin>
-- 
2.21.0.windows.1
```
i.e. add the following element into `<build>`:
```xml
<resources>
	<resource>
		<directory>${basedir}/src/main/resources</directory>
		<targetPath>resources/</targetPath>
	</resource>
</resources>
```

**Comment by Col-E** [comment]
Yeah like it works for me now because this is the default resource location AFAIK. This is really weird.

**Comment by Col-E** [comment]
Ok this is REALLY odd

> There is a comment about _"add `**/*.json` to your source filters"_ and _"refresh the project when that's done"_. But... what is a "source filter" exactly? It's not a Maven concept considering it isn't already written in `pom.xml`. And "refreshing project" is only meaningful to some particular IDEs, not a general concept either. (I'm using IDEA, and I'm guessing yours is Eclipse according to `.gitignore` commit logs)

Exactly, I have no idea what's causing this, but I'll add the patch for sure. 

In my _CURRENT_ project workspace

* IntelliJ works
* Eclipse works
* **Maven works**

However... if I clone the repo

* IntelliJ fails
* Eclipse fails
* **Maven fails**

**Comment by Col-E** [comment]
Thanks! Would have never caught this since I don't regularly clear my workspace.
