### ISSUE TITLE
"IllegalStateException: Not on FX application thread" when typing very fast in auto-completion

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#126]
#### Environment
Java: jdk1.8.0_212
Recaf: 9ab0379f8df0d7e1247b9350a41e562ae38e794d

#### Description
```
IllegalStateException: Not on FX application thread; currentThread = Thread-22
   com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
   com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:444)
   javafx.scene.Parent$2.onProposedChange(Parent.java:367)
   com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:249)
   com.sun.javafx.binding.ContentBinding$ListContentBinding.onChanged(ContentBinding.java:117)
   org.reactfx.collection.ChangeListenerWrapper.onChange(LiveList.java:439)
   org.reactfx.collection.ChangeListenerWrapper.onChange(LiveList.java:417)
   org.reactfx.util.ListNotifications.lambda$takeHead$0(NotificationAccumulator.java:317)
   org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
   org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
   org.reactfx.collection.MappedList.sourceChanged(MappedList.java:41)
   org.reactfx.util.ListNotifications.lambda$takeHead$0(NotificationAccumulator.java:317)
   org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
   org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
   org.reactfx.collection.ProperLiveList.fireModification(ProperLiveList.java:25)
   org.reactfx.collection.ProperLiveList.fireElemInsertion(ProperLiveList.java:50)
   org.reactfx.collection.MemoizationListImpl.get(MemoizationList.java:102)
   org.fxmisc.flowless.CellListManager.getCell(CellListManager.java:69)
   org.fxmisc.flowless.CellPositioner.getSizedCell(CellPositioner.java:217)
   org.fxmisc.flowless.CellPositioner.placeStartAt(CellPositioner.java:127)
   org.fxmisc.flowless.Navigator.fillForwardFrom0(Navigator.java:253)
   org.fxmisc.flowless.Navigator.fillForwardFrom0(Navigator.java:235)
   org.fxmisc.flowless.Navigator.fillTowardsSkyFrom0(Navigator.java:347)
   org.fxmisc.flowless.Navigator.fillViewportFrom(Navigator.java:308)
   org.fxmisc.flowless.Navigator.visit(Navigator.java:130)
   org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
   org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78)
   javafx.scene.Parent.layout(Parent.java:1087)
   org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
   javafx.scene.Parent.layout(Parent.java:1087)
   org.fxmisc.flowless.VirtualFlow.getCellIfVisible(VirtualFlow.java:220)
   org.fxmisc.richtext.GenericStyledArea.getCaretBoundsOnScreen(GenericStyledArea.java:1033)
   org.fxmisc.richtext.CaretNode.lambda$new$6(CaretNode.java:232)
   org.reactfx.value.Val$3.computeValue(Val.java:722)
   org.reactfx.value.ValBase.getValue(ValBase.java:17)
   org.reactfx.value.SuspendableValWrapper.getValue(SuspendableValWrapper.java:23)
   me.coley.recaf.ui.FxAssembler.updateAutoComplete(FxAssembler.java:383)
   me.coley.recaf.ui.FxAssembler.lambda$null$1(FxAssembler.java:185)
   me.coley.recaf.util.Threads$1.run(Threads.java:46)
```
![](https://user-images.githubusercontent.com/12008103/59147943-8b35c480-8a34-11e9-9e23-a49748b875ce.gif)

Release 1.14.0 don't seem to have this issue. I only reproduced it under the latest `master` version (9ab0379f8df0d7e1247b9350a41e562ae38e794d). `git bisect` can help locating the exact commit that introduced the bug, but I haven't get to that yet.

#### Steps to reproduce
1. Open any assembler window.
2. Type `GETSTATIC ` (with a space).
3. Try to type `java/lang/System` (any name seems to work) very quickly. Type it slowly, character-by-character, will not work.
4. Bam!

I recommended comment out this line beforehand by the way:
https://github.com/Col-E/Recaf/blob/9ab0379f8df0d7e1247b9350a41e562ae38e794d/src/main/java/me/coley/recaf/Logging.java#L330
or it'll cut off the full stacktrace, both in UI error prompt and in console output. UI I can understand, but why would you want to truncate stacktraces in console eludes me. How can you debug anything with only half the stacktrace anyway?

**Comment by Col-E** [comment]
> or it'll cut off the full stacktrace, both in UI error prompt and in console output. UI I can understand, but why would you want to truncate stacktraces in console eludes me. How can you debug anything with only half the stacktrace anyway?

_Most of the time_ the top of the trace is all that's necessary _(kind of how like IntelliJ truncates unnecessary lines in it's traces in console)_

**Comment by andylizi** [comment]
> _Most of the time_ the top of the trace is all that's necessary

Point. But in this case, the top half didn't even have anything that starts with `me.coley` so... 🤔

**Comment by Col-E** [comment]
I can't seem to type as fast as you... but I think I found a really simple fix:

`FxAssembler#185`

I found changing `Threads.run(() -> updateAutoComplete());` to `Threads.runFx(() -> updateAutoComplete());`

**Comment by andylizi** [comment]
It works... :sweat_smile:
