### ISSUE TITLE
[Assembler] LDC also support "symbolic references"

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#129]
![ldc](https://user-images.githubusercontent.com/12008103/59348957-1243af00-8d4b-11e9-92d7-a8d640507902.png)

According to [JVMS 6.5.ldc](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.ldc):

> Otherwise, if the run-time constant pool entry is a symbolic reference to a class or interface, then the named class or interface is resolved ([§5.4.3.1](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-5.html#jvms-5.4.3.1)) and value, a reference to the Class object representing that class or interface, is pushed onto the operand stack.

> Otherwise, the run-time constant pool entry is a symbolic reference to a method type, a method handle, or a dynamically-computed constant. The symbolic reference is resolved ([§5.4.3.5](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-5.html#jvms-5.4.3.5), [§5.4.3.6](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-5.html#jvms-5.4.3.6)) and value, the result of resolution, is pushed onto the operand stack.

---

Oh, and I would suggest adding a label beside the `Save` button in `Assembler` window, to show something like "2 errors". I spent a lot of time finding out why I just can't click `Save` even if there were absolutely nothing wrong with my changes. Then I finally realized its because Recaf can't parse its own assembly output `LDC Lorg/bukkit/craftbukkit/Main;` even without me changing anything. And the validator won't run before the first modification, so I didn't notice the warnings immediately.

---

By the way, I also suggest changing the category display name for CFR to something like "CFR decompiler". Because why would the user know that you're using CFR for decompilation and/or that CFR settings mean decompilation settings without... reading... documentation. Well I supposed that "when in doubt, read the docs" is always good practice but I don't think the majority of the users actually read the docs word-by-word? There're not many modern GUI software that you CAN'T use without reading the manuals first anyway.

**Comment by LovesAsuna** [comment]
只要我尝试使用换行符，代码就会自动转换
![TTA5~L3`2%56D771CO2OK11](https://user-images.githubusercontent.com/32810896/59353033-ab2af800-8d54-11e9-8f83-22db3abce66d.png)
![$V QPIHJ_CBZ3V8HUM8~JEP](https://user-images.githubusercontent.com/32810896/59353038-abc38e80-8d54-11e9-85c7-aac824e7ff60.png)

**Comment by andylizi** [comment]
You left the comment at the wrong issue...

你评论错地方了。

**Comment by Col-E** [comment]
> Missing support for symbolic references

![image](https://user-images.githubusercontent.com/21371686/59362598-bacd2100-8d01-11e9-91a5-477c02d87f3d.png)

Done!

> Label beside save to show _"2 errors"_

![image](https://user-images.githubusercontent.com/21371686/59362447-75105880-8d01-11e9-8220-9d5d78d773d2.png)

Also done!

> changing the category display name for CFR to something like "CFR decompiler"

Done x3
