### ISSUE TITLE
LDC不支持\n换行?

### ISSUE THREAD

**Issue by LovesAsuna** [Col-E/Recaf#130]
![$V QPIHJ_CBZ3V8HUM8~JEP](https://user-images.githubusercontent.com/32810896/59353745-3d7fcb80-8d56-11e9-91ef-18a6d67d8427.png)
![TTA5~L3`2%56D771CO2OK11](https://user-images.githubusercontent.com/32810896/59353746-3d7fcb80-8d56-11e9-8d26-b6999f7d8058.png)
当我尝试在assembler中使用\n,其本身会自动被识别为\\n.这也是我直接重编译的原因

**Comment by Col-E** [comment]
Fixed Assembler not escaping special characters: a81a41d6c5a38d24bab5590c3eb4aa2ee784687e
