### ISSUE TITLE
[ASM] Dead loop when parsing invalid method descriptor

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#133]
### Environment
Doesn't matter.

### Description
![](https://user-images.githubusercontent.com/12008103/59551238-fb01fd00-8fa8-11e9-9915-9154b58a1e50.png)
All Recaf windows is in "Not responding" state, and the first loop in [`Type.getArgumentTypes(String)`](https://gitlab.ow2.org/asm/asm/blob/3882e8608c3290b959b28b6611665347726765d5/asm/src/main/java/org/objectweb/asm/Type.java#L302) is looping indefinitely.

#### Call stack
* [`getArgumentTypes:310, Type (org.objectweb.asm)`](https://gitlab.ow2.org/asm/asm/blob/ASM_7_1/asm/src/main/java/org/objectweb/asm/Type.java#L310)
* [`executeInvokeInsn:647, Frame (org.objectweb.asm.tree.analysis)`](https://gitlab.ow2.org/asm/asm/blob/ASM_7_1/asm-analysis/src/main/java/org/objectweb/asm/tree/analysis/Frame.java#L647)
* [`execute:603, Frame (org.objectweb.asm.tree.analysis)`](https://gitlab.ow2.org/asm/asm/blob/ASM_7_1/asm-analysis/src/main/java/org/objectweb/asm/tree/analysis/Frame.java#L603)
* [`analyze:187, Analyzer (org.objectweb.asm.tree.analysis)`](https://gitlab.ow2.org/asm/asm/blob/ASM_7_1/asm-analysis/src/main/java/org/objectweb/asm/tree/analysis/Analyzer.java#L187)
* [`checkValid:65, Verify (me.coley.recaf.bytecode.analysis)`](https://github.com/Col-E/Recaf/blob/db4f188f4c3393bb60a91092c96bf7a7044d50b0/src/main/java/me/coley/recaf/bytecode/analysis/Verify.java#L65)
* [`parseInstructions:167, Assembly (me.coley.recaf.parse.assembly)`](https://github.com/Col-E/Recaf/blob/db4f188f4c3393bb60a91092c96bf7a7044d50b0/src/main/java/me/coley/recaf/parse/assembly/Assembly.java#L167)
* [`parseInstructions:305, FxAssembler (me.coley.recaf.ui)`](https://github.com/Col-E/Recaf/blob/db4f188f4c3393bb60a91092c96bf7a7044d50b0/src/main/java/me/coley/recaf/ui/FxAssembler.java#L305)
* [`onCodeChange:285, FxAssembler (me.coley.recaf.ui)`](https://github.com/Col-E/Recaf/blob/db4f188f4c3393bb60a91092c96bf7a7044d50b0/src/main/java/me/coley/recaf/ui/FxAssembler.java#L285)
* [`lambda$setupCodePane$2:64, FxCode (me.coley.recaf.ui)`](https://github.com/Col-E/Recaf/blob/db4f188f4c3393bb60a91092c96bf7a7044d50b0/src/main/java/me/coley/recaf/ui/FxCode.java#L64)

This is technically an ASM bug, which I already opened an issue in their tracker [asm/asm#317875](https://gitlab.ow2.org/asm/asm/issues/317875), but considering their release schedule (several times a year apparently :sweat_smile:), I think maybe it's better to patch it immediately and temporarily, until they fix it properly in their code. It is, after all, quite easy to trigger (see below).

### Steps to reproduce
1. Open any method in Assembler.
2. Find an instruction with a method descriptor that has at least one parameters in it.
3. (Try to) delete all characters after somewhere in the parameter part of the descriptor (For example, delete `(Ljava/util/Collection;)V` to `(Ljava/util/Collect` will do).
4. Bam!

---

If I were you, I would move all completion & verification related code into its own thread, instead of doing all the CPU-(somewhat)-intensive calculations in the UI thread. That way not only you can easily add timeouts for them, it would also solve the problem of UI being extremely laggy when editing some huge method (which is quite common when facing obfuscated code) or editing in a huge classpath.

**Comment by Col-E** [comment]
Somehow I wasn't able to replicate this behavior even though this should cause Recaf to hang... Anyways I added a quick fix, can you try it out and verify this works?

**Comment by andylizi** [comment]
![](https://user-images.githubusercontent.com/12008103/59566033-02023b80-908d-11e9-8cca-bdf1a4cc9bff.png)
Seems to be working.

**Comment by andylizi** [comment]
They [fixed it](https://gitlab.ow2.org/asm/asm/merge_requests/267). Now waiting for the next release.
