### ISSUE TITLE
Auto-completion doesn't suggest any of the bootstrap classes

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#134]
I discovered this during some refactoring.
https://github.com/Col-E/Recaf/blob/f0c541b00176de915c3e1514ee03f0c1c16431c7/src/main/java/me/coley/recaf/util/Classpath.java#L129-L174

I had found a way to solve it under Oracle JVM 8, but it won't work in Java 9, or in other JVM implementations. So that's ANOTHER compatibility problem😓. Maybe there's another solution that I've missed?

**Comment by Col-E** [comment]
I was hoping Guava's `ClassPath` would work, but I guess we're not allowed to have nice things.

**Comment by andylizi** [comment]
I'm thinking about giving up on auto-scanning and just ask nicely for library locations, like what ProGuard did:

![](https://user-images.githubusercontent.com/12008103/62463155-da417100-b7bb-11e9-82c0-00805a581371.png)

It would save a lot of headaches, and had the benefit of choosing other versions of JDK and adding other library jars. Currently Recaf can only open one jar at a time, so Assembler can't suggest classes from any of the other dependencies.

We can still place the automatically acquired bootstrap classpath in the list of libraries if the list is empty and JRE version is below 9, like a default setting (which I think is also what ProGuard did).

**Comment by Col-E** [comment]
> We can still place the automatically acquired bootstrap classpath in the list of libraries if the list is empty and JRE version is below 9, like a default setting (which I think is also what ProGuard did).

:+1: 

> Currently Recaf can only open one jar at a time

That was one of the first things I wanted to change in `2.0.0`, it'll make this super trivial in the future.

**Comment by Col-E** [comment]
Fixed in #162 

For maintainability purposes should we still consider the proguard approach for later?

**Comment by xxDark** [comment]
Closing since its been fixed/implemented a long time ago, pending support for auto-completion is pending on https://github.com/Col-E/Recaf/pull/564
