### ISSUE TITLE
Duplicated LocalVariableTable attribute entry for '1' issue is not fixed.

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#141]
The issue i submitted yesterday (uplicated LocalVariableTable attribute entry for '1') is not fixed but is listed in fixes.

**Comment by artemking4-Projects** [comment]
https://github.com/Col-E/Recaf/issues/135

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/59601654-ace91880-90d2-11e9-89ac-146d32a25522.png)

When I copy paste the code you give and save the changes, it doesn't give any duplicates. Are you using `1.15.3`?

**Comment by Col-E** [comment]
I added a unit test that tests if multiple references to a local variable index could cause this conflict and it successfully only kept one of the references in the local-variable table. 

If you can find a sample in the latest release that I can reproduce I will re-open this issue.
