### ISSUE TITLE
Ability to search strings in annotations

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#144]
## Ability to search strings in annotations

Ability to find strings in annotations, so the search will find something like 
`@c("data.active.BotSpawnerData")`

**Comment by Col-E** [comment]
Doing a string search with `player` in a test jar:

![image](https://user-images.githubusercontent.com/21371686/59943191-95da5b80-942f-11e9-8891-aac490107314.png)

Annotations on classes, fields, and methods are now scanned. This also works with value search:

![image](https://user-images.githubusercontent.com/21371686/59943458-4f393100-9430-11e9-85df-a775688b8cfd.png)

**Comment by artemking4-Projects** [comment]
Thanks!
