### ISSUE TITLE
Ability to import Jremapper/Enigma mappings

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#149]
## Ability to import mappings of Enigma/Jremapper
Import mapping files from tools like Jremapper/Enigma

**Comment by Col-E** [comment]
Remapping right now is really only intended for one class at a time. Some refactoring would be required to make it viable to do large-scale renaming. 

Definitely on the TODO list.

**Comment by Col-E** [comment]
Added on the `2.0.0` branch in af8fa08fff60081b7ce49d1c3f5648d88602b84f
