### ISSUE TITLE
Use maven for dependencies

### ISSUE THREAD

**Issue by camabeh** [Col-E/Recaf#15]
I tried to clone/explore/debug but you don't specify versions of libraries anywhere. I tried couple of them but they were not correct. Consider better docs or use maven/gradle for dependency management.

**Comment by camabeh** [comment]
Nevermind, found it in docs, I thought they will be in README :). Still maven/gradle better

**Comment by Col-E** [comment]
I've pushed my attempt at getting maven working.  If anyone can verify I've not screwed it up I'll close this. 

> It works on my machine!

**Comment by charlesdaniels** [comment]
Confirming this appear to be working as of 36eb081ccefcc92e5ee278cc813e48659476265a on macOS 10.12 with `javac 1.8.0_121` and Maven 3.5.0:

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"```

Looks ok to close @Col-E

**Comment by Col-E** [comment]
Well, just realised that `mvn package` does not support local dependencies... And since CFR is only provided as a jar....

**Comment by Col-E** [comment]
Problem solved thanks to [this blog post](http://mark.koli.ch/maven-add-local-jar-dependency-to-classpath) by Mark S. Kolich!
