### ISSUE TITLE
Download button on site opens release JSON

### ISSUE THREAD

**Issue by TrueLecter** [Col-E/Recaf#150]
**Describe the bug**

Download button on site opens release JSON instead of downloading file

**To Reproduce**
1. Open https://col-e.github.io/Recaf/
2. Click on "Download Recaf-..."

**Screenshots**
![image](https://user-images.githubusercontent.com/5520406/60187665-9cedd900-9836-11e9-867e-5e6dc7e4273b.png)
![image](https://user-images.githubusercontent.com/5520406/60187629-90698080-9836-11e9-81bc-38fb7d529242.png)

**Comment by Col-E** [comment]
Used to work, so they must have changed something. Anyways simple fix, resolved!
