### ISSUE TITLE
Runtime simulation

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#154]
# Runtime simulation

The ability to simulate running code in a sandbox so that unknown classes and methods can be invoked without running potentially unsafe code _(Like deleting files)_. For primitives, strings, and other safe types this would allow users to watch / step through the execution and watch the changes applied to classes _(fields)_ and the method stack.  

## Use Cases

* Understanding the behavior of unknown logic without executing potentially malicious code
* Fetching values from simple methods
    * In combination with #151 could be used to automatically deobfuscate strings & other obfuscator patterns

## Implementation Outline:

**VirtualObj<T>**
- `T value`

**VirtualClass**
- `Map<Identifier, VirtualField> fields`
- `Map<Identifier, VirtualMethod> methods`

**VirtualMember**
- `identity()`
    - _abstract_, implemented by children. Used as the lookup key for **VirtualField** and **VirtualMethod**.

**VirtualField** _extends_ **VirtualMember**
- `VirtualClass value`

**VirtualMethod** _extends_ **VirtualMember**
- `Simulation getSimulation(VirtualObj... args)`
    - Generate **Simulation** object, does not run immediately

**Simulation**
- `List<VirtualInsn\> instructions`
- `List<VirtualObj\> vars`
- `Stack<VirtualObj\> stack`

**VirtualInsn** _models behavior from_ **AbstractInsnNode**
- `apply(Simulation)`
    - Applies modification to vars/stack as needed

***

Current thoughts on how the simulation API will be handled. There will probably be a lot of `VirtualClass` implementations for common core Java classes. At some point enough base classes should be implemented to have things referencing them work by auto-generated logic. For example, once `String` is implemented something like `StringUtils` should be able to have an auto-generated implementation work since all the outbound reference classes have a `VirtualClass` implementation. 

With this lookup strategy, loading loops would have to be counted somehow. Perhaps a combination of lazy-loading and keeping a global cache for library classes _(anything not residing in the primary Recaf input)_ would be worthwhile.

Also to reduce the complexity of certain simulations, being able to assign dummy values to things like field getters + method invokes may be a useful feature too.

**Comment by Col-E** [comment]
## Method Simulation Outline:

**VirtualObj<T>**
- `T value`

**VirtualClass**
- `Map<Identifier, VirtualField> field`s
- `Map<Identifier, VirtualMethod> methods`

**VirtualMember**
- `identity()`
    - _abstract_, implemented by children

**VirtualField** _extends_ **VirtualMember**
- `VirtualClass value`

**VirtualMethod** _extends_ **VirtualMember**
- `Simulation getSimulation(VirtualObj... args)`
    - Generate **Simulation** object, does not run immediately

**Simulation**
- `List<VirtualInsn\> instructions`
- `List<VirtualObj\> vars`
- `Stack<VirtualObj\> stack`

**VirtualInsn** _generated from_ **AbstractInsnNode**
- `apply(Simulation)`
    - Applies modification to vars/stack as needed

***

Current thoughts on how the simulation API will be handled. There will probably be a lot of `VirtualClass` implementations for common core Java classes. At some point enough base classes should be implemented to have things referencing them work by auto-generated logic. For example, once `String` is implemented something like `StringUtils` should be able to have an auto-generated implementation work since all the outbound reference classes have a `VirtualClass` implementation. 

With this lookup strategy, loading loops would have to be counted somehow. Perhaps a combination of lazy-loading and keeping a global cache for library classes _(anything not residing in the primary Recaf input)_ would be worthwhile.

**Comment by guschoYB** [comment]
Ohh great

**Comment by Col-E** [comment]
And https://github.com/xxDark/SSVM knocks it outta the park.
