### ISSUE TITLE
field edit form: value textbox is disabled

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#159]
Field edit form has textbox that does nothing: Value

**To Reproduce**
1. Open/Add any field in a class
2. Try to edit its value.

**Comment by Col-E** [comment]
They are only meant to be used on fields that are final and hold primitive types _(int, long, boolean, etc)_. Otherwise values are typically assigned in the static block or constructor. 

What kind of field did you test this with?

**Comment by Col-E** [comment]
A majority of fields do not use this entry, but [there are cases where it is used](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.2).

I believe that it's disabled in Recaf if these circumstances are not met.

**Comment by Col-E** [comment]
Going to close as the value is modifiable in `2.0.0`
