### ISSUE TITLE
Russian characters in string are represent as \uXXXX

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#160]
**Russian characters in string are represent as \uXXXX**

**To Reproduce**
1. Open any class that contains non-english characters
2. See \uXXXX instead of a character

**Comment by Col-E** [comment]
Its much easier to modify unicode characters in this escaped representation. A lot of people can't easily create these characters on their machines. Plus then you don't have to worry that a person's machine doesn't support rendering the character _(font)_.

In a read-only context showing the unicode literal would make sense, for instance in the decompiled output. That's up to the decompiler how to print those characters though.

**Comment by andylizi** [comment]
> Its much easier to modify unicode characters in this escaped representation

But how can you modify anything if you can't read it in the first place?

> A lot of people can't easily create these characters on their machines.

If you don't have the proper program to input those characters (e.g. an IME) then why would you try to *write* them. And you only need `Backspace` to *delete* them regardless of language anyway.
It's not like it's easy to write in `\u5929\u6c14\u4e0d\u9519`. Who, except a computer, can read or write in that?

> Plus then you don't have to worry that a person's machine doesn't support rendering the character _(font)_.

[A Unicode test page](http://www.madore.org/~david/misc/unitest/)
![](https://user-images.githubusercontent.com/12008103/61853683-1557c080-aeef-11e9-83c9-e6a119c1bb24.png)
![](https://user-images.githubusercontent.com/12008103/61853691-1983de00-aeef-11e9-9cf2-c03b60e1abdf.png)

Nope. Welcome to the 21st century.

**Comment by Col-E** [comment]
I can accept when I'm wrong.

My mindset comes from working off of intentionally obfuscated code abusing unicode characters such as in the attached sample: [calc-obf.zip](https://github.com/Col-E/Recaf/files/3431167/calc-obf.zip)

Moving forward the option to use either presentation of international characters will be available, with the default for the literal values.

**Comment by Col-E** [comment]
Using `StringEscapeUtils`  in the way shown in a81a41d6c5a38d24bab5590c3eb4aa2ee784687e will have to be changed. This was initially done to properly escape/unescape `\n` but this [also escapes international characters](https://stackoverflow.com/a/13700590), which is why we're here.

**Comment by Col-E** [comment]
This has been resolved in 2.0 
 - #186
- 09075a904f59d8f0a5ac70d2e4daa690be0fd360
