### ISSUE TITLE
Encrypted bytecode Error

### ISSUE THREAD

**Issue by lolka13372** [Col-E/Recaf#166]
There is an error in changing the encrypted bytecode, although jbyteedit does this fine, but the Label and Line function does not work in it, so I had to use your bytecode editor, please fix this problem
![image](https://user-images.githubusercontent.com/51010014/63059171-5c860f80-bef7-11e9-83dd-abac1ef428fe.png)
![image](https://user-images.githubusercontent.com/51010014/63059188-6871d180-bef7-11e9-9a26-93edff4be08b.png)
![image](https://user-images.githubusercontent.com/51010014/63059215-758ec080-bef7-11e9-88bd-0f0d6e656b62.png)

**Comment by Col-E** [comment]
There is not enough information here for me to figure out what the problem is. I will need you to share some more information with me so I can help you out.

What code are you trying to edit? Can you share that? Also Recaf generates a file `rclog.txt`, can you please share that?

**Comment by lolka13372** [comment]
[rclog.txt](https://github.com/Col-E/Recaf/files/3503518/rclog.txt)

**Comment by lolka13372** [comment]
![image](https://user-images.githubusercontent.com/51010014/63059915-598c1e80-bef9-11e9-872b-b33c2fe00acc.png)

**Comment by lolka13372** [comment]
I am changing the link connection string

**Comment by Col-E** [comment]
A window should pop up when the export fails that shows the verification analysis of the current jar. Is the message about `L` the only thing showing up in the verification window or is there more?

**Comment by lolka13372** [comment]
Only "L"
![image](https://user-images.githubusercontent.com/51010014/63060634-73c6fc00-befb-11e9-8353-8b9a6964042b.png)

**Comment by Col-E** [comment]
Well, the method instructions _have to be valid_ to properly execute. So this leads me to believe some debug information is improperly formatted and ASM is failing to verify that.

Can you try checking the `Skip Debug` option and re-importing your jar and making your changes?

![image](https://user-images.githubusercontent.com/21371686/63060810-4d846a80-bec1-11e9-9579-01e27c8aaf08.png)

**Comment by lolka13372** [comment]
![image](https://user-images.githubusercontent.com/51010014/63061013-8130b600-befc-11e9-97e2-d5ea6e140a4a.png)
![image](https://user-images.githubusercontent.com/51010014/63061018-8a218780-befc-11e9-904c-237e8c5c1a0c.png)
![image](https://user-images.githubusercontent.com/51010014/63061033-96a5e000-befc-11e9-927c-9116665178cf.png)
![image](https://user-images.githubusercontent.com/51010014/63061161-e84e6a80-befc-11e9-9c1e-4389e76307b6.png)

**Comment by Col-E** [comment]
Ok, so something is still bad. Uncheck the `Verify` option. 

The sample looks obfuscated so the obfuscator probably has tampered with the bytecode in such a way that the modifications to the class are _technically_ allowed by the file format, but isn't actually representing _valid data_, and this is why ASM fails to verify the data.

**Comment by lolka13372** [comment]
![image](https://user-images.githubusercontent.com/51010014/63061551-30ba5800-befe-11e9-810c-f43e9cc0ca2a.png)
It will be necessary to test
If everything worked or not
I will answer tomorrow

**Comment by lolka13372** [comment]
@Col-E Thx

**Comment by Col-E** [comment]
:+1:
