### ISSUE TITLE
Missing textures in classpath causing nullptr

### ISSUE THREAD

**Issue by goofless** [Col-E/Recaf#168]
[ERRR:03.09.2019 23:32] NullPointerException: null
   me.coley.recaf.util.Icons.loadLvl(Icons.java:235)
   me.coley.recaf.util.Icons.<clinit>(Icons.java:48)
   me.coley.recaf.ui.FxWindow.start(FxWindow.java:103)
   com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
   com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
   com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
   java.security.AccessController.doPrivileged(Native Method)
   com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
   com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
   com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
   com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
   java.lang.Thread.run(Unknown Source)

**Comment by Col-E** [comment]
I'm going to need more information to help.

* What Java version are you on?
* What version of Recaf are you using?
* Are you using the prebuilt releases or compiling from the source code?

**Comment by Col-E** [comment]
I'll reopen this if/when details are provided that allow this to be reproduced.
