### ISSUE TITLE
Code quality improvement

### ISSUE THREAD

**Issue by charlesdaniels** [Col-E/Recaf#17]
Once PR #16  is merged, Recaf will have FindBugs and CheckStyle code-quality metrics as part of the reports in `mvn site`. I would propose a few things to act on these going forward:

1. Commit to "ratcheting down" the number of quality issues. I would simply record the number of issues associated with each commit and try to reduce it, or at least not increase it, with every commit.

2. Make an ongoing effort to reduce the number of quality issues, even if it's just a few at a time.

3. If necessary, disable certain checks from CheckStyle and FindBugs. Not every check will be useful for every project. That said, be sure when disabling a check project-wide that it really isn't a legitimate quality issue for this project. 

4. Once the total issue count is reduced to 0, make CheckStyle and FindBugs part of `mvn compile` so that the build fails if any new issues appear. 

I would suggest creating issues based on the content of this one, then closing this one, as this is just intended to provoke discussion/planning.

**Comment by Col-E** [comment]
Currently using a more lenient version of Google's Java config for CheckStyle.
FindBugs / SpotBugs is there, but not required for building.
