### ISSUE TITLE
Editing with assembler removes try-catches

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [Col-E/Recaf#170]
**Describe the bug**

Editing a method with assembler, not even doing anything & saving, removes all "try-catches"

**To Reproduce**
1. Open the method editor with name, desc, etc
2. View try-catches
3. Close it
4. Edit the method with assembler 
5. Type something, then remove it(to be able to save)
3. Review "try-catches", and see nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/21975901/66878072-1a1b9600-ef6d-11e9-8907-860a56a4dede.png)
![image](https://user-images.githubusercontent.com/21975901/66878086-2b64a280-ef6d-11e9-95f6-c4163275f00c.png)

**Other**
I would think this happens with other information other than "try-catches", either way, it shouldn't remove try-catches.

**Comment by Col-E** [comment]
The new assembler for 2.X is available to use with some of the recent commits, so I'm going to close this.
