### ISSUE TITLE
Error: NullPointerException on Re-Compile

### ISSUE THREAD

**Issue by AxDSan** [Col-E/Recaf#171]
Steps to Reproduce:
1. Have my machine, cuz nothing works here... -.-

Jokes aside...

1. Download Recaf (latest)
2. Open and load X Jar file
3. Open X Class and X Method, Decompile it.
4. With the decompilation window open, right click -> Re-Compile
5. Exception is thrown.

X = Any (it's literally broken down here, it's throwing the exception on everything.)

# Image
![](https://i.imgur.com/sgQP7B5.png)

# LOG:
`NullPointerException: null
   me.coley.memcompiler.JavaXCompiler.compile(JavaXCompiler.java:46)
   me.coley.recaf.ui.component.DecompileItem$FxDecompile.recompile(DecompileItem.java:371)
   me.coley.recaf.ui.component.DecompileItem$FxDecompile.lambda$null$1(DecompileItem.java:218)
   me.coley.recaf.ui.component.ActionMenuItem.lambda$new$1(ActionMenuItem.java:20)
   com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
   com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
   com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
   com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
   com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
   com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
   com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
   javafx.event.Event.fireEvent(Event.java:198)
   javafx.scene.control.MenuItem.fire(MenuItem.java:462)
   com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
   com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$6(ContextMenuContent.java:1358)
   com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
   com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
   com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
   com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
   com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
   com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
   com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
   com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
   com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
   com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
   com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
   com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
   com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
   com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
   com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
   javafx.event.Event.fireEvent(Event.java:198)
   javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
   javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
   javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
   javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
   com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
   com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
   java.security.AccessController.doPrivileged(Native Method)
   com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
   com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
   com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
   com.sun.glass.ui.View.handleMouseEvent(View.java:555)
   com.sun.glass.ui.View.notifyMouse(View.java:937)
   com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
   com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
   java.lang.Thread.run(Unknown Source)
`

**Comment by AxDSan** [comment]
Fix:

1. Open Regedit
2. Go to HKCR\jarfile\shell\open\command
3. Make sure you have your default REG_SZ string value points to your a correct Java executable:

e.g. "C:\Program Files\Java\jdk1.8.0_221\bin\javaw.exe" -jar "%1" %*

**Comment by Col-E** [comment]
I'll look into make the cause of this problem more clear in 2.0 instead of this big exception.
