### ISSUE TITLE
Resource viewer

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [Col-E/Recaf#174]
## Resource viewer/editior

View and or even edit(not really needed but could be nice) a text or a resource file in the jar

This makes life easier, don't have to open it with winwar, or use luyten

**Comment by Col-E** [comment]
Already in the works for `2.0.0` - https://github.com/Col-E/Recaf/blob/redesign/src/main/java/me/coley/recaf/ui/controls/view/FileViewport.java

Currently supports a text editor and hex editor.

**Comment by Col-E** [comment]
Closing since on the redesign branch this is already implemented _(viewing & editing with syntax highlighting)_

If you have further ideas to add to the feature I'd love to hear them though :+1:
