### ISSUE TITLE
 Illegal reflective access by me.coley.recaf.util.Classpath$ClassPathScanner

### ISSUE THREAD

**Issue by blshkv** [Col-E/Recaf#176]
Hi, I'm facing this error message under Gentoo Linux (latest)
I have the following packages installed:
dev-util/recaf-bin-1.15.9
dev-java/openjdk-11.0.5_p10
dev-java/openjfx-11.0.3_p1

Here is the full output:

bash$ recaf 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.coley.recaf.util.Classpath$ClassPathScanner (file:/data/opt/recaf/recaf.jar) to field java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP
WARNING: Please consider reporting this to the maintainers of me.coley.recaf.util.Classpath$ClassPathScanner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by cookiedragon234** [comment]
Looks like this is the cause: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/util/Classpath.java#L169

Have you tried using any other JVM builds such as JDK8? Im not sure which versions Col-E tests on but I know for sure that I do not get this error on my hotspot JDK 8 build.

**Comment by cookiedragon234** [comment]
Also are these errors fatal? It looks like it is only a warning meaning you should still be able to continue using recaf fine?

**Comment by xxDark** [comment]
> 
> 
> Also are these errors fatal? It looks like it is only a warning meaning you should still be able to continue using recaf fine?

Yes this is only a warning, printed by `jdk.internal.module.IllegalAccessLogger`

**Comment by cookiedragon234** [comment]
If they are not fatal I recommend you just ignore them

**Comment by xxDark** [comment]
This warnings cannot be avoided without relaunching Recaf with correct VM flags, even by using `jdk.internal.misc.Unsafe`, since we need to get the offset of `IMPL_LOOKUP` to get field's value.

**Comment by Col-E** [comment]
Like the others have mentioned its not fatal. Its a bit ugly to see in console when starting up, but its a byproduct of how Recaf figures out what classes are loaded at runtime. If there's a _"proper"_ way to lookup this information to not require reflection like this, it could be resolved. I don't know of any other way than how Andy and xxDark set it up.

**Comment by Col-E** [comment]
Using facade classes we can bypass this warning, thanks xxDark!
