### ISSUE TITLE
create a single folder for all output

### ISSUE THREAD

**Issue by blshkv** [Col-E/Recaf#177]
Hi, 

recaf (1.15.9) writes all its output to the current directory instead of ~/.recaf or similar. That basically means that the entire system will be polluted with recaf folders and files which it is getting created during runtime.

Please consider to redesigning it.

**Comment by Col-E** [comment]
Running Recaf shouldn't make too much stuff, 2 folders and 1 log file. :

![image](https://user-images.githubusercontent.com/21371686/72614112-6e813980-38ff-11ea-9bb5-f2c570976785.png)

I personally don't think that's bad. And the reason for it being the current directory instead of a specific folder is so that nobody has to ask _"Where does this config even save to?"_

**Comment by xxDark** [comment]
Maybe settings should be stored in `~/.recaf` directory if user manually creates the directory first?

**Comment by blshkv** [comment]
my point is that it is hard to trace back all these folders and files. "plugins" is just a common name, rc-config is may be openrc related (I have /usr/bin/rc-config binary in my system), txt file which is apparently a log file (must be .log) and even the binary (jar patched). All these files are getting created everytime in random folders. It would be hard to understand which software created after awhile and hard to clean a disk.

The last suggestion (having a directory) is tricky and it is like a hidden functionality. 
I would rather vote for a compilation flag if you really want it to make it optional

**Comment by Col-E** [comment]
Fair enough. I've never had a setup using Recaf where the current directory wasn't where the executable was, so it never really occurred to me.

**Comment by Col-E** [comment]
xxDark started on this, however the logging library used requires specifying a relative or absolute path in the config file _(Which wouldn't allow for platform independent paths)_

So if we wanted to move the log file to the home directory then we'd have to replace the log api. It's already mostly abstracted away to one class, so it could be replaced with a minimal one from scratch.

**Comment by Col-E** [comment]
2.0.0 will be using `${user.home}/Recaf` from now on

**Comment by blshkv** [comment]
Thank you guys!
