### ISSUE TITLE
Roll-out CI for Recaf

### ISSUE THREAD

**Issue by charlesdaniels** [Col-E/Recaf#18]
Recaf should have some sort of CI to:

* Ensure every commit compiles.
* Ensure documentation is build for every commit.
* Monitor CheckStyle/FindBugs issue count for every commit.
* Make build artifacts (jarfile, docs) are available for download.

I suggets investigating [Travis CI](https://travis-ci.org) as it is free for open source projects to use.

**Comment by Col-E** [comment]
Started as of https://github.com/Col-E/Recaf/commit/271c494cc6870a985d37af9116df657dd021369f

**Comment by Col-E** [comment]
Started as of https://github.com/Col-E/Recaf/commit/271c494cc6870a985d37af9116df657dd021369f

[x] Every commit compiles
[ ] Documentation checks
[ ] Checkstyle / Findbugs checks
[ ] Build artifacts

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/blob/redesign/CONTRIBUTING.md#commit-messages - CI is now automated with commit messages thanks to @ViRb3 - #196

**Comment by Col-E** [comment]
I'm going to close this as its basically complete. Findbugs can be easily added later, but for now I believe checkstyle will suffice.
