### ISSUE TITLE
Recaf needs unit tests.

### ISSUE THREAD

**Issue by charlesdaniels** [Col-E/Recaf#19]
Recaf should have unit tests to reduce the probability of regressions between releases. I suggest [JUnit](http://junit.org/) as it integrates nicely with Maven and is widely used.

**Comment by Col-E** [comment]
[Better late than never](https://github.com/Col-E/Recaf/tree/master/src/test/java/me/coley/recaf) :upside_down_face:

**Comment by Col-E** [comment]
Skipping the JavaFX tests using [conditional executions via JUnit 5](https://junit.org/junit5/docs/current/user-guide/#extensions-conditions) resolves this, but now it seems to be hanging for 10m on `InputTest`

**Comment by Col-E** [comment]
Closing since this has been implemented for a while
