### ISSUE TITLE
Font Scale

### ISSUE THREAD

**Issue by LovesAsuna** [Col-E/Recaf#190]
## Feature_Name
Change Font scale
Short description of the feature

***

**Extra details**:
users can change the font scale by theirselves
* More verbose details of features

**Comment by Col-E** [comment]
![2020-01-24_21-54-15](https://user-images.githubusercontent.com/21371686/73115476-565b7c80-3ef4-11ea-86ca-4463ed00203d.gif)

**Comment by Col-E** [comment]
Added in be7d8ba9d6e1fd62e40a5d297fd9fc0a96b92297
