### ISSUE TITLE
Recaf 2.0.0 disassembler bugs

### ISSUE THREAD

**Issue by Ilolka1337** [Col-E/Recaf#192]
Recaf 2.0.0 does not correctly display methods in the disassembler

Screenshots:
![image](https://user-images.githubusercontent.com/63341162/78896365-0c0c8500-7a79-11ea-80d9-e7677e0f9fa4.png)
![image](https://user-images.githubusercontent.com/63341162/78896386-1595ed00-7a79-11ea-9505-c085e625f791.png)
![image](https://user-images.githubusercontent.com/63341162/78896418-20508200-7a79-11ea-9d29-f7a8ca1d833f.png)

**Comment by Col-E** [comment]
Could you provide a sample class file? I can't debug the problem without a sample.

**Comment by Ilolka1337** [comment]
[Matrix.zip](https://github.com/Col-E/Recaf/files/4456370/Matrix.zip)

**Comment by Ilolka1337** [comment]
I use java
![image](https://user-images.githubusercontent.com/63341162/78900676-db7c1980-7a7f-11ea-9023-dadf69aafd25.png)

**Comment by xxDark** [comment]
#Off-topic

Matrix can be cracked by spoofing Matrix's API domain and sending fake response back to the plugin.

**Comment by Col-E** [comment]
The INVOKEDYNAMIC parser didn't allow there to be _no arguments_ _(like this case)_. I'll push the fix soon since I found another problem while looking at this.

**Comment by Col-E** [comment]
Fixed in 20936c77252b31abc2f2b7a035fc32a9b8a392b6
