### ISSUE TITLE
Font Colors

### ISSUE THREAD

**Issue by Ilolka1337** [Col-E/Recaf#193]
## Customize Font Colors

Short description of the feature
users can customize the colors of the strings - methods - values etc. ​​to their taste
***

**Extra details**:

* More verbose details of features

**Comment by Col-E** [comment]
This is actually supported, but is done externally for now.

I wrote a small guide on it here: https://coley.software/recaf-creating-custom-themes/

**Comment by Ilolka1337** [comment]
@Col-E i hope you add so that it can be changed through the program interface

**Comment by Col-E** [comment]
I plan to eventually have a live editor with a preview mode. Its not that hard to set that up. But that'll be done later. I'm currently focusing on other issues.

**Comment by Ilolka1337** [comment]
@Col-E thx

**Comment by Col-E** [comment]
👍

**Comment by Col-E** [comment]
Information on how to create a custom theme can be found here: 
 - https://col-e.github.io/Recaf/doc-advanced-theme.html

The plugin that activates the theme editor _(which isn't done yet, but is usable at this point)_ is in the **#plugins** channel on discord until I create a proper list of plugins somewhere.
