### ISSUE TITLE
Verified Rejected?

### ISSUE THREAD

**Issue by 90mindblogspotcom** [Col-E/Recaf#204]
I used set.ee JBE java bytecode editor and he doesnt have a support or forum so i cant get help.
Please Help Java Minecraft Bytecode Editor
[Java]

Java Bytecode Editor cant edit Minecraft mods.

Pass 3a:

Verifying method: values

Instruction invokevirtual[182](3) 26 constraint violated: Class '[Lcom.pixelmonmod.pixelmon.battles.attacks.Effectiveness;' is referenced, but cannot be loaded: 'VERIFIED_REJECTED

Repository.lookup() failed. FILE NOT FOUND?

I opened this file said verify file without coding editing; it just cant verify file it keep saying it cant find the file but file it is looking is already open! It is searching for its own self and cant find it

**Comment by Col-E** [comment]
This project is the bytecode editor **Recaf**, not Ando Saabas's JBE.  This is a separate editor.

If you use Recaf to make your changes and encounter a bug I will be happy to take a look at the report. But since I do not maintain the software you have a problem with, I cannot help you.

**Comment by 90mindblogspotcom** [comment]
Dude can i edit your software for editing class files in minecraft mods? I just dont understand; i want to change a number and it giving me errors, i tried 8 softwares none of them worked. Why dont we just act like class files are json files just edit its code without giving errors and by ignoring errors. You know workspace is 200 mb and i only want to edit a number people say build eclipse, gradle, jdk, jre, jde and they say choose Javaw.exe sometimes even that doesnt work. Dude this ubuntu linux stuff are really nerd stuff, i decomplied some java code it says 8 lines of code for giving you 1 line of information; bolean this, int that, public pool stuff; it was too easy to edit BattleTech mods. What kind of illness is this. Minecraft is disgusting and it is more slower than all of its C++ copies. There is hundreds of minecraft clones with better graphics and physics and all of them faster than minecraft. Why java devs are like that? I just wanted to edit a class file i spend 2 weeks i can read decompile but cant edit.

**Comment by Col-E** [comment]
> Dude can i use your software for editing class files

Yes, my software should support that.

> I just wanted to edit a class file i spend 2 weeks i can read decompile but cant edit.

Recaf lets you skip the decompile step, which is prone to errors. Instead you can edit the bytecode directly.

> I just dont understand

Slow down and try and be more patient. If you rush trying to learn something it will be frustrating. 

Cover the basics before diving straight into it:

* https://blog.overops.com/jvm-architecture-101-get-to-know-your-virtual-machine/
* https://blog.jamesdbloom.com/JVMInternals.html

> What kind of illness is this. Minecraft is disgusting

Then why don't you play another game?
