### ISSUE TITLE
Class became JAR

### ISSUE THREAD

**Issue by 90mindblogspotcom** [Col-E/Recaf#205]
Hi ColE. Your software works perfectly maybe; didnt test it yet. I used it and it converted my class file to an broken Jar file. I edited jar extension to class by writing and i think maybe it works fine. I used jd gui decompiler; it was looking fine. Your software works like jd gui but it also lets us edit the code. Why output is jar file and is there any guides or videos about all details of this software an known problems? You know if everybody says same stuff and asks same questions it can be boring. By the way i have 133 iq.

Elon Musk send 60 space robots every month for creating internet web in space he say it will be faster and cheaper internet. Covid made by manipulated evolution and virus feeding it is evolving and very unbalanced and weird. If you ill, you need to sleep and stay hot while eating well; otherwise can die recovering takes more than 4 month sometimes. With covid poor people died and begged to rich while rich is killing criminals and gangs while there is curfew. They cleaning USA gangs and rioters. Terorists feel very un required; because virus kills and stops economy so there is no reason for riots or protests anymore; i feel like there is nothing i can do. Normally i am anti rich anti job but everybody left their jobs and everybody became anti rich so i feel very offended.

Clone yourself, inject clone baby blood. Take clone organs, clone blood clots, bone materials and refresh your body be immortal. Kill all humans, enslave your own clones; abuse and rape your own clones also can create your opposite gender clones by only editing 1 chromosome. So there far you can rape and sex your own gender edited clones.

Video games are religion now. In future everybody will be coder. Games will be religion and ideology and education. Youtube will be replaced by github. Videos will be video games. Steam will be twitch.

I want to work with you visit my website

**Comment by Col-E** [comment]
[This is what we call an epic gamer moment.](https://www.youtube.com/watch?v=UVQmdKwn_dQ)
