### ISSUE TITLE
Cannot Save The File

### ISSUE THREAD

**Issue by 90mindblogspotcom** [Col-E/Recaf#206]
File has errors red triangles. I push ctrl S it says errors. I push ctl A and export. It exports but unedited version gets exported. How can we ignore errors; what are table decompile hex, CFM femflower porycryon?? I edited the file i just want to save it. If i copy paste it as json, can it magically become class file? It didnt work, my magic tricks doesnt work

**Comment by Col-E** [comment]
> How can we ignore errors

You can't. That's why they're there.

> What are...

Read here: https://coley.software/recaf-getting-started-primer/

> If i copy paste it as json, can it magically become class file?

Nope

> It didnt work, my magic tricks doesnt work
