### ISSUE TITLE
This Files Gives Disgusting Errors

### ISSUE THREAD

**Issue by 90mindblogspotcom** [Col-E/Recaf#208]
> Edit: Removed IP op does not own

I cant create ICONST_6 i dont know why. How to create Iconst and why i cant create i const 6?

**Comment by Col-E** [comment]
Java does not have an instruction type for `ICONST_6`

See: <https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings>

There are other instructions you should use if you wish to push the value `6` onto the stack

`BIPUSH 6`

**Comment by 90mindblogspotcom** [comment]
So you say iconst is same thing with bipush than why they dont use bipush instead. Also they used one, double kind of numbers but when i replace them with 2.0f it works fine; why they write double instead of writing a real number. Also they said roll a number between 85 100 but if it is bigger than 100 t becoming a negative number. If it is smaller than 3 it is crashing the game like dealing zero damage or a damage that is not a number. ;Than they said divide it with 100 i made it 40 because only that way i can calculate 185 by using 74. Dude i am filled with sickness; eww java users must be really weird people and i was wondering why web browsers slow; because websites use java because school teaches java for web design because it is easy and useless. I wonder is there any game better than minecraft made by java. Eww disgusting so you say iconst 6 doesnt exist, is iconst 0 a thing does it work like 1 or 2? Is iconst a label rather than number? Eww java eww. Alsoı did you know pixelmon crashing very very often.

Move Tutor crashes game. Small numbers crashes game. If false swipe crits it crashes i think maybe.

**Comment by 90mindblogspotcom** [comment]
I stuck at multiple hit move. I also failed at adding a new crit stage. I am unable add new levels new letters. Your software has limits. Is it break if i change all letters to 1 or 2 bigger letters; you know i have to add new parts to middle of the code. Somehow i always failed. Also rng was very weird. With %50 crit; i hit 9 crit in a row than didnt crit for two than crit than didnt. I felt like crit rate was 7/8. I dont know maybe i wasted too much time with Java. I think editing exp formula is a dream at this state. Compiling is hard, code is slow and large; why java is used actually i think java is harder than c++. Notch is a disgusting guy and he stole minecraft from envirominer also minecraft devs specially notch mostly suck at coding. People added more than Devs added to game. Even devs copied some mods that trading npc pigs in nether was a mod. Insomnia was a mod. Hunger was a mod. Cats, dogs was mod.
