### ISSUE TITLE
New windows opens in the secondary monitor

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#209]
## New windows opens in the secondary monitor

I have 2 monitors. WheN I open "Config" menu or need to open any new windows from Recaf, it opens in the left monitor (secondary monitor). It is possible to open in the same monitor as the recaf is opened?

**Comment by Col-E** [comment]
https://stackoverflow.com/questions/34936617/choose-which-monitor-does-a-javafx-window-open-in - Should be possible

**Comment by Col-E** [comment]
Check the latest pre-release. I looked at some docs and this _seems_ like it should work.

**Comment by Col-E** [comment]
Any feedback on the current release's behavior @pedroflor ? Was added in eeb6bfd49c01e08a266ce035ae2060a5cadee381

I don't have multiple monitors to test with. Also, I noticed this makes newly spawned windows serve as top-most...

**Comment by pedroflor** [comment]
Hi Col-E... thanks for the enhancement.
Fixed!
See by your self: [https://i.imgur.com/nEQbZvD.mp4](url)
Just a note: currently, all the new windows opens in the center of the current screen. Neither window remember their last position.

**Comment by Col-E** [comment]
🤔

If I had multiple monitors I could look into it more... but alas I do not.

**Comment by pedroflor** [comment]
Please watch this https://i.imgur.com/nEQbZvD.mp4

**Comment by Col-E** [comment]
I saw. I don't really know what else to do. I read the documentation and its very sparse on this matter... if there's a full fix its not immediately obvious to me.

**Comment by pedroflor** [comment]
The fix you pushed, works great!
Thanks for your time :)
