### ISSUE TITLE
Add "Edit instructions/Decompile/Edit with assembler" with right mouse button

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#210]
Version 1.5, with right mouse buton – RMB, it’s possible to choose between 
- Edit instructions
- Decompile
- Edit with assembler

In version 2.x it’s needed to go to “Config -> Class Mode”… and choose what you need.
Doing this every time we need to view decompiled code or in assemble mode is not funny :)

Would be nice to have an extra option in the RMB that allow to choose to Edit instructions/Decompile/Edit with assembler.

CURRENT BEHAVIOR
![image](https://user-images.githubusercontent.com/3332674/81348878-eaf57f00-908c-11ea-9c03-64631f2b747c.png)

DESIRED BEHAVIOR (V1.5)
![image](https://user-images.githubusercontent.com/3332674/81348911-f8126e00-908c-11ea-9ff2-5cbd5a20f295.png)

**Comment by Col-E** [comment]
Re-reading this now, and I'd like to point out that you don't need to go into the config menu... I should probably point this out explicitly in the docs _(still a wip)_

![41s2oJudXq](https://user-images.githubusercontent.com/21371686/84910553-02108f00-b085-11ea-92ba-312a0772d366.gif)

And in the first picture, that is a class that is selected vs the second picture which is a method, so naturally the former would not have an edit instructions menu.

**Comment by pedroflor** [comment]
Wow... looks super!
Thanks again!

**Comment by Col-E** [comment]
Going to be updating the docs pages to be more clear about this one. They're kinda bare.

**Comment by zwb1988** [comment]
In version 1.x, after you click on edit with assembler option, I could have 1 window open for a method that is displaying in decompiled mode, and having another window to edit the op code at the same time. The decompiled window will also perform a live-update. Has this feature being removed since 2.x?

Also there were options to allow me insert before/after a certain line of op-code in the past version, it seems I couldn't do this in 2.x. It only has a editor with autocomplete. Having a place where I can select one op-code would be very helpful for beginners like me.

**Comment by Col-E** [comment]
> Has this feature being removed since 2.x?

The instruction inserter _(which I wrongfully called the opcode inserter... oops)_ has been removed. 

> Having a place where I can select one op-code would be very helpful for beginners like me.

Very good point. I didn't think about it from that perspective. I can add something like this back in a future update.

**Comment by zwb1988** [comment]
> Though I would also like to consider, would there be a better way to create something like this to help newcomers?

It would be cool to have tool-tips on op-code instructions, like showing quick explanations on the op-codes (a popup window). It will also be nice to have a code highlighting feature, where I can select op-codes to show which section of the decompiled code are referenced and vice versa. This would be awesome. Just some ideas. 

Looking forward to more awesome features in Recaf, this is a great app.

**Comment by Col-E** [comment]
I'm going to consider this resolved with the clarification of: https://github.com/Col-E/Recaf/issues/210#issuecomment-645408768

As for the other usability issues I've opened #230

**Comment by pedroflor** [comment]
Thank you so much!
