### ISSUE TITLE
Does not work with AdoptOpenJDK on Windows

### ISSUE THREAD

**Issue by 44trent3** [Col-E/Recaf#217]
Hi, I'm using AdoptOpenJDK on Windows, Java 8 update 242, and when I try to run Recaf, it tells me I have an outdated Java. I very obviously do not. When I run Recaf with an Oracle JDK, it runs perfectly fine and tells me nothing about Java supposedly being outdated.

Steps to reproduce:
1.) Use AdoptOpenJDK instead of Oracle JDK
2.) Attempt to run Recaf
3.) Be told that Java is outdated when it most certainly is not.

**Comment by Col-E** [comment]
I assume you're using the 1.15 release? Try the pre-releases on the releases page.

**Comment by Col-E** [comment]
Conducted a poll on the discord, will be merging the redesign later which will resolve this since this has been resolved in 2.0
