### ISSUE TITLE
some improvements

### ISSUE THREAD

**Issue by awesomennguy** [Col-E/Recaf#222]
## fields / methods highlighting
if method / field is not renamed then its red, otherwise its green (like in enigma deobfuscation tool)

## other
new "edit with assembler" window, it isnt bad but i prefer old version

And btw when i had "Goto definition" open too long recaf took almost 100% of processor

**Comment by Col-E** [comment]
> if method / field is not renamed then its red, otherwise its green

Recaf is not meant to focus on remapping like Enigma.

> "Goto definition" open too long recaf took almost 100% of processor

By default Recaf will open items with a decompiler. Perhaps the class causes some bug with the decompiler that causes it to hang? Do you have a sample that you can share?

> new "edit with assembler" window

Could you be specific about what parts of the previous design you prefer? Perhaps its something that can be added to the assembler?

**Comment by awesomennguy** [comment]
## about assembler
The current pretty good, but I would prefer if i would right click or if i would clicked 2 times a window would appear where i can edit desc / name / owner etc.

## 100% of processor
it was probably a bug, if i find what it causes i will report it

**Comment by awesomennguy** [comment]
Hi, will you add another asm window as I described?

**Comment by Col-E** [comment]
Perhaps in the future but its a low priority item compared to some other things I have on the todo list.

**Comment by Col-E** [comment]
The suggestion for the ASM window is now somewhat duplicated in the description of #230 

So I will close this and keep discussion on the UX improvement in the newer issue.
