### ISSUE TITLE
Tabs should be 4 spaces

### ISSUE THREAD

**Issue by illuminator3** [Col-E/Recaf#223]
If you try to press tab it writes 8 empty spaces. Normally a tab is 4 spaces long.

**Comment by Col-E** [comment]
I know :(

I haven't found a way to configure that yet. I'm probably just blind.

**Comment by xxDark** [comment]
It's harcoded into JavaFX and impossible to change without tons of bodges.

**Comment by Col-E** [comment]
Well, that sucks :(

**Comment by illuminator3** [comment]
Just listen for a TAB press and type 4 spaces

**Comment by Col-E** [comment]
Fixed in latest release
