### ISSUE TITLE
Different tabs

### ISSUE THREAD

**Issue by illuminator3** [Col-E/Recaf#224]
Add tabs to the top in which you can switch between different JARs that are opened

**Comment by Col-E** [comment]
[Recaf works in terms of workspaces](https://col-e.github.io/Recaf/doc-intro-workspace.html).  See the picture below:

![workspace](https://col-e.github.io/Recaf/screenshots/workspace-diagram.png)

A workspace may have multiple files included in it. You can switch between them in the navigation tree seen in the animation below:

![animation](https://user-images.githubusercontent.com/21371686/84942979-af999780-b0b1-11ea-8207-c1a9baa27475.gif)
