### ISSUE TITLE
Add Krakatau decompiler

### ISSUE THREAD

**Issue by awesomennguy** [Col-E/Recaf#226]
Title says all, decompilers like krakatau etc...

**Comment by Janmm14** [comment]
Would love to see this implemented!

**Comment by Janmm14** [comment]
One can do it by adding a gui with a list of library jars where you can add, edit, delete the paths.
Then one needs an option to set pypy2/python2 executable path.
You need a directory to unpack Krakatau.
Create a new jar file with just the class to decompile in it.
Build path with libraries from user settings + original jar file. Paths separated with `;`.
Specify some unique output.zip
Then you execute python in krakatau dir. And grab decompiled java file from output zip.

**Comment by node3112** [comment]
If you don't want to create a new process, you could embed the Python interpreter that runs Krakatau in Recaf with something like https://github.com/ninia/jep. 
However, you would need Python installed (with the required libraries) for this to work, but you could have a prompt, or something of the sort saying that Python is required?
Additionally, Krakatau's decompiler is Python 2, and you'd probably have to upgrade it to Python 3 (which isn't too bad to do).
Just a consideration for a "cleaner" approach to implementing this, there are probably better ways though.

**Comment by Janmm14** [comment]
Krakatau dev said its hard to update it to python 3. Also krakatau 2 benefits from pypy quite well.
So maybe this should wait for krakatau 3 where you don't need libraries and the cli will be a little easier to use with class file in, class file out option.

**Comment by node3112** [comment]
Yeah that definitely seems like the best option for now.

**Comment by Storyyeller** [comment]
FYI, I'm also planning to remove the decompiler JRE/path requirement thing during the rewrite.

**Comment by Col-E** [comment]
Not happening, incompatible licenses.

**Comment by notiska** [comment]
Just noticed this issue.
I will say that I have updated krakatau myself to Python 3, and made a plugin a while ago to add it to Recaf 3 (via jep).
I can share if you want, I am working on a new plugin that doesn't require Python to be installed at all.
