### ISSUE TITLE
Scroll position not kept when renaming

### ISSUE THREAD

**Issue by fuwwy** [Col-E/Recaf#228]
**Describe the bug**

When a field, method, or class is renamed, the decompiler view is reset and the scroll position goes back to the start.

**To Reproduce**

1. Open any jar file
2. Navigate to any class
3. Rename a field or method
4. The decompiler pane will reload and the scroll position will be back on top

**Comment by Col-E** [comment]
Perhaps a temporary listener that waits until the content is populated can be added that sets the scroll position after decompilation.

**Comment by Col-E** [comment]
This will be included in the next release _(auto-release didn't trigger)_
