### ISSUE TITLE
Implement in Mappings

### ISSUE THREAD

**Issue by Jose82153** [Col-E/Recaf#233]
Implement in Mappings - Apply Map File - JADX?

**Comment by Col-E** [comment]
JADX has mapping support? I'll take a look if you can give an example.

**Comment by Jose82153** [comment]
By activating Deobfuscation it generates a map file, but it does not follow the standards accepted by Recaf.
Output example:
c android.support.a.a.a = C0000a
c android.support.a.a.b = C0001b
c android.support.a.a.c = C0002c
c android.support.a.a.d = C0003d
c android.support.a.a.e = C0004e
c android.support.a.b.a = C0005a
f android.support.a.a.b.a:Landroid/app/Activity; = f0a
f android.support.a.a.b.b:[Ljava/lang/String; = f1b
f android.support.a.a.b.c:I = f2c
f android.support.a.b.a.a:Ljava/lang/Object; = f3a
m android.support.a.a.a.a(Landroid/app/Activity;[Ljava/lang/String;I)V = m0a
m android.support.a.a.c.a(I[Ljava/lang/String;[I)V = mo2a
m android.support.a.a.d.a(Landroid/app/Activity;[Ljava/lang/String;I)V = m2a
m android.support.a.a.e.a(I)V = mo3a

**Comment by Col-E** [comment]
Ah, looks relatively parse-able. Not the cleanest format ever but certainly do-able.

**Comment by Jose82153** [comment]
Please take a test.
Thank you.

**Comment by Jose82153** [comment]
I placed the order below for the Jadx creator:
Would it be possible to implement the output of obfuscation map file in the Proguard standards?
So far I have not received an answer.
Thanks.

**Comment by Col-E** [comment]
Oh proguard's mapping system is even worse :rofl: 

This is fine. I'll get around to adding it soon.

**Comment by Jose82153** [comment]
I was flattered by the attention.
Thanks.

**Comment by Col-E** [comment]
Should be good to go in `2.3.0`

**Comment by Jose82153** [comment]
The Class did not stay in the correct Packages.
Roughly speaking it would be:
map.put (args [1] .replace ('.', '/'), args [1] .replace ('.', '/') + args [2] .replace ('.', '/' ));
Before:
// c android.support.a.b.a = C0005a
After:
// c android.support.a.b.a = android.support.a.b.aC0005a
The ideal would be to remove that first "a" in "aC0005a".
I am very happy with what has already been done.
Thanks.

**Comment by Col-E** [comment]
Aaah. I assumed the latter was the full path. So it stays in the same package then. Easy fix.

**Comment by Jose82153** [comment]
If it gets better, it spoils.
Thank you very much.
