### ISSUE TITLE
Path not updated after renaming a file

### ISSUE THREAD

**Issue by FlowArg** [Col-E/Recaf#234]
**Describe the bug**
The path is not updated after renaming a file. A Recaf reboot is required to update the path correctly.

**To Reproduce**

1. Open Recaf ([2.3.3](https://github.com/Col-E/Recaf/releases/download/2.3.3/recaf-2.3.3-J8-jar-with-dependencies.jar))
2. Load a jar file
3. Rename a file
4. the `editor#getPath` is not updated (you can check this by creating a Recaf plugin an print them)
5. export program, the path is still not updated.
6. You have to restart Recaf and load the recently exported program to had the good `editor#getPath`

**Screenshots**
I discovered this bug with my [RPC Plugin](https://github.com/FlowArg/RecafPluginRPC/)
Before renaming :
![image](https://user-images.githubusercontent.com/52298108/88265664-31db3400-ccce-11ea-86c7-6de3419758dd.png)
After renaming :
![image](https://user-images.githubusercontent.com/52298108/88265710-44556d80-ccce-11ea-8239-55c1014c753e.png)
After program export :
![image](https://user-images.githubusercontent.com/52298108/88267809-aa8fbf80-ccd1-11ea-9e0a-38681c4f12db.png)
After Recaf reboot :
![image](https://user-images.githubusercontent.com/52298108/88266143-f7be6200-ccce-11ea-98df-fe9ba8ac2981.png)

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/88363472-2891ac00-cd4e-11ea-871b-8a8a9039639e.png)

The plugin works fine for me. Threw up a video reference in the discord too.

**Comment by FlowArg** [comment]
Hum, it works fine now but I don't know why yesterday it was not working :shrug:.
