### ISSUE TITLE
Compile snippets into bytecode in assembler

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#245]
## Compile snippets into bytecode in assembler

The idea is to allow users to open a method assembler, then open a prompt allowing them to type in something like `System.out.println("test")`. This line would then be compiled against the current source and inserted into the assembler as lines of method bytecode.

It would be nice to support arbitrary variable support too, such as: `if ($0 != 0){} ` --> `*LOAD 0`

**Comment by Crystallinqq** [comment]
I would shit my pants if this happened.

**Comment by andylizi** [comment]
> I would shit my pants if this happened.

[Javassist](https://www.javassist.org/tutorial/tutorial2.html) kinda already has this feature, up to and including variables support:
```java
class Point {
    int x, y;
    void move(int dx, int dy) { x += dx; y += dy; }
}
```
```java
ClassPool cp = ClassPool.getDefault();
CtClass cc = cp .get("Point");
CtMethod m = cc.getDeclaredMethod("move");
m.insertBefore("{ System.out.println(\"dx = \" + $1 + \", dy = \" + $2); }");
Class c = cc.toClass();
Point p = (Point) c.newInstance();
p.move(4, 2);
```

**Comment by xxDark** [comment]
> 
> 
> > I would shit my pants if this happened.
> 
> [Javassist](https://www.javassist.org/tutorial/tutorial2.html) kinda already has this feature, up to and including variables support:
> 
> ```java
> class Point {
>     int x, y;
>     void move(int dx, int dy) { x += dx; y += dy; }
> }
> ```
> 
> ```java
> ClassPool cp = ClassPool.getDefault();
> CtClass cc = cp .get("Point");
> CtMethod m = cc.getDeclaredMethod("move");
> m.insertBefore("{ System.out.println(\"dx = \" + $1 + \", dy = \" + $2); }");
> Class c = cc.toClass();
> Point p = (Point) c.newInstance();
> p.move(4, 2);
> ```

We discussed that on Discord, however, there are some problems:
How can we use values from the stack without registers?
Javassist does not support ASM, so all the output must be converted.

**Comment by andylizi** [comment]
> How can javassist access the value on the stack?

No it can't - at least, not in its current state. After some digging however, I believe its possible to make it work without major modifications.

Javassist has a complete lexer/parser/bytecode-generator system just built for this, like a lightweight version of [JavaParser](https://javaparser.org/). It will first [parse the statement](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/Javac.java#L563-L580) using a [pre-populated symbol table](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/CtBehavior.java#L781-L785) and generate an AST tree representation. Then the corresponding bytecode will be emitted at the various [`at***` methods](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/ast/ASTree.java#L40-L45) in [`CodeGen`](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/CodeGen.java), [`MemberCodeGen`](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/MemberCodeGen.java) and [`JvstCodeGen`](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/JvstCodeGen.java). One of these methods, [`atVariable`](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/CodeGen.java#L1944-L1972), goes like this:
```java
@Override
public void atVariable(Variable v) throws CompileError {
    Declarator d = v.getDeclarator();
    exprType = d.getType();
    arrayDim = d.getArrayDim();
    className = d.getClassName();
    int var = getLocalVar(d);

    if (arrayDim > 0)
        bytecode.addAload(var);
    else
        switch (exprType) {
        case CLASS :
            bytecode.addAload(var);
            break;
        case LONG :
            bytecode.addLload(var);
            break;
        case FLOAT :
            bytecode.addFload(var);
            break;
        case DOUBLE :
            bytecode.addDload(var);
            break;
        default :   // BOOLEAN, BYTE, CHAR, SHORT, INT
            bytecode.addIload(var);
            break;
        }
}
```
As you can see, this kind of structuring makes it easy to implement our own bytecode emitter that works on the stack. We won't even need to change the pesky parser part (except [here](https://github.com/jboss-javassist/javassist/blob/b70a41bf52/src/main/javassist/compiler/Parser.java#L1250-L1255)), just feed it some type info about things-on-stack through the symbol table and write some custom `at***` generators and it magically works. At least, it should. Never done this before but don't see why it shouldn't - a value is a value, no matter whether it comes from a variable or the stack. It won't be 'piece of cake' level of easy, but it should work.

**Comment by Col-E** [comment]
Progress :)

![image](https://user-images.githubusercontent.com/21371686/102156411-82a12400-3e4b-11eb-936b-705e88b93927.png)

**Comment by Col-E** [comment]
@Crystallinqq time to shit your pants: [2.16.0](https://github.com/Col-E/Recaf/releases/tag/2.16.0)

**Comment by Col-E** [comment]
Not closing yet since it still can be improved with points mentioned on the thread so far.

But the basic idea is now usable 👍

**Comment by Crystallinqq** [comment]
@Col-E just shit my pants.

**Comment by Col-E** [comment]
Could be improved, but variable support is in!

**Comment by milahu** [comment]
> @Crystallinqq time to shit your pants: [2.16.0](https://github.com/Col-E/Recaf/releases/tag/2.16.0)

> Assembler now supports inline expressions with EXPR keyword (8911d66)

sample:

in the java code view, find the function `isAlwaysConnectRequired`,
rightclick, edit with assembler, modify the assembler code ...

```diff
 DEFINE PUBLIC FINAL isAlwaysConnectRequired()Z
 A:
 LINE A 105
-INVOKESTATIC org/appwork/utils/Application.isHeadless()Z
-IRETURN
+EXPR return false;
 B:
```

... hit `Control + S`, close dialog, now the java code has changed

```diff
     public final boolean isAlwaysConnectRequired() {
-        return Application.isHeadless();
+        return false;
     }
```

i tried to edit the java code directly, but this has no effect on the bytecode.
(dear santa, please implement this for christmas ...)

maybe the java code should be read-only?

**Comment by Col-E** [comment]
3X will greatly improve this feature. There are still some caveats, but most common items will be do-able. Here's some examples:

```java
static interceptData(Ljava/lang/String; data)V
a:
 expr {
    if (data != null && !data.isEmpty()) {
        System.out.println("INTERCEPT: " + data);
    } else {
        // something else
    }
 }
b:
 return
end:
```
```java
static handleCode(I code)V
a:
 expr {
    int range = code - (code % 100);
    switch(range) {
     case 100: System.out.println("INFO"); break;
     case 200: System.out.println("SUCCESS"); break;
     case 300: System.out.println("REDIRECT"); break;
     case 400: System.out.println("CLIENT-ERROR"); break;
     case 500: System.out.println("SERVER-ERROR"); break;
     default: break;
    }
 }
b:
 return
end:
```
```java
static deleteFile(Ljava/lang/String; fileName)Z
a:
 // deleted = false;
 iconst_0
 istore deleted
 // delete and update flag, with try-catch for error handling
 expr {
    try {
        deleted = new java.io.File(fileName).delete();
    } catch(Throwable t) {
        System.out.println("Error!");
    }
 }
b:
 // return deleted;
 iload deleted
 ireturn
end:
```

**Comment by Col-E** [comment]
Closing since this is part of 3X and will be improved upon on that branch/release.
