### ISSUE TITLE
Line number size doesn't follow the size of the font

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#247]
**Line number size doesn't follow the size of the font**

an image speaks a thousand words :)

**Font size: 11 (the line numbers doesn't feet goot)**
![image](https://user-images.githubusercontent.com/3332674/91093626-ab48a800-e627-11ea-8f74-cd4942f9c839.png)

**Same window, with font size 12**
![image](https://user-images.githubusercontent.com/3332674/91093722-cddac100-e627-11ea-8210-3a0465a06755.png)

**Comment by Col-E** [comment]
CSS for the line-number node: [text-dark.css](https://github.com/Col-E/Recaf/blob/master/src/main/resources/style/text-dark.css#L19)

I imagine updating the generated CSS in [FontSlider.java](https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/ui/controls/FontSlider.java) can resolve this.

**Comment by Col-E** [comment]
Fixed in d65a404142478ac92c5dfa4ff2d287546e7301a5

**Comment by pedroflor** [comment]
Thank you so much!
