### ISSUE TITLE
Bad format for DEFINE

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#254]
#### Case 1
```
DEFINE FINE()V
```
This causes `Bad format for DEFINE` error, where `FINE` can be any substring of `DEFINE` like `D`, `E`, `F`, `DEF`, `IN`, etc.

#### Case 2
```
DEFINE PUBLIC LI()V
```
This causes `Illegal method modifier` error, where `LI` can be any substring of `PUBLIC` that doesn't start with `P`. It won't throw error when it does start with `P` but I'm sure the parsed result will likely be garbage anyway.

#### Problem
https://github.com/Col-E/Recaf/blob/d731c036482c32f595b5c5e6c983fff7ad1c4c5c/src/main/java/me/coley/recaf/parse/bytecode/parser/MethodDefinitionParser.java#L24-L27
https://github.com/Col-E/Recaf/blob/d731c036482c32f595b5c5e6c983fff7ad1c4c5c/src/main/java/me/coley/recaf/parse/bytecode/parser/MethodDefinitionParser.java#L39-L40
`trim.indexOf(name)` should be `nameStart`.

**Comment by Col-E** [comment]
👍 Fixed, will push then close when I have some more stuff to add
