### ISSUE TITLE
compilation failure in Java8

### ISSUE THREAD

**Issue by mcgyver5** [Col-E/Recaf#26]
The project failed to compile for me in Java 8:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project recaf: Compilation failure
[ERROR] /Documents/Crackmes/JavaCrackmes/recaf/Recaf/src/me/coley/recaf/asm/OpcodeUtil.java:[147,72] incompatible types: inference variable T has incompatible bounds
[ERROR] equality constraints: java.lang.String,E
[ERROR] lower bounds: java.lang.Object
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project recaf: Compilation fai
/Documents/Crackmes/JavaCrackmes/recaf/Recaf/src/me/coley/recaf/asm/OpcodeUtil.java:[147,72] incompatible types: inference variable T has incompatible bounds
    equality constraints: java.lang.String,E
    lower bounds: java.lang.Object
		
Eclipse has a bug report that seems to address this (https://bugs.eclipse.org/bugs/show_bug.cgi?id=469297)
As the bug report suggests, Eclipse 4.6.3 did not detect this problem in the code.

Changing the code on line 147:
	/**
	 * Empty list.
	 */
	public static final Set<String> OPS_EMPTY = Stream.of("").collect(Collectors.toCollection(LinkedHashSet<String>::new)); 

That allowed it to compile and Recaf seemed to work just fine.  Don't know the real consequences of this change!

**Comment by Col-E** [comment]
The fix is to:

     public static final Set<String> OPS_EMPTY = new HashSet<>();

I just haven't been able to hop on my machine to push some things due to being with family over the holidays. This and a few more things will be pushed tomorrow.

**Comment by Col-E** [comment]
On outdated mobile browser so can't edit the last comment, but as long as the set is empty everything should work fine. Yours includes the empty string in the set.

**Comment by andylizi** [comment]
... you can use 
```java
public static final Set<String> OPS_EMPTY = Collections.emptySet();
```
[java.util.Collections#emptySet()](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#emptySet--)

**Comment by Col-E** [comment]
Resolved in last few commits.
