### ISSUE TITLE
Adding new things to classes or creating new classes?

### ISSUE THREAD

**Issue by MizzMaster** [Col-E/Recaf#267]
Is there any way to add a new variable, method or class to the existing class by using any part of Recaf?

**Comment by Col-E** [comment]
Its on the TODO list

**Comment by Col-E** [comment]
This will be added in `2.11.0`

![WFyj05294y](https://user-images.githubusercontent.com/21371686/95550334-b89ed380-09d6-11eb-8ae5-39a2933a86c3.gif)

**Comment by xperia64** [comment]
Is there a to add a new field in table/disassembly mode only? I'm working with some class files which do not decompile correctly in any backend, plus I would prefer to work with the disassembly where possible here.

**Comment by Col-E** [comment]
Oh yeah, thats an oversight on my part. At the moment table mode doesn't have the ability to add new items, but it should be an easy fix.
