### ISSUE TITLE
A bug while renaming variables

### ISSUE THREAD

**Issue by MizzMaster** [Col-E/Recaf#268]
Hello, actually I have to say that Recaf is a very nice tool that I found. Both GUI and background stuff are cool. But I found a bug while renaming variable names. I wish I could send the jar file but I dont own it. Let me explain the bug.

Lets say there are 2 classes named **A** and **B**, and **B** extends **A**. When I try to rename a variable in **A**, it renames all the variables matching in **A**(and maybe some other classes), but it doesn't rename that variable on **B** class. And this causes to crash the program(not Recaf).

The error when this bug happens: `java.lang.NoSuchFieldError: variableName`

Actually I could challange with this by renaming the variables back to original ones, but it took long and i think this bug is an unintended thing when renaming.

Thanks for replying my issues.

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/92842508-a28afc80-f3b1-11ea-8218-590b560df2ab.png)

[Demo.jar.zip](https://github.com/Col-E/Recaf/files/5205502/Demo.jar.zip)

So the problem is the _"virtual"_ nature of fields. Likely an easy fix, [somewhere around here](https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/ui/controls/RenamingTextField.java#L197).

**Comment by MizzMaster** [comment]
Actually it is not just happening while renaming values, i found something more and i have to say them.

A, B, C, ... are classes. (...)(more classes that extends each other like this) C extends B and B extends A. The references in all (...) C and B have to be renamed when i rename a variable in A.

When searching through member references, if i go there by using gui(right click and search references), the owner's name does fill with class's name and cant search extended classs' variable references

**Comment by Col-E** [comment]
I'm not sure I follow this second example you gave. Can you create a minimal reproducible example and drop a zip file here containing the classes?

**Comment by Col-E** [comment]
I have fixed the issue with field renaming and will push an update shortly. 

Regarding the follow-up comment, I am not sure what you mean. Can you open a new issue with more details about this second renaming bug?

**Comment by MizzMaster** [comment]
Actually I was saying that if I rename a variable on a super class, it has to be renamed on all child and child's child ... and so on.
You also fixed this on v2.7.0.

My second thing in that post is, if I search a super class's variable by right clicking it and selecting "Search References", it auto fills "Owner" section by this super class's name, and causes me to can't find references on child classes, because child classes gets this variable by its  own name (`GETFIELD Child.parentsVariable`), so i clear the "Owner" section but then i get lots and lots of search result because of obfuscation has renamed variables like a,b,c...

My advice is, add an option button or box while searching variables, something like 'Also search on child classes'

**Comment by Col-E** [comment]
Oh that's a good point for searching
