### ISSUE TITLE
Add new language ' zh-tw' ?

### ISSUE THREAD

**Issue by skysumbra** [Col-E/Recaf#270]
## Feature_Name
Add new language
Description of the feature
May I creat language with zh-tw ？

**Comment by Col-E** [comment]
Sure, feel free to.

Also so you know in advance, not all the text in the translation is used in the Recaf user interface. Some of the text in there is leftover from older versions, I've just not gotten around to removing it yet.

**Comment by skysumbra** [comment]
Where can find the language file in this project ?
Just for reference with Strings.

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/tree/master/src/main/resources/translations
