### ISSUE TITLE
Error [java.io.IOException: File too large] while I try to start it with JDK

### ISSUE THREAD

**Issue by xlhyjx8** [Col-E/Recaf#273]
while I just double-click the file recaf-2.6.0-J8-jar-with-dependencies.jar, It start bug with jre not jdk
![recaf系统信息](https://user-images.githubusercontent.com/53360259/92995979-98483a00-f53a-11ea-9026-f6860a8d9ef3.png)

So I use the cmd to start by using
cd C:\Program Files\Java\jdk1.8.0_261\
javaws "C:\KK File\ASCIIpath\recaf\recaf-2.6.0-J8-jar-with-dependencies.jar"
It report Error Can't Start this application 
![javaw报错](https://user-images.githubusercontent.com/53360259/92995970-88c8f100-f53a-11ea-8bda-d4e2b2a5e985.png)

CouldNotLoadArgumentException[ 无法加载指定的文件/URL: C:\KK File\ASCIIpath\recaf\recaf-2.6.0-J8-jar-with-dependencies.jar]
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: File too large
	at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
	... 5 more

So why File is too large?It just 26MB. What should I do?

OS windows 10 
JDK Oracle jdk1.8.0_261
I also try openjdk-8u41-b04-windows-i586-14_jan_2020 but it also does not work and report the same error.
Recaf recaf-2.6.0-J8-jar-with-dependencies.jar

**Comment by Col-E** [comment]
I think there may be multiple problems here, but lets just start with the most obvious one...

When you install the JDK/JRE windows should assign `jar` files to double click open with `javaw -jar %s`. It looks like for some reason it wants to use `javaws` instead, which is not correct. 

Run it again with `java` or `javaw` if you do not want to allocate a console and it should start fine. I would also suggest reinstalling JDK 8 so that the file type association with `jar` does not use this `javaws` command anymore too.

**Comment by xlhyjx8** [comment]
Thank you for your reply.
I already re-installed JDK before I open this issues. Re-install JDK version jdk1.8.0_261.
After your reply this,I restart my computer, and restart recaf using

cd %java_home%
java -jar "C:\KK File\ASCIIpath\recaf\recaf-2.6.0-J8-jar-with-dependencies.jar"

in windows cmd.exe.

but it still using JRE not JDK and report 

20:27:30.791 [main] ERROR: Failed to load attach library.
java.io.FileNotFoundException: Could not locate tools.jar
        at me.coley.recaf.util.Natives.loadAttach(Natives.java:48)
        at me.coley.recaf.Recaf.main(Recaf.java:44)
20:27:31.442 [main] INFO : Recaf-2.6.0

in windows cmd.exe.

My OS's system Environment Variable:
JAVA_HOME is C:\Program Files\Java\jdk1.8.0_261
CLASSPATH is .;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
PATH contains C:\Program Files\Java\jdk1.8.0_221\bin;C:\Program Files\Java\jdk1.8.0_221\jre\bin;
Is that correct?

My recaf-2.6.0-J8-jar-with-dependencies.jar is updated from recaf-1.15.7.jar, recaf-1.15.7.jar works well but it removed the method's Annotation while I edited and saved the command(bytecode) of the method so my project doesn't work

**Comment by Col-E** [comment]
So for attach then, you need to start Recaf with the `java` exe from the jdk bin. When you install oracle's JRE it adds some windows paths that will overshadow the JDK (`C:/javapath` or something). This stack exchange post has more details: https://superuser.com/questions/479889/wrong-java-version-being-reported

As for the annotations that is a separate issue. They should be copied over. I'll look into pushing out a fix for that when I can recreate a jar that has the problem in it.

**Comment by xlhyjx8** [comment]
OK , Using jdk/bin I finished my editor.
Thank you for your help!

**Comment by xlhyjx8** [comment]
About 
As for the annotations that is a separate issue. They should be copied over. I'll look into pushing out a fix for that when I can recreate a jar that has the problem in it.
I can send you that jar which the annotation missing to help you fix this problem.
recaf-2.6.0-J8-jar-with-dependencies works well with the annotation.
recaf-1.15.7.jar remove the annotation.
So how can send this file to you?Send this to your email?

**Comment by Col-E** [comment]
You can dm me on discord, profile is on my github bio.

**Comment by xlhyjx8** [comment]
I create a discord account named xlhyjx8#2393 and send the friend apply to Col-E#6255.Please allow
