### ISSUE TITLE
UI should rely on CLI commands

### ISSUE THREAD

**Issue by xxDark** [Col-E/Recaf#276]
Currently most of the UI stuff does not rely on CLI, as it was supposed to be.
See #151

**Comment by Col-E** [comment]
Yeah.... I've not done such a good job with that...

**Comment by Col-E** [comment]
Another thing, I'd like to consider ways to improve upon the CLI command setup.

For instance, you can search in the CLI and see things, but these serve no function when automating tasks. I wonder how we can remedy that?

Some ideas:
 - Caching most recent search and having commands that work off of that
 - Storing the return value of commands into variables that can be referenced by commands

**Comment by guschoYB** [comment]
Hi

**Comment by Col-E** [comment]
Closing as 3.X will address this with its new design philosophy.

The core module will provide all common api-like features and the UI module will provide a both a UI and a CLI that tie back into the core. This way the UI is not limited by the CLI design.
