### ISSUE TITLE
Recaf crashes due to path lookup failure via Powershell/Directories-JVM

### ISSUE THREAD

**Issue by SetoKaiba** [Col-E/Recaf#278]
**Describe the bug**

Can't run the recaf-2.7.0-J8-jar-with-dependencies.jar with corretto-11.0.8.10.1 on Windows 10.

**To Reproduce**

1. java -jar recaf-2.7.0-J8-jar-with-dependencies.jar
2. See error

**Exception**

If applicable, add the exception/stacktrace.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at me.coley.recaf.Recaf.init(Recaf.java:75)
        at me.coley.recaf.Recaf.main(Recaf.java:45)
Caused by: java.lang.NullPointerException
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at me.coley.recaf.Recaf.getDirectory(Recaf.java:167)
        at me.coley.recaf.Recaf.getDirectory(Recaf.java:177)
        at me.coley.recaf.util.self.SelfDependencyPatcher.<clinit>(SelfDependencyPatcher.java:28)
        ... 2 more
```

**Screenshots**

**Comment by Col-E** [comment]
Huh, seems like `Paths.get(BaseDirectories.get().configDir)` is `null` for you then.... That shouldn't happen...
Does it work on Corretto for Java 8 or if you re-run Recaf?

**Comment by xxDark** [comment]
Please run `powershell -EncodedCommand JgAgAHsACgBbAEMAbwBuAHMAbwBsAGUAXQA6ADoATwB1AHQAcAB1AHQARQBuAGMAbwBkAGkAbgBnACAAPQAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgACgBBAGQAZAAtAFQAeQBwAGUAIABAACIACgB1AHMAaQBuAGcAIABTAHkAcwB0AGUAbQA7AAoAdQBzAGkAbgBnACAAUwB5AHMAdABlAG0ALgBSAHUAbgB0AGkAbQBlAC4ASQBuAHQAZQByAG8AcABTAGUAcgB2AGkAYwBlAHMAOwAKAHAAdQBiAGwAaQBjACAAYwBsAGEAcwBzACAARABpAHIAIAB7AAoAIAAgAFsARABsAGwASQBtAHAAbwByAHQAKAAiAHMAaABlAGwAbAAzADIALgBkAGwAbAAiACkAXQAKACAAIABwAHIAaQB2AGEAdABlACAAcwB0AGEAdABpAGMAIABlAHgAdABlAHIAbgAgAGkAbgB0ACAAUwBIAEcAZQB0AEsAbgBvAHcAbgBGAG8AbABkAGUAcgBQAGEAdABoACgAWwBNAGEAcgBzAGgAYQBsAEEAcwAoAFUAbgBtAGEAbgBhAGcAZQBkAFQAeQBwAGUALgBMAFAAUwB0AHIAdQBjAHQAKQBdACAARwB1AGkAZAAgAHIAZgBpAGQALAAgAHUAaQBuAHQAIABkAHcARgBsAGEAZwBzACwAIABJAG4AdABQAHQAcgAgAGgAVABvAGsAZQBuACwAIABvAHUAdAAgAEkAbgB0AFAAdAByACAAcABzAHoAUABhAHQAaAApADsACgAgACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAHMAdAByAGkAbgBnACAARwBlAHQASwBuAG8AdwBuAEYAbwBsAGQAZQByAFAAYQB0AGgAKABzAHQAcgBpAG4AZwAgAHIAZgBpAGQAKQAgAHsACgAgACAAIAAgAEkAbgB0AFAAdAByACAAcABzAHoAUABhAHQAaAA7AAoAIAAgACAAIABpAGYAIAAoAFMASABHAGUAdABLAG4AbwB3AG4ARgBvAGwAZABlAHIAUABhAHQAaAAoAG4AZQB3ACAARwB1AGkAZAAoAHIAZgBpAGQAKQAsACAAMAAsACAASQBuAHQAUAB0AHIALgBaAGUAcgBvACwAIABvAHUAdAAgAHAAcwB6AFAAYQB0AGgAKQAgACEAPQAgADAAKQAgAHIAZQB0AHUAcgBuACAAIgAiADsACgAgACAAIAAgAHMAdAByAGkAbgBnACAAcABhAHQAaAAgAD0AIABNAGEAcgBzAGgAYQBsAC4AUAB0AHIAVABvAFMAdAByAGkAbgBnAFUAbgBpACgAcABzAHoAUABhAHQAaAApADsACgAgACAAIAAgAE0AYQByAHMAaABhAGwALgBGAHIAZQBlAEMAbwBUAGEAcwBrAE0AZQBtACgAcABzAHoAUABhAHQAaAApADsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAcABhAHQAaAA7AAoAIAAgAH0ACgB9AAoAIgBAAAoAWwBEAGkAcgBdADoAOgBHAGUAdABLAG4AbwB3AG4ARgBvAGwAZABlAHIAUABhAHQAaAAoACIANQBFADYAQwA4ADUAOABGAC0AMABFADIAMgAtADQANwA2ADAALQA5AEEARgBFAC0ARQBBADMAMwAxADcAQgA2ADcAMQA3ADMAIgApAAoAWwBEAGkAcgBdADoAOgBHAGUAdABLAG4AbwB3AG4ARgBvAGwAZABlAHIAUABhAHQAaAAoACIAMwBFAEIANgA4ADUARABCAC0ANgA1AEYAOQAtADQAQwBGADYALQBBADAAMwBBAC0ARQAzAEUARgA2ADUANwAyADkARgAzAEQAIgApAAoAWwBEAGkAcgBdADoAOgBHAGUAdABLAG4AbwB3AG4ARgBvAGwAZABlAHIAUABhAHQAaAAoACIARgAxAEIAMwAyADcAOAA1AC0ANgBGAEIAQQAtADQARgBDAEYALQA5AEQANQA1AC0ANwBCADgARQA3AEYAMQA1ADcAMAA5ADEAIgApAAoAfQA=` and post results.

`getWinDirs` in the library mention above return null for some reason.

**Comment by SetoKaiba** [comment]
OK. It's working now. I use the powershell command and find out the problem. The path will return null if I have invalid LIB environment variable.

**Comment by SetoKaiba** [comment]
I think maybe should tell the user to check the LIB environment variable, if the path returns null.

**Comment by xxDark** [comment]
For what `LIB` env. variable is responsible for?

**Comment by SetoKaiba** [comment]
It was the vc sdk folder. But it's deleted after updated my visual studio. But the LIB env is not removed. So the powershell doesn't work. And the path returns null as well.

**Comment by xxDark** [comment]
I think that you might open an issue in upstream to add fallback path if powershell trick fails.

**Comment by Col-E** [comment]
Added a manual `System.getEnv(...)` call I'm not going to close this because I would prefer this be handled properly upstream.

You can hop on the discussion here: https://github.com/dirs-dev/directories-jvm/issues/43
 - Especially give a 👍 to the guy who made a PR that fixes this

**Comment by Col-E** [comment]
Renaming to be more clear. This is fixed in `2.13.1` atm.

**Comment by soc** [comment]
I have released versions 22 and 23 which hopefully address this issue.

Version 22 make the library not throw an exception if there is an issue, and version 23 tries to be a bit sneakier trying to retrieve the values. Use 23, but if there are issues with the approach you can fall back to 22, while we have a new look at the problem.

**Comment by Col-E** [comment]
Thank you!

**Comment by Col-E** [comment]
Closing as this has been resolved for the mostpart
