### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by novakzs** [Col-E/Recaf#283]
**Describe the bug**

When the program is running, but I'm not interacting with it, after some time(5-10-20 minutes), I'm starting to see high CPU usage on one core. If I then interact with the editor window, the CPU usage drops down to normal.

**To Reproduce**

I cannot reliably reproduce it. The app has to be out of focus, but not minimized. Something is always opened with the assembler or a decompiler. After that, it's just a matter of time until the bug manifests itself.

I'm using Windows 10 1809 and an Azul "Zulu+FX" jdk 11.0.8+10
It affects at least every recaf version between 2.3.6 and 2.7

I attached a short jfr recording 
[flight_recording_1108Dworkjavatoolsrecafrecaf270J8jarwithdependenciesjar9492.zip](https://github.com/Col-E/Recaf/files/5240461/flight_recording_1108Dworkjavatoolsrecafrecaf270J8jarwithdependenciesjar9492.zip)

**Comment by Col-E** [comment]
> between 2.3.6 and 2.7

So, does 2.3.5 not have this problem?

**Comment by xxDark** [comment]
Anything interesting if you start Recaf with `-Dprism.verbose=true` flag?

**Comment by novakzs** [comment]
I can't say anything about that.
Before 2.3.6 I only used recaf sparsingly and in short sessions(basically: open program -> edit something -> close program).
I've only started using recaf in multi hour sessions since 2.3.6, and that is when I started noticing this bug. so I guess the change of usage contributed more than a change between versions.

**Comment by novakzs** [comment]
> Anything interesting if you start Recaf with `-Dprism.verbose=true` flag?
> Can you also please attach logs?

It may take some time, but I will try it to see what happens

**Comment by novakzs** [comment]
Here are the logs

[rclog.txt](https://github.com/Col-E/Recaf/files/5241106/rclog.txt)
[1.log](https://github.com/Col-E/Recaf/files/5241167/1.log)

One comment: 

After the CPU usage went down to normal, I clicked on the config menu, the application became unresponsive and I had to forcefully kill it. I don't know how that affects the logs.

**Comment by xxDark** [comment]
> After the CPU usage went down to normal, I clicked on the config menu, the application became unresponsive and I had to forcefully kill it. I don't know how that affects the logs.

Could you please join Recaf's Discord server for further investigation?
It will speed up communication process a lot.

**Comment by Col-E** [comment]
Closing as 3X idling has been vastly reduced: https://github.com/Col-E/Recaf/issues/541
