### ISSUE TITLE
Hyperlinks in MANIFEST.MF

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#288]
Something like this
![JD-GUI example](https://user-images.githubusercontent.com/12008103/93658770-23608d00-fa71-11ea-9c8f-fd9d34e4dbfb.png)
could be helpful when investigating obfuscated code. Otherwise one would have to either (a) click on each level of package and find the exact class in a sea of `a` `b` `c` names and hope that you didn't click into the wrong package by accident, or (b) use the search bar and pay careful attention to the case-sensitive fully-qualified name.

**Comment by win32kbase** [comment]
Added in above mentioned PR.
