### ISSUE TITLE
Word wrapping in decompile window

### ISSUE THREAD

**Issue by tomtastic** [Col-E/Recaf#293]
## Word wrapping

I'd like to have the option of wrapping long lines in the decompile window, to make it easier to see them without lots of scrolling.

eg.
![image](https://user-images.githubusercontent.com/302127/93918154-da743700-fd03-11ea-9758-57dd182f3216.png)
![image](https://user-images.githubusercontent.com/302127/93918343-1ad3b500-fd04-11ea-95a3-dcf4d9dc9b11.png)

**Comment by Col-E** [comment]
Will be added in `2.11.0`

![image](https://user-images.githubusercontent.com/21371686/95549785-e5062000-09d5-11eb-8489-727068be7c85.png)

![R4ptesc4Ni](https://user-images.githubusercontent.com/21371686/95550049-44fcc680-09d6-11eb-8dba-67c15ace10c3.gif)
