### ISSUE TITLE
I can't save my changes  in class mode ?

### ISSUE THREAD

**Issue by bobiscool** [Col-E/Recaf#297]
I changed my code in class mode,  use cmd+s to save the files , then export it to another.jar

But when I open it, I see noting changed.

**Comment by Col-E** [comment]
Class mode is the title, but the option values are:

1. Decompile
2. Table
3. Hex

Which one were you using? And when you saved, did you see the green flash as described in the docs? https://www.coley.software/Recaf/doc-edit-modes.html

**Comment by bobiscool** [comment]
I edited my code in decompile mode as follow
![image](https://user-images.githubusercontent.com/9073321/96532910-6f486100-12bf-11eb-942a-f8c50d0bf018.png)
I removed the code in the red red box， got no error
![image](https://user-images.githubusercontent.com/9073321/96533092-d0703480-12bf-11eb-8213-872b63430e65.png)
but did not see the green flash as you said

Is there something wrong with me?

**Comment by Col-E** [comment]
Check the system info page to see if recompiling is supported: https://www.coley.software/Recaf/doc-setup-8.html

If it is, can you check the logging output? Perhaps there is an error message in the log file that isn't being shown. The log file is can be found here: https://www.coley.software/Recaf/doc-intro-config.html

**Comment by Col-E** [comment]
I'll need more information to properly diagnose the issue here.

**Comment by bobiscool** [comment]
My fault, env error, thanks for your patient！
