### ISSUE TITLE
Suggestion : raw hex view in assembler

### ISSUE THREAD

**Issue by gotroc** [Col-E/Recaf#299]
Not sure how doable this is, but it would be nice to have a column to the left of the assembler window with the raw hexadecimal corresponding to each line.

**Comment by Col-E** [comment]
I have a plan for this idea, but not in the assembler so you can see live changes. That is not really do-able at the moment.

https://github.com/Col-E/Recaf/issues/244 - My plan is to have a read-only window that is _similar_ to the assembler.

It will be a while before I can get around to fully implementing this. More info in the linked issue.
