### ISSUE TITLE
Allow for Decompiler CLI Options

### ISSUE THREAD

**Issue by alexyao2015** [Col-E/Recaf#303]
## Allow for Decompiler CLI Options

Fernflower has many configurable options available. Would it be possible to add command line options to the decompiler when viewing a class?

**Comment by Col-E** [comment]
Yes, I haven't drafted out how I want this to look in the config UI yet.
Because it should have options for all the supported decompilers, but also not totally clutter the config menu.

**Comment by alexyao2015** [comment]
There could simply be 3 text boxes, one for each decompiler, or 1 text box that is just appended to the chosen decompiler.

**Comment by Col-E** [comment]
The problem with that approach is its rather unintuitive for newer users. I'd like something that's accessible to people less familiar with the tech behind the scenes. For example, the config value for `decompile.showsynthetics` applies to all decompilers. Recaf passes the appropriate setting to each decompiler. 

For equivalent values I would like to do this approach, and for more specific ones a way to tidily  show it in the same place without cluttering the config window too much.

**Comment by Col-E** [comment]
Supported in 4.X

![image](https://github.com/Col-E/Recaf/assets/21371686/b1bdf2dc-655a-4caa-a4f8-496a7fac0430)
