### ISSUE TITLE
JDK Not found

### ISSUE THREAD

**Issue by Moon-developer** [Col-E/Recaf#307]
Having a weird issue when trying to edit with the decompile option picked in config.

the file outputs:
```
// =============================================== //
// Recompile disabled. Please run Recaf with a JDK //
// =============================================== //

// Decompiled with: CFR 0.150
...
```
Any idea what this issue is? sorry if it's a bit of a newbie questions. I did install the `jdk-8u271-windows-x64.exe` before running `java -jar recaf-2.12.0-J8-jar-with-dependencies.jar`

**Comment by Col-E** [comment]
Check your system path and see what the java directory is. 

The JDK 8 looks like this
```
jdk/
 - bin/
 - jre/bin
```
and I believe it may point to the second, which does not give access to the full JDK toolset.

**Comment by Moon-developer** [comment]
I thought about this as well so I did check my environment variables. there's only one and it's pointing to the JDK 8 bin. not the `jre/bin`.
I made sure to check both user and system environments. Hence why I brought it up as a strange behavior to confirm.

To double check environment I also check it via command line to make sure the current shell has the same setup.

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/blob/0d65b01b7d3c6270a8b6e96051a0dc5dcc6d49eb/src/main/java/me/coley/recaf/ui/controls/text/JavaEditorPane.java#L196

That message is shown when the runtime fails to provide access to the compiler as indicated by this line here. 

Oh I forgot to mention, you can check what version Recaf is using in the [help > info] option: https://www.coley.software/Recaf/doc-setup-8.html

**Comment by Moon-developer** [comment]
Thank you for the comment on stackexchange.  Java 11 worked everything else was just not working at all. Posted the question there before here since I didn't know if it was a bug or a general configuration issue.

**Comment by Col-E** [comment]
👍 Java 11 may be confusing for some but man does it make life easier here
