### ISSUE TITLE
No such field exception: ucp

### ISSUE THREAD

**Issue by BlueGoliath** [Col-E/Recaf#312]
**Describe the bug**

Application fails to get field "ucp".

**To Reproduce**

Attempt to launch via java -jar recaf-2.16.5-J8-jar-with-dependencies.jar

Output:

08:43:39.971 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
08:43:39.973 [main] INFO :  - No local cache, downloading dependencies...
08:43:42.559 [main] INFO :  - Loading dependencies...
08:43:42.562 [main] ERROR: Failed to add dependencies to classpath!
java.lang.NoSuchFieldException: ucp
	at java.base/java.lang.Class.getDeclaredField(Class.java:2553)
	at me.coley.recaf.util.self.SelfDependencyPatcher.loadFromCache(SelfDependencyPatcher.java:135)
	at me.coley.recaf.util.self.SelfDependencyPatcher.patch(SelfDependencyPatcher.java:100)
	at me.coley.recaf.Recaf.init(Recaf.java:82)
	at me.coley.recaf.Recaf.main(Recaf.java:50)

Edit: this seems to be due to a change in JDK 17 builds, which I use. Java 11 works fine.

**Comment by BlueGoliath** [comment]
Actually the variable has been removed entirely in JDK 16 and above. Here is Java 11's source code:

https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/jdk/internal/loader/ClassLoaders.java#L161

and here is Java 16/17:

https://github.com/openjdk/jdk/blob/b575dd80b6e86821fcf3e065e31c6bddb85db6c4/src/java.base/share/classes/jdk/internal/loader/ClassLoaders.java#L165

**Comment by Col-E** [comment]
Looks like its still in the parent type, tested locally and work when getting from the super-type.

Pushing a fix, will see a release shortly 👍

**Comment by xxDark** [comment]
Consider using `VMUtil` for that.
