### ISSUE TITLE
Unhackable jar

### ISSUE THREAD

**Issue by glesialo** [Col-E/Recaf#314]
My comment in your reddit /r/java thread:

https://www.reddit.com/r/java/comments/kjz70b/recaf_java_bytecode_reversing_tool_ive_been/gh0js9n?utm_source=share&utm_medium=web2x&context=3

Please find a zip file, with the jar file in it, attached.

Thanks in advance,
Manolo.

**Comment by glesialo** [comment]
Not so Unhackable after all.

Thank you!

**Comment by Col-E** [comment]
😁
