### ISSUE TITLE
Ignore Case Option

### ISSUE THREAD

**Issue by ghost** [Col-E/Recaf#321]
Reason: Avoid the Omission while searching strings.
`if possible make  the modification of Source file name of classes and Annotion of methods/fileds possible just like Jbytemod`

**Comment by Col-E** [comment]
I marked this as done apparently a while ago... Anyways this is a feature in 3X in the workspace filter, and in the code _"Find"_ search bar.

https://user-images.githubusercontent.com/21371686/144746046-d965cf36-9c1f-4d83-8507-488fcc6626e6.mp4
