### ISSUE TITLE
Bug with packages & classes renaming

### ISSUE THREAD

**Issue by FlowArg** [Col-E/Recaf#329]
**Describe the bug**

> This bug hide a recently renamed package and his classes.

**To Reproduce**

1) Open the **2.16.7** Recaf version.
2) Load a jar. For my test, I took the tools.jar of my jdk 8u271.
3) Open some classes (for example `com.sun.tools.hat.Main`, `com.sun.tools.hat.internal.server.QueryListener`).
4) Next, rename `com.sun.tools.hat.internal.server.QueryListener` to `com.sun.tools.hat.internal.problem.QueryListener` (a package that not exist in the original jar)
5) Check if the package appears, yes !
6) Then, Rename QueryListener (QueryListenerWAW) for example.
7) And the package is now invisible (check my video & screenshot) !

**Screenshot**
![image](https://user-images.githubusercontent.com/52298108/103437174-79260300-4c24-11eb-8b51-bba593e3c563.png)

**Video**
I've made a [video](https://youtu.be/HDO6ZRDYgYI) when I discovered the bug with the 2.12 version of Recaf :

**Consequences**
I must export the jar and reimport it in Recaf.

**Comment by Col-E** [comment]
Fixed in `2.16.8`
