### ISSUE TITLE
Running recaf with a JDK

### ISSUE THREAD

**Issue by Floppinqq** [Col-E/Recaf#330]
in recaf, if you dont run with a jdk will appear a message that it can't recompile jars.
i runned recaf with a jdk and i literally can edit everything, but when i press Ctrl+E or Export Program, it saves but when i open again the changes dont get saved
for i.e:
changing imports from a class
changing overwrites
etc...

what i do:

Open a jar in recaf(with jdk)
change a import
export program

Then i check if the changes that i made saved
open the "changed" jar in recaf again
go to where i changed the import
and the import continue normal

and in cmd, the error is:
ERROR: Failed recompiling code for 'me/floppinqq/test/test' - Reason: 'Failed compile due to compilation errors'

**Comment by Col-E** [comment]
Ok, so to clarify you did re-run it with a JDK and were able to use the recompile feature.

When you pressed `Control + S` did the editor tab flash green to indicate that you successfully saved?

And in the logfile/terminal output, does it tell you how many modified classes were found when exporting?

**Comment by Floppinqq** [comment]
yes, the editor tab do a green flash, but later appears some error but i ignore
the terminal appear the message:
ERROR: Failed recompiling code for 'me/floppinqq/test/test' - Reason: 'Failed compile due to compilation errors'

**Comment by Col-E** [comment]
Can you provide me with the test class? If there were compile errors then it should have flashed _red_ not _green_.

Also, can you be more descriptive than _"change an import"_? Imports are a source-code level concept and do not actually exist in the actual class. They just point the compiler to the correct class.

**Comment by Floppinqq** [comment]
the me/floppinqq/test/test is a example

when i said change an import i say remove a import from the class

**Comment by Col-E** [comment]
Oh well that's not gonna work lmao

**Comment by Floppinqq** [comment]
but there is any way to fix that?

**Comment by Col-E** [comment]
No, you're removing something the compiler needs to work. You can make a different change though. 
```java
class Example {
    public static void main(String[] args) {
         System.out.println("hello");
    }
}
```
Compile with `javac` open it in Recaf, then edit the string it prints.

Save `Control + S` then export and run it.

**Comment by Floppinqq** [comment]
compilation errors

**Comment by Col-E** [comment]
It works if you make valid edits. If you can provide a valid edit that does not work, I'll reopen the issue.

Here is an example with the code I gave above: ![AyoL32gWOY](https://user-images.githubusercontent.com/21371686/103443336-47189f00-4c2c-11eb-80eb-cce6b4c7dfb5.gif)
