### ISSUE TITLE
Suggestion: Add ability to change decompiler settings.

### ISSUE THREAD

**Issue by ElektroKill** [Col-E/Recaf#332]
## Decompiler Options

Fernflower by default does not decompile generics but this can be changed by specifying options. I suggest an option in the config of Recaf to allow changing these parameters of decompilers. It would really come in handy!

Thanks in advance!

**Comment by Col-E** [comment]
Huh, woulda thought that would be a default setting.

Anyways, the major hold-up for why I haven't done so yet in 2.X is because I'm not so sure how to best represent all the values in the UI without looking super cluttered.

**Comment by Col-E** [comment]
Full decompiler configuration is supported in 4x

![image](https://github.com/Col-E/Recaf/assets/21371686/9ece93d2-6236-416c-ba0c-e2e067a8872b)

![image](https://github.com/Col-E/Recaf/assets/21371686/17700160-ad19-456a-9973-ccf65be2afad)

Each decompiler handles config slightly differently, but everything is accessible. Will be adding FernFlower _(via VineFlower fork)_ later.
