### ISSUE TITLE
No context menu in decompiled java view for methods which return or accept unknown types

### ISSUE THREAD

**Issue by tth05** [Col-E/Recaf#333]
**Describe the bug**

In the decompiled view for java files the context menu when right clicking a method name won't show up. This boils down to `JavaParserUtil#getDescriptor` returning an incorrect description for the method because it can't find the types. For example `()Lnet/minecraft/util/DamageSource` becomes `()LDamageSource`.
It still works in the table view, but I'd prefer to stay in the file view instead of having to switch between the two constantly.

Also you can't add minecraft/forge as a library because minecraft itself is obfuscated and forge only transform all class names at runtime, which makes it hard to get a library jar with the correct class names.

**To Reproduce**

1. Open sample 'Any minecraft mod for example Refined Storage'
2. Navigate to 'com.raoulvdberge.refinedstorage.util.StackUtils'
3. Right click any method that accepts for example an NBTTagCompound

**Comment by Col-E** [comment]
This could be resolved by phantom class generation, or by some improvement to the JavaParser setup. I wish there was some way to give it more hints on what types are...

I'll take a look at Refined Storage and see if the phantom resource is not generating all the necessary classes for some reason.

For now a decent workaround is: 

1. Open the class with decompile mode and drag the tab to a new window _(drag and drop to an empty space on your sreen)_
2. Open the class again, but in table mode. You should now have two open tabs representing the same class. You can use the decompile one for reference and table mode for usage.

**Comment by tth05** [comment]
I've tried again with the official Refined Storage version now and seems like it works there?

You can try it with pneumaticcraft instead `https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/download/2978408`

**Comment by tth05** [comment]
Not sure if it has anything todo with these errors, which show up when loading pneumaticcraft.

https://pastie.io/ycafqv.java

**Comment by Col-E** [comment]
Yup, that's pretty relevant.

**Comment by Col-E** [comment]
Wheen looking at `pneumaticcraft` the phantom process gets stuck....

![image](https://user-images.githubusercontent.com/21371686/103745860-32daf600-4fce-11eb-8126-98b3382ddda6.png)

**Comment by tth05** [comment]
You will probably look back at it in 2 years and think "Ah yeah, that's why I put that there".

**Comment by Col-E** [comment]
It did have an effect :(

Phantoms generated but the hierarchy is no longer linked. Lets see if there's another way to boost it.

**Comment by Col-E** [comment]
Been working on a JPhantom pr which should address the failures. Will have to look into performance another day.

**Comment by Col-E** [comment]
I think this has been fixed ;)

Tested on some mods:
```
INFO : Loaded workspace from: refinedstorage-1.9.11.jar
DEBUG: Begin generating phantom classes, given 740 input classes
DEBUG: Wrote classes to temp file, starting phantom analysis...
DEBUG: Phantom analysis complete, cleaning temp file
DEBUG: Generated 607 phantom classes in 1200 ms
```
And:
```
INFO : Loaded workspace from: pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar
DEBUG: Begin generating phantom classes, given 1584 input classes
DEBUG: Wrote classes to temp file, starting phantom analysis...
DEBUG: Phantom analysis complete, cleaning temp file
DEBUG: Generated 1322 phantom classes in 2846 ms
```

Console will emit some extraction failure warnings, but a recovery system is in place so most of the classes still get properly generated
