### ISSUE TITLE
Automatically rename class names that contain invisible characters

### ISSUE THREAD

**Issue by nevinhappy** [Col-E/Recaf#336]
## Feature_Name
Automatically rename class names that contain invisible characters.
Description of the feature
In some scenarios, the class files are confused to contain invisible characters. In the process of decompiling, it is hoped that these contents can be automatically recognized and renamed automatically, such as the sequence of a-z, etc., no matter what,  it's much better than invisible characters.
There are three fields that need to be renamed :
1. Class name
2. Class member name
3. Class function name
This is a example of a decompiled class:
![example](https://user-images.githubusercontent.com/1475079/103838639-8af62300-50c8-11eb-84f9-71119bc5206c.png)

**Comment by Col-E** [comment]
See _"Illegal renamer"_ https://www.coley.software/Recaf-documentation/adv-plugins.html

**Comment by nevinhappy** [comment]
Thank you for your reply! It's just what I want. It's great !!!
