### ISSUE TITLE
Feat - add project export

### ISSUE THREAD

**Issue by snuckdev** [Col-E/Recaf#354]
## Export whole project to a .zip file

Since Recaf supports so many decompilers, I would love to add a feature that exports all decompiled classes into a .zip like Procyon and JD-GUI do.

**Comment by Col-E** [comment]
https://www.coley.software/Recaf-documentation/adv-plugins.html

Check the decompile all plugin, itll dump all the decompiled code in one go.

**Comment by snuckdev** [comment]
Thx
