### ISSUE TITLE
Permit reflect library causes OpenJ9 segfault

### ISSUE THREAD

**Issue by Thihup** [Col-E/Recaf#355]
Using this library causes the OpenJ9 to not work. Would be possible to remove the use of it?

https://github.com/eclipse/openj9/issues/12012#issuecomment-783591676

**Comment by xxDark** [comment]
I opened a PR at Permit's repository.
I have a bare hope of thhat it will be ever merged, so I guess yes, I'll just remove the library itself.

**Comment by Col-E** [comment]
Renaming for clarity, we'll fix it one way or another.

**Comment by Col-E** [comment]
Fixed in `2.18.0`
