### ISSUE TITLE
decompile apk .dex .aar

### ISSUE THREAD

**Issue by studiobuilder-tech** [Col-E/Recaf#363]
Apk decompile

**Comment by codingsocks** [comment]
This issue is easier said than done without some hacky implementation mentioned by Col-E a while ago, but APK support is coming in Recaf 3.X IIRC.

**Comment by codingsocks** [comment]
ah, yeah it is coming in 3.X, image:

![image](https://user-images.githubusercontent.com/6201484/111876569-4ced6900-896d-11eb-9bc7-6c987685f69e.png)

**Comment by studiobuilder-tech** [comment]
Thanks

**Comment by Col-E** [comment]
It'll be a while until 3.X comes out, but in the meantime you can use dex2jar as well.

**Comment by studiobuilder-tech** [comment]
Ok

**Comment by x4e** [comment]
> Apk decompile

In the future try making more descriptive issues, you are more likely to receive help
