### ISSUE TITLE
Adding regex support into find/search dialog

### ISSUE THREAD

**Issue by Dansoftowner** [Col-E/Recaf#367]
## Regex support in find dialog

Hi!

It would be nice to have an option for searching text by regular expressions in this "find-box":
![image](https://user-images.githubusercontent.com/49782833/113329606-0fe68680-931e-11eb-860c-cbaae1eca988.png)

Like in Intellij:
![image](https://user-images.githubusercontent.com/49782833/113330000-90a58280-931e-11eb-8916-4013c77a241e.png)

Best regards

**Comment by Col-E** [comment]
Ha, its funny you suggest this: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/ui/controls/SearchBar.java#L50

**Comment by Col-E** [comment]
Tossed this together in the 3X branch :)

https://user-images.githubusercontent.com/21371686/144553847-0b94f893-4d96-45d7-a2cc-9d0158581ca7.mp4

Gonna clean it up and it should be pushed up soon.
