### ISSUE TITLE
Missing fonts on Linux

### ISSUE THREAD

**Issue by ItzRiotz** [Col-E/Recaf#369]
Description - I am using Arch Linux (with the XFCE4 environment, too lazy to assemble my own) and fonts seem to be missing.
Instead of letters I just have little empty boxes. Now, it may be a problem that you're using a Windows font, or it may be my problem that I have a missing font (which I most likely the problem).

1. Install Arch Linux with the XFCE4 desktop environment.
2. Install Java (I am using Java 8)
3. Download latest Recaf (as of the time of writing is 2.18.3)
4. The missing font box appears (can't even comprehend what it says)

Screenshot - https://imgur.com/fqWPK7t.png

**Comment by ItzRiotz** [comment]
Fixed by installing a big package of fonts
`yay -S nerd-fonts-complete`

**Comment by Col-E** [comment]
Sounds like a good point to add to the docs for future arch users to refer to

**Comment by codingsocks** [comment]
I thought Recaf always fell back onto a system default font if the one it wanted wasn't available

**Comment by ItzRiotz** [comment]
No idea, just that Arch is a very bare bones installation and it doesn't have more than like 10 normal and 15 monospace fonts..
Might recommend installing more fonts.

**Comment by codingsocks** [comment]
I *would* test and fix the root issue but unfortunately my Arch Linux installation that I had on my laptop committed self-sudoku and I don't want to reinstall it atm. Maybe at some point I will look into it though.

**Comment by ItzRiotz** [comment]
also latest jar without dependencies has no main manifest @Col-E

**Comment by ItzRiotz** [comment]
anyways continuing on testing this, I painfully made a new VM with Arch Linux, had to fiddle around with installing JavaFX, then GTK, and after all that I get a NullPointer for fonts (couldn't expect less) although I do have a few fonts (this exception happened in com.sun.javafx.font.LogicalFont line 181).
Here's a list of all of the fonts that I have installed **by default**: https://pastebin.com/ceMbRES0

**Comment by Col-E** [comment]
> also latest jar without dependencies has no main manifest @Col-E

It never does. Its not supposed to be runnable. Only the larger jar with dependencies is.
