### ISSUE TITLE
Exception: Recaf class recompilation done with JRE instead of JDK

### ISSUE THREAD

**Issue by AxDSan** [Col-E/Recaf#38]
I get that error whenever I try to recompile a class... what do I need to do to fix this issue?

My environment variable path has the jdk properly setup... I don't know what's wrong.

OS: Windows 10, if that helps in something.

**Comment by Col-E** [comment]
I've done the same but double clicking it seems to still run it with the JRE _(Probably some funky registry keys that need to be adjusted)_. Try running it via console that's how I get it to work. `java -jar recaf.jar`

**Comment by AxDSan** [comment]
Yeah, something is def going on, I had to run it directly from the JDK path itself but it’s a lame fix for now, if this gets solved I’ll reopen the issue and report back

**Comment by Col-E** [comment]
I mean if anyone can figure out a clean solution I would love to know.
