### ISSUE TITLE
Ability to edit strings in annotations

### ISSUE THREAD

**Issue by ghost** [Col-E/Recaf#382]
Just like JbyteEdit
(But it's Bugly)

**Comment by BackupAccou** [comment]
public final class mark{
    @iiiIIiIIIII(sdsdsd="key", \0="key")
    public static String key;
   }

**Comment by Col-E** [comment]
This has been incorporated into the new 3X assembler, I do not plan on back-porting it to 2X due to the significant parser differences. So when 3X drops this will be supported. Closing as done, availability will be in the first 3X official release.
