### ISSUE TITLE
Ability to open directory

### ISSUE THREAD

**Issue by illuminator3** [Col-E/Recaf#383]
## Ability to open directory

There should be a feature that allows you to open a normal directory which contains (nested) .class files

**Comment by Col-E** [comment]
There is logic to support it, just the UI doesn't tie in to it yet due to some ugly edge case handling that'd have to be made. Shouldn't be that hard to add though.

**Comment by Col-E** [comment]
I'll add this in the next release. Drag dropping a directory works, but for the `File > Open` menu, that's a _file_ picker and won't take directories. But most of the time people just drag drop anyways so its not too bad of an issue `¯\_(ツ)_/¯`

**Comment by illuminator3** [comment]
Maybe add a `File -> Open Directory` option which uses a `DirectoryChooser`

**Comment by Col-E** [comment]
Could do that, but then it'd make sense to also supply a `File -> Save Directory`. Ideally there should be some smart handling to be able to do both from one menu option to reduce clutter/confusion.

**Comment by Col-E** [comment]
Supported in 4.X
