### ISSUE TITLE
Decompilation failed

### ISSUE THREAD

**Issue by 529178241** [Col-E/Recaf#387]
/*
     * Exception decompiling
     */
    public static IMDDBQueryFacade getInstance() {
        /*
         * This method has failed to decompile.  When submitting a bug report, please provide this stack trace, and (if you hold appropriate legal rights) the relevant class file.
         * 
         * org.benf.cfr.reader.util.ConfusedCFRException: Tried to end blocks [4[SIMPLE_IF_TAKEN]], but top level block is 1[MONITOR]
         *     at org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.processEndingBlocks(Op04StructuredStatement.java:435)
         *     at org.benf.cfr.reader.bytecode.analysis.opgraph.Op04StructuredStatement.buildNestedBlocks(Op04StructuredStatement.java:484)
         *     at org.benf.cfr.reader.bytecode.analysis.opgraph.Op03SimpleStatement.createInitialStructuredBlock(Op03SimpleStatement.java:736)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:845)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:278)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:198)
         *     at org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:94)
         *     at org.benf.cfr.reader.entities.Method.analyse(Method.java:531)
         *     at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:1042)
         *     at org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:929)
         *     at org.benf.cfr.reader.Driver.doClass(Driver.java:84)
         *     at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:75)
         *     at me.coley.recaf.decompile.cfr.CfrDecompiler.decompile(CfrDecompiler.java:65)
         *     at me.coley.recaf.ui.controls.view.ClassViewport.lambda$updateView$1(ClassViewport.java:112)
         *     at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
         *     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
         *     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
         *     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
         *     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
         *     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
         */
        throw new IllegalStateException("Decompilation failed");
    }[](url)

**Comment by 529178241** [comment]
![MDDBBaseQueryFacade class](https://user-images.githubusercontent.com/13533237/119313122-c115f700-bca5-11eb-97cb-566e7a43797e.jpg)

**Comment by Col-E** [comment]
Have you tried switching to one of the other two decompilers? If this class is heavily obfuscated, it may just be too confusing for them.

**Comment by Col-E** [comment]
Closing as this is an upstream decompilation issues, but discussion can still continue.

**Comment by Col-E** [comment]
Actually this is a problem on my end it seems. I'll open a ticket with more details.
