### ISSUE TITLE
Interface breaks on glyph in json

### ISSUE THREAD

**Issue by nothub** [Col-E/Recaf#390]
**Describe the bug**

> Recaf GUI breaks when attempting to display a text file with glyph in json.

**To Reproduce**

1. Create jar file.
2. Add a text file with contents:
```
[
  {
    "": "🌉"
  }
]

```
3. Load in recaf and open text file.

**Exception**

If applicable, add the exception/stacktrace.
```
00:44:14.798 [ForkJoinPool-1-worker-5] DEBUG: Generated 0 phantom classes in 49 ms
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 32
	at com.sun.prism.impl.GlyphCache.getCachedGlyph(GlyphCache.java:332)
	at com.sun.prism.impl.GlyphCache.render(GlyphCache.java:148)
	at com.sun.prism.impl.ps.BaseShaderGraphics.drawString(BaseShaderGraphics.java:2101)
	at com.sun.javafx.sg.prism.NGText.renderText(NGText.java:312)
...
```
https://pastebin.com/f7DKDMbF

**Screenshots**

![screenshot](https://i.imgur.com/m7uQbR9.png)

Tested on 
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Ubuntu 20.04

**Comment by Col-E** [comment]
Looks like https://bugs.openjdk.java.net/browse/JDK-8189092

Can you open the Recaf directory _(via Help -> System information)_ and check what version of JavaFX is in the dependencies directory?

**Comment by nothub** [comment]
```
**System**
| Name | Architecture |
| -------- | -------- |
| `Linux` | `amd64` |

**Java**
| Version | VM name | VM vendor | Home | Supports compiler | Supports attach |
| -------- | -------- | -------- | -------- | -------- | -------- |
| `16.0.1` | `OpenJDK 64-Bit Server VM` | `AdoptOpenJDK` | `/home/hub/.sdkman/candidates/java/16.0.1.hs-adpt` | `true` | `true` |

**JavaFX**
| Version |
| -------- |
| `11.0.2` |
```

**Comment by Col-E** [comment]
> 11.0.2

The issue was fixed in the 14.0, can you try deleting the jars in the directory and launching Recaf with the latest version of Java?

**Comment by nothub** [comment]
recaf updated javafx to 15.0.1 after deleting the old dependencies, everything works as expected now, thanks :+1:

**Comment by Col-E** [comment]
I've removed the unnecessary version check, so in the next release it will pull only newer JFX versions. But existing cached jars will need to be manually cleared by the user.
