### ISSUE TITLE
Wide instruction support

### ISSUE THREAD

**Issue by Scott-Young-6746** [Col-E/Recaf#396]
## Wide instruction support

When editing methods using the "Edit with Assembler" option, both the `goto_w` and `wide` bytecode mnemonics are listed as unknown bytecodes. 

This would be a useful feature for generating tests using these bytecodes for JIT compiler developers working on VMs

**Comment by Col-E** [comment]
ASM abstracts away the wide instructions into more general ones, so its not something I can really support without entirely re-writing the assembler. It should map to the appropriate version when it writes the bytecode back to the class.

**Comment by Col-E** [comment]
To elaborate, if you were to take a method that was long enough _[but not too long](https://stackoverflow.com/a/61282148)_ ASM would automatically use `goto_w` to jump to the later labels. But anything before would use normal `goto`. It won't emit the wide variant unless its necessary.

**Comment by Scott-Young-6746** [comment]
> 
> 
> To elaborate, if you were to take a method that was long enough _[but not too long](https://stackoverflow.com/a/61282148)_ ASM should automatically use `goto_w` to jump to the later labels AFAIK. But anything before would use normal `goto`. It won't emit the wide variant unless its necessary.
> 
> Though [some actual compilers would just use the wide one](https://stackoverflow.com/a/61299130).
> 
> I'd need to make a test case or so to validate things work how I think they do.

Ah, I miss-read the JVM spec, because I had thought that `goto_w` wouldn't get generated by a compiler due to the method size being limited to 2 byte representation, and `goto` using 2 byte offsets, but method size is unsigned so I can still get a `goto_w` out of Recaf with a lot of `{iload_0,istore_0}` pairs.

Thanks for the assistance!
