### ISSUE TITLE
ZipException: duplicate entry: r/p/w/q/z.class/

### ISSUE THREAD

**Issue by yaskylan** [Col-E/Recaf#397]
我正在对一款混有 "paramorphism" 的Minecraft客户端进行一些见不得人的事情 然鹅我的Recaf它不可以加载 "paramorphism" 混淆过后的class文件 最主要的是 我不能将文件排除在外 太糟糕了!

**Comment by Col-E** [comment]
I can't do anything without a sample jar to test with.

**Comment by yaskylan** [comment]
> I can't do anything without a sample jar to test with.

https://mega.nz/file/HNoQwD7Z#_-g2WyzIsshaJbL9upi_EAql8_usd9w2xiOLEoap7o8

**Comment by yaskylan** [comment]
> > I can't do anything without a sample jar to test with.
> 
> https://mega.nz/file/HNoQwD7Z#_-g2WyzIsshaJbL9upi_EAql8_usd9w2xiOLEoap7o8

一个典型的混有 "paramorphism" 的Minecraft1.12.2

**Comment by xcfrg** [comment]
Can no longer reproduce original issue on at least 72d9a5b9d08910554d4fc71a0f9a0adf7fe65e94
Not all files in the sample appear to get parsed though:
![Screenshot_20220422_092842](https://user-images.githubusercontent.com/30675315/164724221-243695af-4334-4b9d-a27a-cb7025706c77.png)

**Comment by Col-E** [comment]
Per prior comment, closing
