### ISSUE TITLE
Recompile Always Fails even when running with JDK

### ISSUE THREAD

**Issue by Creator256** [Col-E/Recaf#40]
Every time I try and recompile code after de-compiling, an error is given that says the following:

[ERRR:2/3/18 4:30 PM] Could not recompile, user attempted recompile from JRE process (not JDK).
[ERRR:2/3/18 4:30 PM] You cannot use this feature while running Recaf under the JRE.
 Recompilation relies on Recaf being executed in a JDK.
Please re-run with a JDK.

I am currently running it with a JDK. The trace I am given is the following: 

Trace: 
me.coley.recaf.ui.component.panel.DecompilePanel.recompile(DecompilePanel.java:109)
me.coley.recaf.ui.component.panel.DecompilePanel.lambda$new$0(DecompilePanel.java:68)
me.coley.recaf.ui.component.action.ActionMenuItem$1.actionPerformed(ActionMenuItem.java:21)
javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
javax.swing.DefaultButtonModel.setPressed(Unknown Source)
javax.swing.AbstractButton.doClick(Unknown Source)
javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
java.awt.Component.processMouseEvent(Unknown Source)
javax.swing.JComponent.processMouseEvent(Unknown Source)
java.awt.Component.processEvent(Unknown Source)
java.awt.Container.processEvent(Unknown Source)
java.awt.Component.dispatchEventImpl(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
java.awt.Container.dispatchEventImpl(Unknown Source)
java.awt.Window.dispatchEventImpl(Unknown Source)
java.awt.Component.dispatchEvent(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.awt.EventQueue$4.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)

Any idea as to why this is happening?

**Comment by Col-E** [comment]
Have you explicitly invoked recaf using a `javaw/java` executable from a JDK install?

**Comment by Creator256** [comment]
Yes I have. Installed the newest version of JDK as well and still no luck.

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/35772440-c3d51160-090c-11e8-9bc5-14c1bf559c03.png)
It should be called like this. Setting your `JAVA_HOME` and `PATH` doesn't seem to work on windows.

**Comment by Creator256** [comment]
Ah, running as admin was what I needed to do. Sorry for the trouble.

**Comment by Col-E** [comment]
NP, I should probably be more specific about this on the docs.
