### ISSUE TITLE
I want to develop a new feature about security detection

### ISSUE THREAD

**Issue by pppppkun** [Col-E/Recaf#404]
## Security Detection

I want to add some new features about Security Detection which focus on Stain analysis and SQL injection vulnerability detection but I'm a freshman about open-source community and poor in English. Thus, If I want to add new features above, which partial code should I read, or are there any manuals or rules I need to understand first?

Thanks

**Comment by Col-E** [comment]
I think you would want to leverage something that is already more focused on vulnerability detection like https://github.com/gmu-swe/rivulet

Especially in the context of open-source software where there are existing test cases to use RIVULET on.
