### ISSUE TITLE
automatic patch generation, headless binary patching, scripting, automation

### ISSUE THREAD

**Issue by milahu** [Col-E/Recaf#405]
## automatic patch generation

i want to automate this workflow:

1. unpack jar
2. locate function
3. patch assembler
4. recompile class
5. produce binary patch (bsdiff) of the class file

the goal is to auto-generate the binary patches from different versions of the jar file,
based on context-detection (fuzzy matching), similar to text diff-patch

or have we invented this wheel already?

**Comment by Col-E** [comment]
Recaf already stores class/file history, so this shouldn't be too hard to incorporate with [jbsdiff](https://github.com/malensek/jbsdiff/blob/51b6981d97b4cf386069481707394f37c537b1d5/src/main/java/io/sigpipe/jbsdiff/Diff.java#L66)

For UI usage, I have two ideas:

1. Create patches for all files in the primary resource, export to a zip of patches _(Zip entry file names match original resource names)_
    - Then you can do `File > Load patches` and select the zip
2. Create single patches for single items, and add a patch menu to class/file items

I imagine the first way would be preferable in most cases. Nothing stopping both from being done though.

**Comment by milahu** [comment]
> this shouldn't be too hard to incorporate with [jbsdiff](https://github.com/malensek/jbsdiff/blob/51b6981d97b4cf386069481707394f37c537b1d5/src/main/java/io/sigpipe/jbsdiff/Diff.java#L66)

im afraid that the bytecode is too unstable for patching,
for example a change in optimization-flags could make the binary-patch useless

i was thinking of something like [codemods](https://github.com/rajasegar/awesome-codemods), to transform the syntax-tree with imperative javascript.
in this case, the syntax-tree would represent either the decompiled java code, or the java assembler code.
this way, we could implement a highly custom fuzzy search-and-replace ...

**Comment by Col-E** [comment]
> i was thinking of something like codemods, to transform the syntax-tree
> in this case, the syntax-tree would represent either the decompiled java code, or the java assembler code.

The main problem on stability is that with different versions of a program the constant pool symbols can be defined at different indices. This is fine up until a method body has the same instructions as before, but now all the CP indices are different. But since ASM abstracts this away, diffing based off assembler output would be completely stable. 

The ideas I have would be tweaked as such:

1. The patches would no longer be linked to their file name, but instead be associated with some lookup that links each patch with a `class name + member name / desc`.
    - Not sure about how this could be complaint with bsdiff _(Not familiar with the format)_ but it could easily be done with a custom patch format. 
2. Menu would not be on classes, it would be on fields/methods

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/commit/817aa24da25565a610479cdcda038a3210bd602b - A more proper patch-like system has been added to the 4.X API - UI pending

**Comment by milahu** [comment]
currently im using this bash script to patch a jar file

based on the [old scripting API](https://www.coley.software/Recaf-documentation/adv-scripting.html)
(i dont see how to use the [new scripting API](https://recaf.gitbook.io/developer-documentation/plugins-and-scripts/plugin-vs-script))

<details>
<summary>
jdownloader-patch-core.sh
</summary>

```sh
#!/usr/bin/env bash

# patch jdownloader
# dont require MyJDownloader login for headless mode

set -eux

recaf=$(NIXPKGS_ALLOW_UNFREE=1 nix-build --no-out-link '<nixpkgs>' -A nur.repos.milahu.recaf-bin)
export PATH="$recaf/bin:$PATH"

now=$(date --utc +%Y%m%dT%H%M%SZ)

jdownloader_path="$HOME/.config/jdownloader"

jar_path="$jdownloader_path/Core.jar"
bak_jar_path="$jar_path.bak.$now"

class="org/jdownloader/api/myjdownloader/MyJDownloaderController"
method="isAlwaysConnectRequired()Z"

# note: no whitespace in paths
temp_base=/run/user/$UID/recaf-jdownloader-MyJDownloaderController-isAlwaysConnectRequired
asm_path=$temp_base.asm
recaf_script_path=$temp_base.recaf
temp_jar_path=$temp_base.patched.jar

# disassemble the method to patch
cat >$recaf_script_path <<EOF
disassemble --destination=$asm_path $class $method
EOF
recaf --input="$jar_path" --script=$recaf_script_path

# check if method is patched
if ! grep -q INVOKESTATIC $asm_path; then
  echo "patch was already applied"
  # cleanup
  # TODO trap exit
  rm $recaf_script_path
  rm $asm_path
  exit
fi

# patch the assembly code
# -INVOKESTATIC org/appwork/utils/Application.isHeadless()Z
# -IRETURN
# +EXPR return false;
sed -i '/INVOKESTATIC/d; s/IRETURN/EXPR return false;/' $asm_path

# assemble the patched method
cat >$recaf_script_path <<EOF
assemble $class $method $asm_path
export $temp_jar_path
EOF
recaf --input="$jar_path" --script=$recaf_script_path

echo "replacing $jar_path"
mv "$jar_path" "$bak_jar_path"
mv $temp_jar_path "$jar_path"

# cleanup
# TODO trap exit
rm $recaf_script_path
rm $asm_path
```

</details>
