### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by storm772** [Col-E/Recaf#412]
**Describe the bug**

*** These settings, notifications background are not shown.***
![image](https://user-images.githubusercontent.com/93355393/139486199-511e87c7-1113-49b0-915a-dc19f7170b98.png)

**To Reproduce**

1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Screenshots**

![NmsXvX6L](https://user-images.githubusercontent.com/93355393/139486136-ce3f4bf0-54f6-423d-ab76-d80f06434453.png)

**Comment by win32kbase** [comment]
I have no idea what I'm looking at.

**Comment by 1fxe** [comment]
Looks like an issue with my notification https://github.com/1fxe/Recaf4Forge

**Comment by storm772** [comment]
No. It happens with Right Click > Remove Too.
![image](https://user-images.githubusercontent.com/93355393/139487388-0a08411d-9be4-4063-9581-2b975fec4a8e.png)

**Comment by storm772** [comment]
> 
> 
> I have no idea what I'm looking at.

The background of the notification is invisible.

**Comment by win32kbase** [comment]
Fixed in above PR, thanks

**Comment by storm772** [comment]
You didn't fixed it.

**Comment by win32kbase** [comment]
![image](https://user-images.githubusercontent.com/6201484/139489994-cffa34e9-d61e-499b-bbd8-d4952a6c2d50.png)

**Comment by storm772** [comment]
Fixed
