### ISSUE TITLE
UI failed to load after using a plugin that implements the workspace interface

### ISSUE THREAD

**Issue by pppppkun** [Col-E/Recaf#418]
I developed a plugin which implements Workspace interface and apply it in Recaf to verify whether it can work successfully, but when I moved jar package into **/plugin directory and try to start Recaf, the crash happened and no useful  information has logged
The question may happened in my own code, so i comment all my code and the plugin's code become below
![image](https://user-images.githubusercontent.com/43557766/140641282-b421c5b7-13c0-43ec-a321-691bbdc9aa58.png)
I try to start Recaf again, but the same log information appeared. The information is shown below
![image](https://user-images.githubusercontent.com/43557766/140641331-c1645c64-b271-4eba-97b2-b88b54616a7d.png)
If no plugin is loaded, the Recaf can be started successfully. Considering that the Ui is did not appeared when I loaded my plugin, I try to make breaks in the Recaf's source code. There was nothing wrong with the methods in the `Recaf.java`, and then I started debugging the `MainWindow.java` (The println code is added myself)
![image](https://user-images.githubusercontent.com/43557766/140641456-8327985b-0ba2-4012-bf35-b7b964c2b27e.png)
Compared with the start process which no plugin is loaded, I can't tell if there is an exception. 
I notice that there are two lines of code here `updateWorkspaceNavigator` and `PluginsManager.getInstance().addPlugin(new WindowPlugin());`, Is it possible that these two lines of code caused the UI to fail to load? Or other operations are required when using this interface?

English is not my mother tongue. If there is any offense, I apologize

**Comment by Col-E** [comment]
I made a simple workspace plugin with the following code:
```java
package me.coley.recaf.plugin.rename;

import me.coley.recaf.plugin.api.WorkspacePlugin;
import me.coley.recaf.workspace.Workspace;
import org.plugface.core.annotations.Plugin;

@Plugin(name="Test")
public class Test implements WorkspacePlugin {
    @Override
    public String getVersion() {
        return "1.0.0";
    }

    @Override
    public String getDescription() {
        return "test desc";
    }

    @Override
    public void onClosed(Workspace workspace) {
        System.out.println("Close workspace");
    }

    @Override
    public void onOpened(Workspace workspace) {
        System.out.println("Open workspace");
    }
}
```

When I placed it into the `plugins` folder and ran Recaf, it started normally and the `println` calls appeared where they were expected to. 

> the crash happened and no useful information has logged

Thats odd that nothing was logged. Usually when a plugin loads if a problem occurs it _should_ be logged here: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/Recaf.java#L131

Since my little demo works fine, I'm not sure what the issue is on your end until there's more information provided. You could possibly run Recaf with a debugger and step through the plugin loading process.

**Comment by pppppkun** [comment]
> I made a simple workspace plugin with the following code:
> 
> ```java
> package me.coley.recaf.plugin.rename;
> 
> import me.coley.recaf.plugin.api.WorkspacePlugin;
> import me.coley.recaf.workspace.Workspace;
> import org.plugface.core.annotations.Plugin;
> 
> @Plugin(name="Test")
> public class Test implements WorkspacePlugin {
>     @Override
>     public String getVersion() {
>         return "1.0.0";
>     }
> 
>     @Override
>     public String getDescription() {
>         return "test desc";
>     }
> 
>     @Override
>     public void onClosed(Workspace workspace) {
>         System.out.println("Close workspace");
>     }
> 
>     @Override
>     public void onOpened(Workspace workspace) {
>         System.out.println("Open workspace");
>     }
> }
> ```
> 
> When I placed it into the `plugins` folder and ran Recaf, it started normally and the `println` calls appeared where they were expected to.
> 
> > the crash happened and no useful information has logged
> 
> Thats odd that nothing was logged. Usually when a plugin loads if a problem occurs it _should_ be logged here: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/Recaf.java#L131
> 
> Since my little demo works fine, I'm not sure what the issue is on your end until there's more information provided. You could possibly run Recaf with a debugger and step through the plugin loading process.

This really confuses me. Your example can't run on my computer as my own code.

> You could possibly run Recaf with a debugger and step through the plugin loading process.
That's what I have tried before and I found that Recaf successfully loads plugin but the UI can't load. I guess the problem may be related to the Run Environment, I run Recaf'code under MacOS and Oracle jdk1.8.0_301, I try to run this code using openjdk1.8 but I failed for some reasons which I can't remember...
maybe I need to run the code under the environment as you?

**Comment by pppppkun** [comment]
> > I made a simple workspace plugin with the following code:
> > ```java
> > package me.coley.recaf.plugin.rename;
> > 
> > import me.coley.recaf.plugin.api.WorkspacePlugin;
> > import me.coley.recaf.workspace.Workspace;
> > import org.plugface.core.annotations.Plugin;
> > 
> > @Plugin(name="Test")
> > public class Test implements WorkspacePlugin {
> >     @Override
> >     public String getVersion() {
> >         return "1.0.0";
> >     }
> > 
> >     @Override
> >     public String getDescription() {
> >         return "test desc";
> >     }
> > 
> >     @Override
> >     public void onClosed(Workspace workspace) {
> >         System.out.println("Close workspace");
> >     }
> > 
> >     @Override
> >     public void onOpened(Workspace workspace) {
> >         System.out.println("Open workspace");
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I placed it into the `plugins` folder and ran Recaf, it started normally and the `println` calls appeared where they were expected to.
> > > the crash happened and no useful information has logged
> > 
> > 
> > Thats odd that nothing was logged. Usually when a plugin loads if a problem occurs it _should_ be logged here: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/Recaf.java#L131
> > Since my little demo works fine, I'm not sure what the issue is on your end until there's more information provided. You could possibly run Recaf with a debugger and step through the plugin loading process.
> 
> This really confuses me. Your example can't run on my computer as my own code.
> 
> > You could possibly run Recaf with a debugger and step through the plugin loading process.
> 
> That's what I have tried before and I found that Recaf successfully loads plugin but the UI can't load. I guess the problem may be related to the Run Environment, I run Recaf'code under MacOS and Oracle jdk1.8.0_301, I try to run this code using openjdk1.8 but I failed for some reasons which I can't remember... maybe I need to run the code under the environment as you?

I try your code twice again, It ran but quit after a few seconds...

**Comment by Col-E** [comment]
What happens if you run with JDK 11 or higher?

**Comment by pppppkun** [comment]
> What happens if you run with JDK 11 or higher?

The Recaf can't start as the IDEA give the information about packages(org.objectweb.asm) not exists.
```
/Recaf/src/main/java/me/coley/recaf/mapping/Mappings.java:6:25
java: package org.objectweb.asm does not exists
/Recaf/src/main/java/me/coley/recaf/mapping/Mappings.java:7:25
java: package org.objectweb.asm does not exists
/Recaf/src/main/java/me/coley/recaf/mapping/Mappings.java:8:25
java: package org.objectweb.asm does not exists
/Recaf/src/main/java/me/coley/recaf/mapping/Mappings.java:9:33
java: package org.objectweb.asm.commons does not exists
/Recaf/src/main/java/me/coley/recaf/mapping/Mappings.java:184:54
java: can't find symbol
  Symbol:   Class ClassReader
  Position: Class me.coley.recaf.mapping.Mappings
/Users/pkun/IdeaProjects/Recaf/src/main/java/me/coley/recaf/mapping/Mappings.java:195:54
java: can't find symbol
  Symbol:   Class ClassReader
  Position: Class me.coley.recaf.mapping.Mappings

```
The first time I run Recaf, I use OpenJDK11, but it failed and after searching, I think I need to transfer to OracleJDK1.8. I run the same sample plugin example in another Windows Computer which uses OracleJDK1.8, and it works!

**Comment by Col-E** [comment]
That looks like somehow the project isn't pulling in the dependencies it needs. I don't know how that's happening, maven always _"just works"_ for me.
