### ISSUE TITLE
Some strings cannot be translated

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#42]
1. [FilePrompt.java#L16](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/util/FilePrompt.java#L16), L34, L51 and L63
![JFileChooser](https://user-images.githubusercontent.com/12008103/35789721-fbb2c696-0a78-11e8-8264-27a72bd22ad7.jpg)
-----
2. [JarFileTree.java#L35](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/ui/component/tree/JarFileTree.java#L35), L58, L64 and L67
![JarFileTree](https://user-images.githubusercontent.com/12008103/35789837-fac4f244-0a79-11e8-9854-746e888782f9.jpg)
-----
3. [AccessPanel.java#L24-L27](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/ui/component/panel/AccessPanel.java#L24-L27) and L45
![AccessPanel](https://user-images.githubusercontent.com/12008103/35789914-6ad44fb2-0a7a-11e8-9bd8-14fb75cc8992.jpg)
-----
4. [DefinitionBox.java#L63](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/ui/component/internalframe/DefinitionBox.java#L63) and L96
![DefinitionBox-1](https://user-images.githubusercontent.com/12008103/35790010-0f6707a4-0a7b-11e8-8065-45c280425a7e.jpg)
![DefinitionBox-2](https://user-images.githubusercontent.com/12008103/35790020-174e1b24-0a7b-11e8-80be-459f4f9bbaf8.jpg)
-----
5. [MemberTable.java#L29](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/ui/component/table/MemberTable.java#L29), [VariableTable.java#L37](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/ui/component/table/VariableTable.java#L37) and [ClassDisplayPanel.java#L224](https://github.com/Col-E/Recaf/blob/2ee2827/src/me/coley/recaf/ui/component/panel/ClassDisplayPanel.java#L224)
![MemberTable](https://user-images.githubusercontent.com/12008103/35790201-f8bc25a6-0a7b-11e8-9845-b25108222064.jpg)

**Comment by Col-E** [comment]
Yeah, I've missed a few things here and there...

**Comment by Col-E** [comment]
Last few commits have fixed all of these. I've attempted to use existing translations to fill in the new values. If I messed them up do correct me.
