### ISSUE TITLE
Desktop.browse(...) freezes JFX on Linux with GNOME

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#424]
**Describe the bug**

> Any call to `Desktop.browse(...)` freezes Recaf on Linux machines with GNOME

**To Reproduce**

- Say _"yes"_ to opening the documentation
- Help > System info > open recaf directory

**The Solution**

From: https://stackoverflow.com/questions/23176624/javafx-freeze-on-desktop-openfile-desktop-browseuri

```java
if( Desktop.isDesktopSupported() )
{
    new Thread(() -> {
           try {
               Desktop.getDesktop().browse( new URI( "http://..." ) );
           } catch (IOException | URISyntaxException e1) {
               e1.printStackTrace();
           }
       }).start();
}
```

Ideally since this would be all in the `UI` module, we could use our existing `Threads` class for pooling the threads.

We should make a wrapper utility so that we don't have this big block of code every time we want to invoke `browse`. This should be done on both `master` and `dev3`

**Comment by FlowArg** [comment]
Currently on the latest version of Arch with KDE Plasma 5.23.3: the bug doesn't occur.

**Comment by Col-E** [comment]
Shoulda specified, this is on Manjaro with GNOME. I think its a GNOME problem.

**Comment by xxDark** [comment]
Can't https://docs.oracle.com/javase/8/javafx/api/javafx/application/HostServices.html#showDocument-java.lang.String- be used instead?

**Comment by Col-E** [comment]
Didn't know that existed. It doesn't look like it'll work for opening local file paths according to the docs though.

**Comment by Geolykt** [comment]
It should be known that on my installs (fedora) Desktop.browse traditionally only opened the browse when the JVM exists. I have no idea why though

**Comment by win32kbase** [comment]
Fixed in 2x as of https://github.com/Col-E/Recaf/commit/3212458c61295834f0bf851cf1efea46dd2e4793, still needs to be ported to 3x though

**Comment by Col-E** [comment]
Ported to 3x: 88adb702043beac1d9738b1afbb33794e3d1d3e6
