### ISSUE TITLE
Wrong Windows OS version 

### ISSUE THREAD

**Issue by TheGloriousDuck** [Col-E/Recaf#429]
**Describe the bug**

> The OS name stated is Windows 10, even though Windows 11 is installed.

**To Reproduce**

1. Have Windows 11 installed
2. Open recaf
3. Open System information
4. See Windows 10 as the OS name even though you are on Windows 11

**Exception**
I am running an Insider version of Windows 11 that was made before the public release, which may affect the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/43049985/143779424-aa83960e-8544-4e6b-8d07-c4d9f65bd085.png)

**Comment by win32kbase** [comment]
The OS version is obtained from Java's System.getProperty. We're not responsible for what it returns.

https://github.com/Col-E/Recaf/blob/419925d996fe33d3caa94a864070af97c1a2d625/src/main/java/me/coley/recaf/ui/controls/pane/SysInfoPane.java#L47
