### ISSUE TITLE
Uncaught exception while opening an invalid Java program

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#43]
```
IllegalArgumentException:
Message: null
Trace: 
org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
org.objectweb.asm.ClassReader.<init>(ClassReader.java:443)
me.coley.recaf.asm.Asm.readClass(Asm.java:46)
me.coley.recaf.asm.JarData.<init>(JarData.java:58)
me.coley.recaf.Recaf.selectInput(Recaf.java:118)
me.coley.recaf.ui.SwingUI.lambda$setupMenu$0(SwingUI.java:102)
me.coley.recaf.ui.component.action.ActionMenuItem$1.actionPerformed(ActionMenuItem.java:21)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

Steps-to-reproduce:
1. Click `File -> Open`.
2. Change `File Type` to `All Files` (or something like that, I'm not sure about the specific wording).
3. Open any file that isn't a Java program.
-----
Maybe add some validation like this:
![validation](https://user-images.githubusercontent.com/12008103/35790770-064a9c86-0a7f-11e8-937e-9bf96aeebf20.jpg)
or
```java
fileChooser.setAcceptAllFileFilterUsed(false);
```
so users will only be able to select a class or jar?

**Comment by Col-E** [comment]
Went with `fileChooser.setAcceptAllFileFilterUsed(false);` will commit in a bit.
