### ISSUE TITLE
Cannot save changes

### ISSUE THREAD

**Issue by IWolfZZ** [Col-E/Recaf#435]
**Describe the bug**
Cannot save changes when there's "errors".

> A clear and concise description of what the bug is. If there's errors it wont let you save any changes to the file which obfuscation prevents this from editing the file.

**To Reproduce**

1. Open a jar
2. Have an error because of a obfuscation or make something error
3. Try saving changes

**Comment by win32kbase** [comment]
What do you mean it's "stupid" that you can't save with errors? That doesn't even make sense. Decompilers are great but they're not magic. There are some things that are representable in bytecode form that physically can't be represented in Java source code form making them literally impossible to recompile, and decompilers can't always output recompilable code even in the case that it's valid in both forms. Please read the documentation and learn how to use the assembler.

**Comment by IWolfZZ** [comment]
How am I suppose to edit something when I cant save it when there's errors from obfuscation stopping me from saving it?

**Comment by IWolfZZ** [comment]
![image](https://user-images.githubusercontent.com/87252860/146656268-949d150c-f740-4b57-92e0-485d1c924fcc.png)

**Comment by win32kbase** [comment]
https://www.coley.software/Recaf-documentation/use-assembler.html

**Comment by IWolfZZ** [comment]
Theres no other way to edit the code? 
![image](https://user-images.githubusercontent.com/87252860/146656797-36f1d01f-45c7-491e-b7f6-a156299e48c4.png)
This assembler is confusing.

**Comment by win32kbase** [comment]
Not easily in it's obfuscated state. To recompile it you would have to fix the errors yourself which is probably easier said than done especially considering other classes and their obfuscated method and field names.

**Comment by Col-E** [comment]
For reused variables stripping debug in the config would be useful.

Or runninf the jar through a deobf program first.

**Comment by win32kbase** [comment]
https://github.com/java-deobfuscator/deobfuscator potentially
