### ISSUE TITLE
CRC32 corrupter works on Recaf 2.21.4. 

### ISSUE THREAD

**Issue by vektorinspace** [Col-E/Recaf#440]
**Describe the bug**

> If you apply the CRC32 corrupter on a jar, classes appear invisible in Recaf.

**To Reproduce**

1. Obfuscate a jar with the CRC32 corrupter.
2. Open the jar in Recaf.
3. You can observe that the classes are invisible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96449363/147884018-4c093467-9ce9-4b09-9630-e38d1c961315.png)

See [Radon obfuscator](https://github.com/ItzSomebody/radon/blob/master/src/main/java/me/itzsomebody/radon/Radon.java#L123) on how the CRC32 corrupter works.

**Comment by faastcall** [comment]
Duplicate of #403, fixed in the `dev3` branch.

**Comment by vektorinspace** [comment]
👍

**Comment by win32kbase** [comment]
Fixed in 2x now
