### ISSUE TITLE
Jar won't run

### ISSUE THREAD

**Issue by NotADinosaur** [Col-E/Recaf#442]
It's probably just me being stupid, so sorry about this. I'm using java 17 and the latest release of recaf, and when I try to open the jar it just opens a cmd window with `no main manifest attribute, in recaf-2.21.9.jar`
What am I doing wrong?

**Comment by xxDark** [comment]
Use the jar with the dependencies bundled.
https://www.coley.software/Recaf-documentation/setup-get.html

**Comment by NotADinosaur** [comment]
ok, I'll try that. I don't really know what I'm doing at all haha

**Comment by NotADinosaur** [comment]
it says javafx could not be found, even though I'm using a version of java above 11

**Comment by xxDark** [comment]
Your JDK installation may be misconfigured, check your environment variables.

**Comment by NotADinosaur** [comment]
not sure what I did but it works now. Thanks!
