### ISSUE TITLE
Issue when running it

### ISSUE THREAD

**Issue by KlaasNiphaas** [Col-E/Recaf#444]
**Describe the bug**

Whenever i run the latest jar with sources i get an error:

```
Error occurred during initialization of VM
Failed setting boot class path.
```

**To Reproduce**

Just `java -jar recaf-2.21.10-J8-jar-with-dependencies.jar`

1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Exception**

If applicable, add the exception/stacktrace.
```
```

**Screenshots**
![image](https://user-images.githubusercontent.com/80031535/148186320-52941b51-058d-4486-86e0-109c092f506d.png)

**Comment by terminalsin** [comment]
Are you sure that’s not an issue with your Java installation? Try running “java -version” and post a screenshot of the result in here.

**Comment by KlaasNiphaas** [comment]
Getting the same issue there. Should i try re installing?
![image](https://user-images.githubusercontent.com/80031535/148196459-367349e1-0e48-4fe1-ab0e-c67617026d8d.png)

**Comment by terminalsin** [comment]
Yea. This is an issue with your installation, not recaf. 
https://www.oracle.com/java/technologies/downloads/, scroll down to Java 8 and create an account to download the Windows X64 (DO NOT SELECT X32).

@Col-E Ig you can close this

**Comment by xxDark** [comment]
As it was said, that is an issue with your JDK installation. One other option is to download JDK 11+ installation, that you can get from https://adoptium.net/.
