### ISSUE TITLE
encoding issues

### ISSUE THREAD

**Issue by Tukali** [Col-E/Recaf#446]
If there is a Chinese in the file, it will be garbled
![image](https://user-images.githubusercontent.com/45891208/148531717-5e436f33-9f38-480c-8c86-a1f7386cdcd3.png)

**Comment by 3jq** [comment]
Probably recaf just gotta use utf-16 for decompiled text.

**Comment by xtherk** [comment]
use `java -jar -Dfile.encoding=UTF-8 recaf.jar` to run

**Comment by xtherk** [comment]
> If there is a Chinese in the file, it will be garbled ![image](https://user-images.githubusercontent.com/45891208/148531717-5e436f33-9f38-480c-8c86-a1f7386cdcd3.png)

### Reason
Your Windows system defaults to GBK, you double-click `recaf.jar` or use `java -jar recaf.jar` Run, the default characters inside the Java are GBK, the Recaf processing text is use ` new String(Byte[])`, this when the default encoding is gbk, it will cause garbled.

**Comment by Toshimichi0915** [comment]
we can close this issue?

**Comment by win32kbase** [comment]
> we can close this issue?

Yep, thank you for your PR.

**Comment by V-KOOL** [comment]
Have you solved this Chinese garbled code problem?
