### ISSUE TITLE
Internal update prompt does not show "Important News" piece

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#448]
![image](https://user-images.githubusercontent.com/21371686/148595012-b5b811ee-4aeb-4b28-874a-8a8d340f5f13.png)

The release posts are only partially parsed, making the prompt only show bullet point items.

**Comment by win32kbase** [comment]
This was fixed in https://github.com/Col-E/Recaf/commit/7ee876d29b504c0dbdf7855a8bf0cc4cdd591b23
