### ISSUE TITLE
Deobfuscation of class names, methods and fields

### ISSUE THREAD

**Issue by RealIndica** [Col-E/Recaf#476]
## Deobfuscation

Can deobfuscate class names, methods and fields. Working with obfuscated code is a huge headache, so this feature is entirely necessary for ease of use. Renamed class names, methods and fields should also include a comment of their original names.

Example obfuscated:
```java
a.a.a(true);
```

Example deobfuscated:
```java
class1.field1.method1(true); 
```

It would also be useful to find which fields, methods and classes are actually obfuscated. You could find these by checking for duplicate names and their length.

**Comment by xxDark** [comment]
You can rename classes, methods and fields by right clicking on an item and choosing `Rename` option.

**Comment by RealIndica** [comment]
> You can rename classes, methods and fields by right clicking on an item and choosing `Rename` option.

Yes, but its tedious to manually rename all when the entire thing is obfuscated. Automation would be useful and deobfuscation should only be needed for patching, not recompiling with code.

**Comment by RealIndica** [comment]
> > > You can rename classes, methods and fields by right clicking on an item and choosing `Rename` option.
> > 
> > 
> > Yes, but its tedious to manually rename all when the entire thing is obfuscated. Automation would be useful and deobfuscation should only be needed for patching, not recompiling with code.
> 
> There are plugins in our Discord server that provide automatic renaming when you load the jar. I think they are also mentioned on the website in `Plugins` section. Is that what you want?

Absolutely, i'll join the discord. Shouldn't deobfuscation be part of the base program though? Just a suggestion.

**Comment by xxDark** [comment]
> > > > You can rename classes, methods and fields by right clicking on an item and choosing `Rename` option.
> > > 
> > > 
> > > Yes, but its tedious to manually rename all when the entire thing is obfuscated. Automation would be useful and deobfuscation should only be needed for patching, not recompiling with code.
> > 
> > 
> > There are plugins in our Discord server that provide automatic renaming when you load the jar. I think they are also mentioned on the website in `Plugins` section. Is that what you want?
> 
> Absolutely, i'll join the discord. Shouldn't deobfuscation be part of the base program though? Just a suggestion.

Recaf provides an ability to remap stuff, as mentioned above, and plugins are made to work with the designed API, not the Recaf itself, that's the approach we took. I guess this issue can be closed, in case the problem is solved?

**Comment by RealIndica** [comment]
> > > > > You can rename classes, methods and fields by right clicking on an item and choosing `Rename` option.
> > > > 
> > > > 
> > > > Yes, but its tedious to manually rename all when the entire thing is obfuscated. Automation would be useful and deobfuscation should only be needed for patching, not recompiling with code.
> > > 
> > > 
> > > There are plugins in our Discord server that provide automatic renaming when you load the jar. I think they are also mentioned on the website in `Plugins` section. Is that what you want?
> > 
> > 
> > Absolutely, i'll join the discord. Shouldn't deobfuscation be part of the base program though? Just a suggestion.
> 
> Recaf provides an ability to remap stuff, as mentioned above, and plugins are made to work with the designed API, not the Recaf itself, that's the approach we took. I guess this issue can be closed, in case the problem is solved?

Yeh, thank you for the guidance :)
