### ISSUE TITLE
Search references incomplete results (missing synthetic accessors) 

### ISSUE THREAD

**Issue by werame** [Col-E/Recaf#480]
I cannot upload the sources as they are proprietary, but this should be easy enough to repro on some other setup. If some class is `import`ed, recaf can't find the importer as referencing it, e.g.

```
DEFINE  <init>(Lfoo/bar/zap; 1)V
A:
ALOAD this
ALOAD 1
PUTFIELD foo/bar/XX/yy Lfoo/bar/zap;
ALOAD this
INVOKESPECIAL java/lang/Object.<init>()V
RETURN
B:
```

is not found when going to `public class zap` (in the `foo.bar` package) right-clicking it a 
and choosing "Search references".

Recaf does find occurrences like `NEW foo/bar/zap` (in other files) but not the one above, perhaps because of the 'L'.

I also tried searching for `Lfoo/bar/zap` (i.e. `L` prepended) but that also finds nothing.

Even searching for the unqualified class name `zap` doesn't find that reference.

The problem seems to be caused by synthetic accessors.

**Comment by Col-E** [comment]
Are you sure you're using the search feature right?

As per: https://www.coley.software/Recaf-documentation/use-search.html

> **Class References**
> Finds where types are referenced. This is not to be confused with member reference. This finds instantiations of the type in the following cases:
> -    Example.class
> -    new Example
> -    x instanceof Example
> -    Example myLocalVariable

Not all fields are required in the search so if you search for `foo/Bar` as an owner in member references it will show you any reference to a field or method defined in `foo/Bar`

**Comment by Col-E** [comment]
I'm going to assume this was confusion between the class and member ref searches until further comment.
