### ISSUE TITLE
Impossible to edit inner classes?

### ISSUE THREAD

**Issue by werame** [Col-E/Recaf#481]
**Describe the bug**

So it seemss Recaf cannot recompile an inner class. 

**To Reproduce**

Again I cannot share the code of the app here, but it seems the problem is that CFR generates an `implements` for the inner class referring to the outer and then (predictably) on save/compile "interface is expected here".

And likewise  for all the `@Override`s that CFR generates for the inner class.

**Comment by Col-E** [comment]
> Title

Recaf doesn't have any special compiler. The only thing Recaf does which makes it easier than decompile recompile yourself is that it analyzed the bytecode of your application and generates missing references. This allows compiling against types you don't have.

That being said, if you decompile an inner class without any context of the outer class that's not going to be the same class when recompiled. You can edit them if you have the outer class as context. That being said while recompiling is a handy feature it does not apply to all cases such as the one here. If you want to open just the inner class you're going to have to use the assembler to make your changes.

>  it seems the problem is that CFR generates an implements for the inner class referring to the outer and then (predictably) on save/compile "interface is expected here".

I'm not really sure what this sentence means. When I look at the decompiled output of an inner class it looks normal to me _(plus or minus any syntatic sugar for outer access methods)_

**Comment by Col-E** [comment]
Usually the pattern is `Outer` then `Outer$Inner` with each having an appropriate `InnerClasses` attribute being defined in the bytecode. What each decompiler does with this information is on them though, especially with non-standard inputs of obfuscated code. I've not really  seen CFR do something like this so until I see a reproducible case I'm not sure I can offer any advice here.
