### ISSUE TITLE
Workflow for editing extremely unclear

### ISSUE THREAD

**Issue by werame** [Col-E/Recaf#482]
## Feature_Name

There doesn't seem to be any kind of indicator when a class is modified in assembler whether that's a pending change or has been save somewhere (workspace or jar).

Generally Recaf will happily lose all your changes with no indication of what's going on. Especially if you decompile again, it seems to discard all changes from the workspace with no warning. 

It's also unclear if editing methods in assembly from the table mode (which is the only one that might remotely work for inner classes) is saving anything anywhere.

The only way to confirm that Recaf has done anything is to load both old and new jars in a Intellij project and Ctrl+D. And then you see that some method changes were made and some were lost by Recaf. So it seem to only support changing one method at a time, reliably, with a full export, close, re-import cycle needed. Extremely time consuming.

Mkay, apparently in table editing mode you have hit Ctrl+S for every method. Again there's no indicator what has been modified or saved.

But when editing the last method in file that seems to be bugged and not saving.

**Comment by Col-E** [comment]
Every editor region in Recaf flashes green when a save _(By default bound to `Control + S`)_ is executed like so:

![its green](https://www.coley.software/Recaf-documentation/img/save-glow.gif)

When you do this in the assembler window the tab where the assembler was spawned from refreshes the decompiled or table row elements output.

**Comment by xxDark** [comment]
Can you please record the video that demonstrates this issue? (Possibly, with keystrokes shown). Thanks.

**Comment by werame** [comment]
Here's simple scenario:

1. Go in table mode and edit a method, e.g. delete its body but for RETURN.
2. Save with Ctrl+S. It flashes green ok.
3. Right click again the class and choose to decompile with CFR. You get back the old method, before saving.
4. If you go back in table mode, you also see the method back as it was before step 1.

**Comment by Col-E** [comment]
> 3. Right click again the class and choose to decompile with CFR. You get back the old method, before saving.

I can't reproduce this, nor can I reproduce 4. Exporting is unrelated because all it does is export the current state of the files and their changes. The UI should reflect this state, which it does when I follow the given scenario.

**Comment by xxDark** [comment]
Closing, no response
