### ISSUE TITLE
Dialog boxes disappear without interaction after 2-3 seconds, on Windows 10 w/Java 16.

### ISSUE THREAD

**Issue by werame** [Col-E/Recaf#483]
**Describe the bug**

On Windows 10 with Java 16 various yes/no or decompile error dialog boxes disappear by themselves after 2-3 seconds, without mouse or keyboard interaction.

I've looked at the preferences, but I don't see any timeout that would settable for these, so I guess it's a bug.

**Comment by xxDark** [comment]
The popup will disasppear once it loses it's focus as it set [here](https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/ui/controls/popup/DragPopup.java#L60)

**Comment by Col-E** [comment]
^^ Demo showing what xxDark referenced

https://user-images.githubusercontent.com/21371686/153416204-f9996eae-a574-46f0-afc6-b95ed7b02d8f.mp4

**Comment by werame** [comment]
Yeah, I suppose it's due to the dialogs being non-modal and the main window wanting to pop to front now and then for some reason. Updating itself with something, I guess.

**Comment by Col-E** [comment]
Ah, so this follow-up comment seems to be a _different_ bug:

https://user-images.githubusercontent.com/21371686/153524776-2d138c76-f3db-48d9-9a08-2775d7de3184.mp4

The hover-popups on the table columns _(access is instant, return type and args are delayed)_ bring the main window forward, but not into focus. The editor window is now in an odd focus state.

**Comment by Col-E** [comment]
Closing as 4.X is the only branch we're working on going forward.
