### ISSUE TITLE
Saving jar changes classes which have not been edited?

### ISSUE THREAD

**Issue by cnsgithub** [Col-E/Recaf#49]
Hi, i noticed that saving a jar will result in a lot of changes in *.class files which have not been touched. 

I only changed a single ICONST_0 to ICONST_1 in one *.class file, and saved the jar. So i expected that this change is only reflected in the changed class. However most *.class files have been edited.

Would it be possible to add a separate Save to each single class when something has been changed? This would make it easier to compare / see what has been changed manually compared with the genuine jar

Only change in one class:
![image](https://user-images.githubusercontent.com/13161711/39616737-36e67700-4f7d-11e8-9eea-8c207da1e983.png)

This class has not been touched manually:
![image](https://user-images.githubusercontent.com/13161711/39616715-1f4a43a6-4f7d-11e8-8010-16f5f5389bc1.png)

Thanks.. Nice tool btw :)

**Comment by Col-E** [comment]
Well, the new release is out *(Its not 100% done, but nothing that won't be added over the next week or so)* so this is now complete.
