### ISSUE TITLE
reobf fails on setfield call when class extends class extends class

### ISSUE THREAD

**Issue by jredfox** [Col-E/Recaf#491]
**Describe the bug**

> fails to reobfuscate with a valid srg mappings and minecraft 1.5.2 jar added in as a library

**To Reproduce**

1. use this jar [harken-deob.jar.zip](https://github.com/Col-E/Recaf/files/8131775/harken-deob.jar.zip)
2. use this mapping 
[joined.obf - Copy.srg.txt](https://github.com/Col-E/Recaf/files/8131779/joined.obf.-.Copy.srg.txt)
3. add minecraft.jar as a library now https://launcher.mojang.com/v1/objects/465378c9dc2f779ae1d6e8046ebc46fb53a57968/client.jar
4. class ItemHSScythe.class has a deobed feild called this.maxStackSize when it's suppose to be obf. 

Q:A: 
- since it's a forge mod did I try adding forge as a library: No because that field is a vanilla minecraft field it failed when it shouldn't have. **I also later tried it with the same result**
- the class ItemHSScythe extends ItemSword which extends Item. the mapping says maxStackSize  for Item is `FD: net/minecraft/item/Item/maxStackSize wk/cq` so it should have worked.
- this of course causes a java runtime error `cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: maxStackSize`.

**Comment by Col-E** [comment]
Sorry for the late reply, here's whats going on:

This is the bytecode in the constructor that assigns the value.
```
ALOAD this
ICONST_1
PUTFIELD mod_HarkenScythe/common/ItemHSScythe.maxStackSize I
```
The owner of `maxStackSize` is the current class `ItemHSScythe`. At runtime this will look up the class hierarchy to find it defined in parent types, IE `ItemSword` then `Item`. 

The problem is Recaf/JPhantom cannot infer that `maxStackSize` belongs to either of these classes because the owner is defined as _itself_. Adding the `minecraft.jar` does not change things since the jar is already obfuscated, so there is no `ItemSword` or `Item` inside, just a bunch of `aaa`, `aab`, `aac` etc.

So the mapper is not able to figure out its supposed to change that reference. You would need to add an unobfuscated minecraft jar that contains the `Item` class.

**Comment by jredfox** [comment]
Well shouldn't you remapp all jars to the same mapping before that happens? I was able to remap deob most of the jar with Minecraft remaining obf. I remapped lots of jars before without having the issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Col-E** [comment]
> Well shouldn't you remapp all jars

The only jar edited is the primary jar. Anything beyond that is treated as a supporting library.

> I remapped lots of jars before without having the issue.

Right, but this isn't really a common thing. So it doesn't present itself often. But as I've explained all you need to do is add a deobfuscated MC jar and it'll fix this.

**Comment by jredfox** [comment]
Ok well can you have an error screen explaining that the jars all need to be mapped the same if you decide it's not a bug. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Col-E** [comment]
> Ok well can you have an error screen explaining that the jars all need to be mapped

What would be the criteria for detecting this though?

There surely are lots of fields that don't get mapping in the jar. So it would have to somehow know that something in the mappings you provided wasn't mapped. But as I've explained, Recaf isn't aware of the relationship between the Sytch class and the ItemSword/Item classes. With a lack of information how would you know you missed out on something?

**Comment by jredfox** [comment]
Check the first last and middle mapping if it's not found for the the library jar then throw the error screen. It's expected to have one jar fully mapped one or the other not both

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jredfox** [comment]
I would also check one of each type fields methods and even classes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Col-E** [comment]
> It's expected to have one jar fully mapped

For this specific case maybe. But most mapping work I've seen being used is with partial mappings, so there will be plenty of _"missing"_ items in this case. Recaf needs to be able to know what the intention is, but mapping is a generalized process so thats not really an easy ask.
