### ISSUE TITLE
Add support for Case Sensitive classes

### ISSUE THREAD

**Issue by ConaII** [Col-E/Recaf#496]
## Case sensitivity

Currently, this program will not work with jars that have repeating classes named for example "a.class" and "A.class".
This breaks, a lot of things, first of all, you can't access the other classes, since they are deleted, secondly, after saving the jar the case sensitive classes are deleted.

**Comment by Col-E** [comment]
IDK what you're talking about. Nothing in Recaf is case insensitive in terms of internal file state management.

[demo.zip](https://github.com/Col-E/Recaf/files/8155553/demo.zip)

Editing works

https://user-images.githubusercontent.com/21371686/156033690-3cfe0e8b-b584-43f1-81ba-b9f78efd6abe.mp4

:

**Comment by win32kbase** [comment]
If you're referring to renaming, maybe a warning should be put in place but either way it should be obvious why you cannot have two classes of the same identical casing and name.

**Comment by ConaII** [comment]
Weird, it happens in my case.
Anyways i had to install linux to modify some classes inside the jar.

**Comment by faastcall** [comment]
> Weird, it happens in my case. Anyways i had to install linux to modify some classes inside the jar.
> 
> Also, in the 3.0x it doens't happen

Sample?
