### ISSUE TITLE
Not saving code moddifications after exporting

### ISSUE THREAD

**Issue by XeonLyfe** [Col-E/Recaf#498]
After I open a Jar and edit it, then I click File > Export Program Then export it, it doesn't save the code that I edited in recaf into the class.

**Comment by win32kbase** [comment]
Are you recompiling the file..? Please read the documentation at https://www.coley.software/Recaf-documentation/ for more information on how to use the tool.

**Comment by XeonLyfe** [comment]
I am trying to edit a Jar and remove authentication and then recompile. after I export it, the edited class doesn't save.

**Comment by win32kbase** [comment]
'Remove authentication'? What you do with the tool on your own is your own business but we will not provide support for people who are just cracking random software.
