### ISSUE TITLE
APK support

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#50]
A friend of mine has suggested adding APK support, but I'm not sure how to approach that given the major [differences between standard java's bytecode and dalvik](https://forensics.spreitzenbarth.de/2012/08/27/comparison-of-dalvik-and-java-bytecode/). 

Any ideas / suggestions on how to approach this would be greatly appreciated.

**Comment by andylizi** [comment]
How about using [dex2jar](https://github.com/pxb1988/dex2jar) to convert it and then feed it to ASM...

**Comment by Col-E** [comment]
Was thinking about it but was hoping to see if any other solutions existed. I'd prefer not to depend on an external command-line tool, and their java backend has almost no documentation as far as I can see. 

I will use it if I can't find any other cleaner alternative. The ideal situation would be `dex` -> `Map<className, org.objectweb.asm.ClassNode>` -> `edit` -> `dex` without any dependence on file IO / CLI.

**Comment by mendax47** [comment]
> How about using [dex2jar](https://github.com/pxb1988/dex2jar) to convert it to classes and back...

dex2jar doesn't support multidex... so if any apk contain multiple dex file then the result will be very unexpected..

**Comment by Col-E** [comment]
For multiple reasons I'm going to refer APK modification to another project, [AndroidProjectCreator](https://maxkersten.nl/projects/androidprojectcreator/) _([Github](https://github.com/ThisIsLibra/AndroidProjectCreator))_. 

Closing as out of scope.
