### ISSUE TITLE
Choosing Java compiler version?

### ISSUE THREAD

**Issue by ToruTheRedFox** [Col-E/Recaf#504]
Would choosing the Java compiler version be possible? 

<del>I'm trying to add a public static long to class A and use it in class B, but need it to run on Java 6 (due to incompatibilities with plugins as this is for an old Minecraft server)</del>

<del>with a much newer Java version, it runs fine, but with the likes of Java 6 and even 7, it just throws a NoSuchFieldError</del>

turns out that class A was being overridden by something else lol

**Comment by Col-E** [comment]
The compiler tries to use the current class version as a target as seen here: https://github.com/Col-E/Recaf/blob/68096acb9267ae360de887714caf102318fbff76/src/main/java/me/coley/recaf/ui/controls/text/JavaEditorPane.java#L121

The version is then fit into the range of whatever the current compiler _(from your installed version of Java)_ supports.

Looks like you got this resolved though, so I'll close the issue.

**Comment by ToruTheRedFox** [comment]
it's possible to manually go in and set the target lower, but that is a tad bit annoying to do
