### ISSUE TITLE
Escaped unicode characters are decoded wrongly

### ISSUE THREAD

**Issue by L3g7** [Col-E/Recaf#513]
When having an escaped unicode character (`"\\u0041"`), Recaf decodes the unicode character (`"\A"`), resulting in a lexical error.

To reproduce:
1. compile following code
2. open with recaf
```java
class Example {
    String example = "\\u0041";
}
```
![grafik](https://user-images.githubusercontent.com/62625188/160480184-bb37db50-6268-40b5-8ee9-482275104060.png)

**Comment by win32kbase** [comment]
Thanks. Think it is fixed in above PR.

Image:
![image](https://user-images.githubusercontent.com/6201484/160492645-904d5ee6-7839-4fe8-ac87-b629839b40f3.png)

**Comment by Col-E** [comment]
I actually think this is something that should be reported and addressed upstream in CFR. That would be a proper solution rather than us _patching_ the output.

**Comment by win32kbase** [comment]
This is now fixed in both 2X and 3X
