### ISSUE TITLE
method owner does not match type on stack

### ISSUE THREAD

**Issue by Veyselxan** [Col-E/Recaf#518]
Help me pls

JAVA CODE
```
  boolean A() {
		return java.time.LocalDate.now().toString().equals("2022-04-13");
	}
```
To byte 
```
INVOKESTATIC java/time/LocalDate.now()Ljava/time/LocalDate;
INVOKEVIRTUAL java/time/LocalDate.toString()Ljava/lang/String;toString()Ljava/lang/String;
LDC "2022-04-13"
INVOKEVIRTUAL java/lang/String.equals(Ljava/lang/Object;)Z
IRETURN
```

error img:
![image](https://user-images.githubusercontent.com/21371686/162915469-4558f8db-1e90-466e-8430-e8459e400b75.png)

**Comment by Col-E** [comment]
Look at the return type of your method call:

`INVOKEVIRTUAL java/time/LocalDate.toString()Ljava/lang/String;toString()Ljava/lang/String;`

Its `Ljava/lang/String;toString()Ljava/lang/String;` but should only be `Ljava/lang/String;`
