### ISSUE TITLE
ArrayIndexOutOfBoundsException when forgetting ; in method descriptor

### ISSUE THREAD

**Issue by ZainlessBrombie** [Col-E/Recaf#52]
Hey its me again! :)
tried to do an invokespecial for java/lang/IllegalArgumentException <init> with descriptor `(Ljava/lang/String)V`, my mistake, it should have been `(Ljava/lang/String;)V`. Got this exception:

[ERRR:5/29/18 8:57 PM] ArrayIndexOutOfBoundsException: 21
   org.objectweb.asm.Type.getArgumentTypes(Type.java:282)
   org.objectweb.asm.Type.getArgumentTypes(Type.java:545)
   me.coley.recaf.ui.FormatFactory.addMethodType(FormatFactory.java:145)
   me.coley.recaf.ui.FormatFactory.addOpcode(FormatFactory.java:208)
   me.coley.recaf.ui.FormatFactory.opcode(FormatFactory.java:120)
   me.coley.recaf.ui.component.InsnListEditor$OpcodeList.createFormat(InsnListEditor.java:540)
   me.coley.recaf.ui.component.InsnListEditor$OpcodeList.lambda$10(InsnListEditor.java:513)
   com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
   java.security.AccessController.doPrivileged(Native Method)
   com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
   com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
   com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
   com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
   java.lang.Thread.run(Thread.java:748)

PS: Sorry for not fixing that stuff myself, kind of low on time for quality work atm ;)

**Comment by Col-E** [comment]
Pretty sure this is gonna be covered by the patch I made for your other issue: e6207cd1f03c13a47292d48432bf618c3988785a

**Comment by Col-E** [comment]
Yup, tried pasting it in the latest and got this instead of a hard-crash:
![image](https://user-images.githubusercontent.com/21371686/40681813-2d985346-6358-11e8-9656-048eee0ef712.png)
