### ISSUE TITLE
How to save the "Op-codes" after making changes ?

### ISSUE THREAD

**Issue by Redcode456123** [Col-E/Recaf#525]
After making changes it doesn't seems that I am able to save the changes at all, any help on that (Export workspace and export program doesn't do it) ?
-Also as a small note the "Search" for a string inside a JAR file seems not working (or need enhancement).

Thanks for help.

**Comment by Col-E** [comment]
Did you read the documentation on editing? 

https://www.coley.software/Recaf-documentation/use-editing.html

Regarding string search, what did use as a search parameter and what were you trying to find?

**Comment by Col-E** [comment]
No response, closing until requested information is provided
