### ISSUE TITLE
[Question] Is Recaf not support Java 17?

### ISSUE THREAD

**Issue by Alceatraz** [Col-E/Recaf#529]
Can't save with version 17, Is this because Recaf not support 17 yet ?

Under 16 will flash green while press Ctrl+S but 17 will flash red and print this in console:

```text
Reason: 'Fix the invalid input'
```

![1](https://user-images.githubusercontent.com/8266702/165673072-7c784d23-7276-4f7d-b510-30ced42a373e.jpg)
![2](https://user-images.githubusercontent.com/8266702/165673075-3eec9a1a-90ed-48e2-af78-d38664b057ae.jpg)

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/ui/controls/node/ClassNodeEditorPane.java#L144

Needs to be updated, hasn't been touched in a _long_ time.

**Comment by Col-E** [comment]
Closing as 4.X is the only branch we're working on going forward.
