### ISSUE TITLE
No JDK detection

### ISSUE THREAD

**Issue by Telezhka-the-First** [Col-E/Recaf#533]
I installed the latest JDK and launched Recaf. After decompiling a file it said "Recompile disabled. Please run Recaf with a JDK". How to solve it?

**Comment by win32kbase** [comment]
Ensure the JDK is in your path and you are truly running it with the JDK

**Comment by Telezhka-the-First** [comment]
I ensured that JDK is in my path and restarted the computer, but nothing changed. May I be doing something wrong? I launch Recaf through "java -jar "Recaf.jar""

**Comment by win32kbase** [comment]
Can you post the output of `java -version`?

**Comment by Telezhka-the-First** [comment]
Yes, of course. It says:
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by xcfrg** [comment]
`java` is pointing to a java 8 jre from 2015, not a jdk
Fix your path enviorment variable

**Comment by Telezhka-the-First** [comment]
My path currently looks like this, added all what I could think of
https://ibb.co/vJHmFNg

**Comment by Telezhka-the-First** [comment]
Variable JAVA_HOME is correctly set aswell; Path defines, correlating with Java, are even duplicated, but nothing seems to change

**Comment by xcfrg** [comment]
Remove `C:\ProgramData\Oracle\Java\javapath`, and every other java entry that is not `C:\Program Files\Java\jdk1.8.0_333\bin` from your path
Oracle java has a tenency to add that path back on each install, you may want to look into better OpenJDK based vendors

**Comment by Telezhka-the-First** [comment]
I've done all what you've said... and it worked! Thank you very much for your help! Good luck!
