### ISSUE TITLE
android.os.Build missing on save

### ISSUE THREAD

**Issue by IChooseYou** [Col-E/Recaf#535]
How do I set my class path so Recaf finds android studio install directory?

**Comment by Col-E** [comment]
I'm not sure I understand the full issue. Can you elaborate?

**Comment by win32kbase** [comment]
> I'm not sure I understand the full issue. Can you elaborate?

When he recompiles code, android.os.Build is missing which makes compiling fail. JPhantom probably failed.

Ensure phantom class generation is enabled and that it works (errors in console if it doesn't) or add the dependency to the workspace as detailed in https://www.coley.software/Recaf-documentation/use-edit-via-decompile.html

**Comment by win32kbase** [comment]
Also, if that's enabled and classes are still missing then chances are it is just failing. This happens often with target applications that are obfuscated. You can either edit the bytecode directly using the assembler or add the target dependencies into the workspace manually.

**Comment by Col-E** [comment]
Closing with the assumption this is just another case of JPhantom (3rd party) failing for one reason or another.
