### ISSUE TITLE
AgentLoadException: Failed to load agent library: instrument was not loaded.Can't find dependent libraries

### ISSUE THREAD

**Issue by dashne** [Col-E/Recaf#538]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Exception**

If applicable, add the exception/stacktrace.
```
stacktrace goes here
```

**Screenshots**

**Comment by Col-E** [comment]
Please fill out the details of the bug report so that we can understand the issue.
