### ISSUE TITLE
Deleted methods do not save to JAR

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Col-E/Recaf#54]
Due to a bug in `IntelliJ`'s `GUI designer`, a certain method is created multiple times in the target `JAR`. In order to get rid of the duplicates, which cause the whole application `JAR` to crash with a `java.lang.ClassFormatError`, I used `Recaf`.

After deleting the duplicate methods in `Recaf`, I verified the code after decompiling it again using `Recaf` as well and saved the new `JAR` since I only saw one copy of the method left. However, the `JAR` did not get updated analogously to the deleted methods. All duplicates are still there. Why is that? This literally defeats the purpose of a bytecode editor when it does not edit the `JAR` like you did in the GUI. I'm using the as of now [latest release](https://github.com/Col-E/Recaf/releases/tag/1.0.2).

Can you please fix this? Thanks a lot. I appreciate this application but it would be nice if it can deliver what it promises.

**Comment by Col-E** [comment]
Oh yeah, just reproduced this by duplicating a member and renaming it to be the same. Deletion failed. I'll fix that and post a new release with some other fixes in a few minutes.

**Comment by Col-E** [comment]
Fixed in dff56cdd9fc659b0e7028ab7446c1a76690ea629 I'll create a new release
