### ISSUE TITLE
您好，大佬， springboot 项目 直接导出有问题，没有做任何修改，可以帮忙看看吗？

### ISSUE THREAD

**Issue by 1412910387** [Col-E/Recaf#540]
没有做修改，直接导出，大小直接少了10M
![微信截图_20220523104532](https://user-images.githubusercontent.com/59010323/169733773-e6ae3dff-9efb-4524-b188-d65b012a05bf.png)

**Comment by xtherk** [comment]
据我所知，Recaf会优化一些访问不到的字节码指令，移除这些垃圾执行是会减少jar包体积的。

As far as I know, Recaf will optimize some instructions that cannot be accessed. Remove these garbage instructions will reduce the volume of the jar package.

**Comment by xtherk** [comment]
Maybe you use English to ask questions better

**Comment by 1412910387** [comment]
ok

**Comment by Col-E** [comment]
Recaf also compresses jar files by default. In 2X there's not a UI front for it, but it can be disabled in `backend.json`

> `"backend.compressexport": true`

But yes, English is proffered for issues.

**Comment by 1412910387** [comment]
jar package is reduced, but it cannot be started successfully

**Comment by 1412910387** [comment]
springboot  project export  cannot be started successfully，but other project can be started successfully.

such as  recaf-2.21.13-j8-jar-with-dependencies.jar

**Comment by 1412910387** [comment]
> 

thanks, i try

**Comment by 1412910387** [comment]
> 

thank you.but  I cannot  find where  it can be disabled in backend .if have UI front ,better  

Can you give me a configured jar?thank you

**Comment by xtherk** [comment]
> > 
> 
> thank you.but I cannot find where it can be disabled in backend .if have UI front ,better
> 
> Can you give me a configured jar?thank you

C:\Users\${your name}\AppData\Roaming\Recaf\config\backend.json

**Comment by 1412910387** [comment]
> > > 
> > 
> > 
> > thank you.but I cannot find where it can be disabled in backend .if have UI front ,better
> > Can you give me a configured jar?thank you
> 
> C:\Users\{your name}\AppData\Roaming\Recaf\config\backend.json
ok,thank you,i try it

**Comment by 1412910387** [comment]
> > > 
> > 
> > 
> > thank you.but I cannot find where it can be disabled in backend .if have UI front ,better
> > Can you give me a configured jar?thank you
> 
> C:\Users\{your name}\AppData\Roaming\Recaf\config\backend.json
I  try it, BUT springboot project export cannot be started successfully
original springboot project can be started successfully
![image](https://user-images.githubusercontent.com/59010323/169739428-050390e8-f5dc-4ddd-acb1-84c575142f4a.png)
![image](https://user-images.githubusercontent.com/59010323/169739491-603315ff-be72-4cc3-8b64-e96a3daaadde.png)

**Comment by Col-E** [comment]
>   I try it, BUT springboot project export cannot be started successfully

What error does it give you?

**Comment by 1412910387** [comment]
> > I try it, BUT springboot project export cannot be started successfully
> 
> What error does it give you?
sorry ,I went to dinner. I just saw it
![image](https://user-images.githubusercontent.com/59010323/169753692-5868fbd9-c435-415a-bf22-b2ba0192b282.png)

**Comment by 1412910387** [comment]
I found that the original directory has changed

![image](https://user-images.githubusercontent.com/59010323/169754858-869c6f6c-f3fb-4999-bfb1-b739e8caa053.png)
![image](https://user-images.githubusercontent.com/59010323/169754932-e8aaf9a0-eb43-4288-8d77-4b3ce5ed5acd.png)

**Comment by Col-E** [comment]
I'll need access to a small sample which demonstrates this behavior to see why the `io` folder is being removed. But that seems odd that it vanishes like that.

**Comment by 1412910387** [comment]
I solved it through other ways. I'll decompress and replace .class  file directly. Thank you all the same

**Comment by 1412910387** [comment]
> I'll need access to a small sample which demonstrates this behavior to see why the `io` folder is being removed. But that seems odd that it vanishes like that.

I solved it through other ways. I'll decompress and replace .class  file directly. Thank you all the same

**Comment by Col-E** [comment]
While this does solve the issue, I'd like to have an example so that I can fix this regardless. Somebody else will likely encounter the same issue.

**Comment by 1412910387** [comment]
> While this does solve the issue, I'd like to have an example so that I can fix this regardless. Somebody else will likely encounter the same issue.
https://start.spring.io/  You can use this website to generate a demo and try it

**Comment by Col-E** [comment]
👍 Thanks

**Comment by xtherk** [comment]
> While this does solve the issue, I'd like to have an example so that I can fix this regardless. Somebody else will likely encounter the same issue.

SpringBoot jar standard structure:
```txt
-BOOT-INF
-META-INF
-org
```
Our code is located in `BOOT-INF/classes`

Reason: BOOT-INF/classes/io move to /io

**Comment by Col-E** [comment]
^^ That and some rewrite logic I'm doing will better support jar-in-jar content down the road
