### ISSUE TITLE
Recaf window not loading, just whitescreens

### ISSUE THREAD

**Issue by RibozymeR** [Col-E/Recaf#543]
**Describe the bug**

When running
`java -jar recaf-2.21.13-J8-jar-with-dependencies.jar`
or
`java -jar recaf-2.20.3-J8-jar-with-dependencies.jar`
the Recaf window is opened (Recaf icon and title "Recaf"), but nothing is displayed and the window stays blank.

**To Reproduce**

Run `java -jar recaf-2.21.13-J8-jar-with-dependencies.jar`

OS is Windows 10, Java version is
```
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

**Exception**

No exception/error or stacktrace is shown, but the `java` output is
```
17:25:33.426 [main] INFO : Recaf-2.21.13
17:25:33.428 [main] INFO : - Java: 17 (Java HotSpot(TM) 64-Bit Server VM)
17:25:33.542 [main] TRACE: Loading configuration
Jun 06, 2022 5:25:33 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @52cc8049'
```
and after closing the window
```
17:25:36.782 [JavaFX Application Thread] INFO : Shutting down
17:25:36.783 [JavaFX Application Thread] TRACE: Saving configuration
17:25:36.794 [JavaFX Application Thread] TRACE: Shutting down thread executors
```

**Comment by xxDark** [comment]
Please attach screenshots/video

**Comment by RibozymeR** [comment]
![recaf_cmd](https://user-images.githubusercontent.com/25306585/172202818-a6add087-db60-4735-8409-ab7c74002d39.png)
![recaf_recaf](https://user-images.githubusercontent.com/25306585/172202839-aea4f1ed-a7d7-4987-be82-a3e9b56d5ce2.png)
![recaf_cmd2](https://user-images.githubusercontent.com/25306585/172202850-fe9fe04b-d78a-41e1-9e33-c0081d9b052e.png)

Here's the situation: what I executed, what the window looks like, what's shown after closing the window,

**Comment by xxDark** [comment]
Does it work if you start with JDK 8?

**Comment by RibozymeR** [comment]
No, with Java 1.8.0_51 I get the same problem, with an actual exception
```
18:35:08.621 [main] ERROR: Failed to load attach library.
java.io.FileNotFoundException: Could not locate tools.jar
        at me.coley.recaf.util.Natives.loadAttach(Natives.java:48)
        at me.coley.recaf.Recaf.main(Recaf.java:50)
```
(After that, it says Recaf version, Java version, and "Loading configuration", with no more output after that)

**Comment by xxDark** [comment]
tools.jar is optional and not requires for recaf's work
Check your graphics drivers, and try running Recaf with `-Dprism.debug=true`

**Comment by RibozymeR** [comment]
Awesome, thank you, that did it! Running Reacf with `-Dprism.debug=true` made it work, and now it even works again when I run it without that option, with both Java 8 and Java 17.

**Comment by Col-E** [comment]
> and now it even works again when I run it without that option, with both Java 8 and Java 17.

???????????

I mean, great! But, why? how? 🤔
