### ISSUE TITLE
[Question] How to add package to .class file?

### ISSUE THREAD

**Issue by iocmet** [Col-E/Recaf#549]
I have class file and i need access it from java app but it obfuscated and it package removed (it located in default package) and i can access it only from same default package if i add it to classpath but i can't use default package, is there a way to add a package to a class?
![image](https://user-images.githubusercontent.com/63492966/175770634-cd833802-f7ee-4eab-90ba-8f25f279a94d.png)

**Comment by Col-E** [comment]
Rename the class to `mypackage/goes/here/bdw`.

You can right click the class name in the tree on the left, or in the decompiled code _(if the code is parsable by JavaParser)_.

Do be aware, you only have this single class open in Recaf. If you rename it like this, references to this class will still be to the old name which points to the default package. If this is part of a larger jar, load the jar then rename the class.
