### ISSUE TITLE
Addition of void temp method to edited class

### ISSUE THREAD

**Issue by olalekaneboda** [Col-E/Recaf#55]
**Describe the bug**
Recaf is adding the following method to any edited class when exporting
**void temp();**
Hence you get this error when you try to run the class
**java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file**

**Comment by Col-E** [comment]
I'll fix this after class: Should be an issue around https://github.com/Col-E/Recaf/blob/867ee4bea8bcb1113edce9feedf76cea1a9d88e9/src/me/coley/recaf/ui/FxWindow.java#L441

**Comment by Col-E** [comment]
Actually it was caused due to a stupid copy/paste mistake I did. Fixed in c43d9d8a4bf9ef42e2ec0d0fe2d9eb88b9cc8bdb

**Comment by olalekaneboda** [comment]
Ok thanks for the prompt response
Great toolkit!!!
