### ISSUE TITLE
Font changes in tree view

### ISSUE THREAD

**Issue by FlowArg** [Col-E/Recaf#554]
**Describe the bug**

> The font of some items in the tree view changes.

**To Reproduce**

1. Open Recaf 2.x
2. Load any jar. For the example I choose recaf.jar
3. Write repeatedly "a" in the search bar.
4. The font of some items (name of the jar and "files" entry) changes (enable / disable monospace) each time you write in the search bar a character.
5. If you open/close the "files" entry for instance, the font also changes.

NOTE : At some point, the police no longer change.

Operating system : Arch Linux with KDE Plasma
Java Version : 17 (OpenJDK Azul Zulu) but the bug also "works" with Java 8
Recaf version : 2.21.13

**Video**
I made a video to show the bug :

https://user-images.githubusercontent.com/52298108/176908569-b450808a-bcf8-4c0b-9747-a8799ab9f27b.mp4

**Comment by Col-E** [comment]
Closing, re-open or make a new issue if it occurs on 4.X
