### ISSUE TITLE
Unable to generate missing classes

### ISSUE THREAD

**Issue by rikka0w0** [Col-E/Recaf#555]
I was trying to edit a java8 jar. The jar has many dependencies that are hard to collect. I saw there is a "Generate missing classes" option in the Config dialog, but even if I enabled it explicitly, when I edited the java code and hit ctrl+s, it still complains about "package xxx does not exist" and "cannot find symbol". Is there any limitation of this feature?

**Comment by Col-E** [comment]
The `generate missing classes` is done via a slightly modified version of [JPhantom](https://github.com/gbalats/jphantom). Its pretty cool, but unfortunately can be a bit unstable at times. Plus, its behavior [isn't even deterministic](https://github.com/gbalats/jphantom/blob/d55b16808f980c167fff91c493587927c6fe9361/src/main/java/org/clyze/jphantom/constraints/solvers/BasicSolver.java#L213). There is an element of randomness to it which means it sometimes will not work at all, but will work when you try the exact same thing again later.

Our modified version attempts to [use some insights into the input to speed up computation time](https://github.com/Col-E/jphantom/blob/master/src/main/java/org/clyze/jphantom/constraints/solvers/BasicSolver.java#L191). But sometimes the optimal guess order cannot yield a solution and we fall-back to the original random behavior.

We want to eventually migrate to something that does not rely at all on random order.

**Comment by rikka0w0** [comment]
That's for the information. My modifications are now done by manual byte code editing.

**Comment by Col-E** [comment]
Closing old 2.X tickets, but also we're still using JPhantom in 4.X at the moment, but with new work done in Reconstruct we should be able to migrate away soon.
