### ISSUE TITLE
Stuck on loading file

### ISSUE THREAD

**Issue by CXVUSER** [Col-E/Recaf#568]
Stuck on loading file

![image](https://user-images.githubusercontent.com/61128558/182001947-a5f905b5-1816-40f4-8449-902fdc28cd2c.png)

cpu usage 0

java: jdk-11.0.6

recaf snapshot 14

**Comment by xcfrg** [comment]
You ignored the github template
Sample?
Is there a stacktrace?

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/182002495-f65f5e13-8f42-4379-a715-deab198429f6.png)

works fine for me, JDK 11, Recaf snapshot 14

**Comment by CXVUSER** [comment]
java -jar .\recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies_14.jar
08:08:18,911 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:08:19,240 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:08:19,273 |-ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [filter] of type [me.coley.recaf.util.logging.LoggingFilter] java.lang.ClassNotFoundException: me.coley.recaf.util.logging.LoggingFilter
        at java.lang.ClassNotFoundException: me.coley.recaf.util.logging.LoggingFilter
        at      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at      at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at      at ch.qos.logback.core.util.Loader.loadClass(Loader.java:120)
        at      at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.begin(NestedComplexPropertyIA.java:102)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at      at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:64)
        at      at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:134)
        at      at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at      at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at      at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at      at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at      at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at      at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at      at me.coley.recaf.util.logging.Logging.lambda$get$1(Logging.java:46)
        at      at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
        at      at me.coley.recaf.util.logging.Logging.get(Logging.java:46)
        at      at me.coley.recaf.Main.<clinit>(Main.java:30)
08:08:19,278 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:08:19,350 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to TRACE
08:08:19,350 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
08:08:19,352 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:08:19,368 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5a8e6209 - Registering current configuration as safe fallback point
08:08:19,925 |-INFO in ch.qos.logback.core.FileAppender[null] - File property is set to [C:\Users\vzheg\AppData\Roaming\Recaf\log-2022-07-31.txt]
08:08:19.938 [Main/main] TRACE: Compressing 0 old log files
08:08:20.207 [Recaf/main] DEBUG: Initialize: Recaf-3.0.0-SNAPSHOT (fe9e30d3929ab9fc19ea1e3df8dd5cfdd2918140)
08:08:20.214 [Recaf/main] DEBUG: java.home = E:\MyDocs\Desk\ToolsFx-1.13.0-withjre-win-x64\jre
08:08:20.215 [Recaf/main] DEBUG: java.version = 17.0.3
08:08:20.215 [Recaf/main] DEBUG: java.vm.vendor = Azul Systems, Inc.
08:08:20.216 [Recaf/main] DEBUG: java.vm.version = 17.0.3+7-LTS
08:08:20.216 [Recaf/main] DEBUG: os.arch = amd64
08:08:20.216 [Recaf/main] DEBUG: os.bitness = 64
08:08:20.217 [Recaf/main] DEBUG: os.name = Windows 11
08:08:20.218 [Recaf/main] DEBUG: os.version = 10.0
08:08:20.504 [AccessPatcher/main] DEBUG: Opening access to all packages
08:08:20.671 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
08:08:20.782 [JFXInjection/main] INFO : Checking local cache for JavaFX dependencies...
08:08:20.835 [JFXInjection/main] INFO : JavaFX classpath injection complete
08:08:21.086 [Lang/main] INFO : Loaded translations 'cs_CZ'
08:08:21.116 [Lang/main] INFO : Loaded translations 'de_DE'
08:08:21.185 [Lang/main] INFO : Loaded translations 'en_US'
08:08:21.191 [Lang/main] INFO : Loaded translations 'zh_CN'
08:08:21.272 [ClsSet/Recaf misc-0] DEBUG: Clst file loaded in 635ms, classes: 4750, methods: 48272
08:08:21.378 [ConfigRegistry/main] DEBUG: Register config container: conf.display
08:08:21.414 [ConfigRegistry/main] DEBUG: Register config container: conf.editor
08:08:21.426 [ConfigRegistry/main] DEBUG: Register config container: conf.binding
08:08:21.428 [ConfigRegistry/main] DEBUG: Register config container: conf.dialog
08:08:21.398 [ProcessKotlinInternals/Recaf misc-0] DEBUG: Kotlin Intrinsics class not found
08:08:21.430 [ConfigRegistry/main] DEBUG: Register config container: conf.assembler
08:08:21.438 [ConfigRegistry/main] DEBUG: Register config container: conf.compiler
08:08:21.440 [ConfigRegistry/main] DEBUG: Register config container: conf.decompiler
08:08:21.443 [ConfigRegistry/main] DEBUG: Register config container: conf.export
08:08:21.445 [ConfigRegistry/main] DEBUG: Register config container: conf.recent
08:08:21.446 [ConfigRegistry/main] DEBUG: Register config container: conf.ssvm
08:08:21.453 [ConfigRegistry/main] DEBUG: Register config container: conf.plugin
08:08:21.460 [ConfigRegistry/main] DEBUG: Loading stored config containers
08:08:21.538 [Lang/main] WARN : Tried to set translations to 'ru_RU', but no entries for the translations were found!
Jul 31, 2022 8:08:21 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3c153a1'
08:08:23.851 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'Java'
08:08:23.853 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'Java Bytecode'
08:08:23.870 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'Dalvik Bytecode'
08:08:23.871 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'XML'
08:08:23.872 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'Manifest'
08:08:23.878 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'CSS'
08:08:23.884 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'JSON'
08:08:23.886 [Languages/JavaFX Application Thread] DEBUG: Registering language syntax for 'Properties'
08:08:25.116 [JFXUtils/JavaFX Application Thread] DEBUG: JavaFX platform initialized from: javafx.application.Platform
08:08:32.633 [ContainerContentSource/Recaf misc-0] INFO : Reading from file: H:\Programming\UTILS\JAVA\JByteMod-1.8.2.jar

**Comment by CXVUSER** [comment]
`Fixed it package package me.coley.recaf.util.threading`

`package me.coley.recaf.util.threading;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ThreadFactory;

/**
 * Wrapper for {@link ExecutorService} with easier inline configuration.
 *
 * @author Matt Coley
 */
public class ThreadPoolFactory {
	private static final int MAX = Runtime.getRuntime().availableProcessors();

	/**
	 * @param name
	 * 		Thread pool name.
	 *
	 * @return {@link Executors#newFixedThreadPool(int)}.
	 */
	public static ExecutorService newFixedThreadPool(String name) {
		return newFixedThreadPool(name, true);
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 * @param daemon
	 * 		Flag to set created threads as daemon threads.
	 *
	 * @return {@link Executors#newFixedThreadPool(int)}.
	 */
	public static ExecutorService newFixedThreadPool(String name, boolean daemon) {
		return newFixedThreadPool(name, MAX, daemon);
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 * @param size
	 * 		Thread pool size.
	 * @param daemon
	 * 		Flag to set created threads as daemon threads.
	 *
	 * @return {@link Executors#newFixedThreadPool(int)}.
	 */
	public static ExecutorService newFixedThreadPool(String name, int size, boolean daemon) {
		return Executors.newFixedThreadPool(MAX, new FactoryImpl(name, daemon));
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 *
	 * @return {@link Executors#newCachedThreadPool()}.
	 */
	public static ExecutorService newCachedThreadPool(String name) {
		return newCachedThreadPool(name, true);
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 * @param daemon
	 * 		Flag to set created threads as daemon threads.
	 *
	 * @return {@link Executors#newCachedThreadPool()}.
	 */
	public static ExecutorService newCachedThreadPool(String name, boolean daemon) {
		return Executors.newCachedThreadPool(new FactoryImpl(name, daemon));
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 *
	 * @return {@link Executors#newSingleThreadExecutor()}.
	 */
	public static ExecutorService newSingleThreadExecutor(String name) {
		return newSingleThreadExecutor(name, true);
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 * @param daemon
	 * 		Flag to set created threads as daemon threads.
	 *
	 * @return {@link Executors#newSingleThreadExecutor()}.
	 */
	public static ExecutorService newSingleThreadExecutor(String name, boolean daemon) {
		return Executors.newSingleThreadExecutor(new FactoryImpl(name, daemon));
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 *
	 * @return {@link Executors#newScheduledThreadPool(int)}.
	 */
	public static ScheduledExecutorService newScheduledThreadPool(String name) {
		return newScheduledThreadPool(name, true);
	}

	/**
	 * @param name
	 * 		Thread pool name.
	 * @param daemon
	 * 		Flag to set created threads as daemon threads.
	 *
	 * @return {@link Executors#newScheduledThreadPool(int)}.
	 */
	public static ScheduledExecutorService newScheduledThreadPool(String name, boolean daemon) {
		return Executors.newScheduledThreadPool(MAX, new FactoryImpl(name, daemon));
	}

	private static class FactoryImpl implements ThreadFactory {
		private final String name;
		private final boolean daemon;
		private int tid = 0;

		public FactoryImpl(String name, boolean daemon) {
			this.name = name;
			this.daemon = daemon;
		}

		@Override
		public Thread newThread(Runnable r) {
			Thread thread = new Thread(r);
			thread.setDaemon(daemon);
			thread.setName(name + "-" + tid++);
			return thread;
		}
	}

}
`

**Comment by CXVUSER** [comment]
me.coley.recaf.util.threading.ThreadPoolFactory.java

private static final int MAX = Math.max(1, Runtime.getRuntime().availableProcessors() - 2); to
private static final int MAX = Runtime.getRuntime().availableProcessors();

Fixed my problem

**Comment by xxDark** [comment]
Fixed with https://github.com/Col-E/Recaf/commit/6892e5e24ee72345cfdb9175c1473f1550b0b62a
