### ISSUE TITLE
Add Show synthetics

### ISSUE THREAD

**Issue by CXVUSER** [Col-E/Recaf#573]
Add Show synthetics option for decompilers on dev3

**Comment by xxDark** [comment]
![image](https://user-images.githubusercontent.com/19853368/182036474-6b44a861-5786-40ab-b410-b2efe7c8672f.png)

**Comment by CXVUSER** [comment]
> ![image](https://user-images.githubusercontent.com/19853368/182036474-6b44a861-5786-40ab-b410-b2efe7c8672f.png)

not working for Procyon dec

**Comment by xxDark** [comment]
Fixed in https://github.com/Col-E/Recaf/commit/c8e07d4e08354c1be847afdf4d31cc29ffe15d5b
