### ISSUE TITLE
add open as encoding  menu

### ISSUE THREAD

**Issue by MisterChangRay** [Col-E/Recaf#581]
## Feature_Name

open jar file, some file need to edit;
like:
![image](https://user-images.githubusercontent.com/16421384/182357573-c523d7b2-4230-4552-859b-045d591d7452.png)

but only ascii file can be directy edit, gbk or anther encoding showing like below:

![1659437623344](https://user-images.githubusercontent.com/16421384/182358174-2af8fcf4-a749-4f63-9794-19232c3fb47a.png)

hope add encoding menu to this 

![image](https://user-images.githubusercontent.com/16421384/182358427-18b06e3f-c476-4c6c-b1c7-0ddc0de1ead6.png)

**Comment by Col-E** [comment]
Probably would better be implemented as a config value rather than cluttering the _"open as"_ menu.

**Comment by Amejonah1200** [comment]
I propose of also adding a possibility for changing the encoding in an IntelliJ-like bottom bar. We could also add line breaks, and stats.

**Comment by Col-E** [comment]
In 4.X we now have a system that acts kind of like auto-detection of text file encodings. If a similar problem occurs in 4.X we can create a new issue.
