### ISSUE TITLE
How to ignore errors to save

### ISSUE THREAD

**Issue by idolf** [Col-E/Recaf#589]
I want to modify the minecraft code, but I can't save it because there are minecraft's own functions in the code, and I want to be able to save the bytecode in any case

**Comment by Amejonah1200** [comment]
Hey, are you using the assembler then? For (re-)compilation, the libraries (which you can obtain fairly easy: just use your mc jar) are needed.

**Comment by Col-E** [comment]
1. Refer to section on phantoms: https://www.coley.software/Recaf-documentation/use-workspace.html#phantom-resource
    - We use the standard Java compiler `javac` to recompile code, so _"missing"_ data needs to be supplied
    - We use [JPhantom](https://github.com/gbalats/jphantom) to generate _"missing"_ data dynamically
    - JPhantom isn't perfect and fails sometimes. If that happens you have two options:
        - You can supply the minecraft client / libraries yourself.
        - You can make your changes with the assembler 
2. No, you cannot _ignore_ errors. They are ***errors*** not _warnings_
