### ISSUE TITLE
Recaf cannot be loaded into a class with a long package name

### ISSUE THREAD

**Issue by luiox** [Col-E/Recaf#600]
**Describe the bug**
When I try to open a confused jar, the jar has an extremely long package name so that recaf cannot display the package and the classes in it

> A clear and concise description of what the bug is.
For example,a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/lIIlIlIlll.class
The classes in such packages will be ignored by recaf.
When I try to open it, the command line or output an error message.
22:03:29.813 [ForkJoinPool-1-worker-9] DEBUG: Attempting to patch invalid class 'a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/lIIlIlIlll.class'
22:03:29.815 [ForkJoinPool-1-worker-9] DEBUG: Illegal class patching success!
Therefore, I can't see the package a in recaf.

**To Reproduce**

1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

> A clear and concise description of what the bug is.

**To Reproduce**

1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Exception**

If applicable, add the exception/stacktrace.
```
stacktrace goes here
```

**Screenshots**

**Comment by xxDark** [comment]
What Recaf version are you using?

**Comment by luiox** [comment]
I use the latest version 2.21.13 in the release.

**Comment by Col-E** [comment]
Long names and illegal bytecode patching work with the set of obfuscation samples I have on hand. Could you provide a reproducible sample?

Also you may want to check out the snapshot releases of 3X (https://github.com/Col-E/recaf-3x-issues/) and see if it handles it better.

**Comment by luiox** [comment]
[demo.zip](https://github.com/Col-E/Recaf/files/9536428/demo.zip)
Due to the limitation of file format, I changed jar to zip. This is just a case. The file that I said cannot be loaded is a in the jar. When you try to open it, you will find that the package name is very long.

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/189380193-fe0027b1-d60e-42a4-b152-8763d283c5d1.png)

When the package directory/name is long recaf will truncate it using `...` as seen in the image above. I don't see any issues here.

**Comment by luiox** [comment]
OK, I changed a computer and tried again. Now you can open it. Thank you.
