### ISSUE TITLE
Search and Replace

### ISSUE THREAD

**Issue by byposeidon** [Col-E/Recaf#602]
Do you plan to add search and replace feature for the Recaf?
That would be awesome.

**Comment by Amejonah1200** [comment]
Hey, are you talking about Strings or Source Code? The first would be a good idea, the latter isn't possible (if we aren't talking about jvm instructions)

**Comment by byposeidon** [comment]
> Hey, are you talking about Strings or Source Code? The first would be a good idea, the latter isn't possible (if we aren't talking about jvm instructions)

Strings.

**Comment by Amejonah1200** [comment]
If this feature is gonna be implemented, it will be for 3x. Stay tuned. Shouldn't be this difficult tho. 🤔

**Comment by Col-E** [comment]
Been done in 4x branch for a while and even supports a number of other enhancements like regex group replacement

https://github.com/Col-E/Recaf/assets/21371686/75c32b5b-beb1-472e-bedb-03d447faf673
