### ISSUE TITLE
Cannot virtualize app

### ISSUE THREAD

**Issue by bojanv55** [Col-E/Recaf#613]
Been asking this previously, but maybe I'm doing something wrong here. I compiled the javaFX app with java 17, and trying to virtualize it in recaf. Am I doing something wrong, or is it not possible?

This is my compiled JAR:

[debugit.zip](https://github.com/Col-E/Recaf/files/9846419/debugit.zip)

And this is the process I try:

![recaf_run](https://user-images.githubusercontent.com/1422698/197389642-93907662-ebee-40b5-8884-278ea66413fa.gif)

**Comment by Nowilltolife** [comment]
SSVM is basically a jvm, so it cannot access the natives as it implements all the native backend in java, unless you want to create a pr and implement the javafx backend it cannot run javafx applications

**Comment by Col-E** [comment]
Closing, as @Nowilltolife has explained the issue.
