### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by itsFrag** [Col-E/Recaf#618]
Im trying to start the software and i have java 11 and it doesnt work

> it says there is a command which is non existing and its a jar file and thats probs the issue but idk how i change the file and into what

**To Reproduce**

1. Download the file as a jar
2. go to downloads 
3. try to open the file

**Screenshots**
[
![Screenshot 2022-11-08 202127](https://user-images.githubusercontent.com/117772019/200655956-72ae90de-9df3-4e03-b32c-112a5f62bb3b.png)
](url)
it says java cant be downloaded even tho i have java 11 installed and there is a command which doesnt excists

**Comment by xxDark** [comment]
This is a system error and not displayed by Recaf

**Comment by Amejonah1200** [comment]
How did you install Java? Is `java -version` working?

**Comment by itsFrag** [comment]
java -version is working. i downloaded it from oracle and it legit works fine and how can i go around the system error

**Comment by Amejonah1200** [comment]
Use `java -jar path\to\jar`.

**Comment by Col-E** [comment]
As others have stated, this message isn't related to Recaf specifically.

Run the Recaf jar with `java -jar` using the appropriate version of Java. The results displayed in the terminal should be more specific than whatever this dialog window says.

**Comment by itsFrag** [comment]
thx i got recaf opend through cmd thx alot <3
