### ISSUE TITLE
Parser breaks whenever Java Keyword is used as a class name, field name, or method name

### ISSUE THREAD

**Issue by mdo992** [Col-E/Recaf#620]
Parsing the code below in Recaf fails because a Java Keyword is being used as the class name:

```java
public class while {
}
```

This also happens when you use a Java Keyword for field names, method names, and package names.

Please let me know if this needs to be reported to javaparser instead.

**Comment by xxDark** [comment]
JavaParser does not play well on obfuscated code, consider using assembler instead.

**Comment by Col-E** [comment]
As xxDark said, there's not much we can really do about it. JavaParser is not made by us, and handling keywords as identifiers is a tricky business. You can ask them about it but I doubt they offer much.

This is why Recaf has an assembler _(which was around first anyways)_. Its been improved on the 3X branch, which is where all our support is currently going into.
