### ISSUE TITLE
Exported file doesn't contain made changes.

### ISSUE THREAD

**Issue by jurian112211** [Col-E/Recaf#624]
Helllo, I edited a .jar file and changed the value from a boolean, then I exported the program but the exported jar file didn't contain my changes...
The boolean didn't change, any idea about this?

**Comment by Amejonah1200** [comment]
Well, when you pressed Ctrl+S, did it blink red or green?

**Comment by jurian112211** [comment]
It doesn't blink?

**Comment by jurian112211** [comment]
I just readed this page: https://www.coley.software/Recaf-documentation/use-workspace.html
I didn't know about the need to save the changes but it still doesn't work when I save & export.

**Comment by jurian112211** [comment]
Any thoughts on resolving this?

**Comment by jurian112211** [comment]
Oh, just noticed that there are some errors.
The program already works fine though, it doesn't recognize a library so therefore it gives errors

**Comment by Nowilltolife** [comment]
No. It is definitively not possible to disable error checking as javac cannot compile something which has faulty / invalid inputs. If you want a less strict environment to edit the program please refer to using the assembler which usage is outlined here: https://www.coley.software/Recaf-documentation/use-edit-via-bytecode.html

**Comment by jurian112211** [comment]
Alright, thank you :)
