### ISSUE TITLE
Is there a way for me to save .jar file changes with erros inside?

### ISSUE THREAD

**Issue by Semifyy** [Col-E/Recaf#626]
Hello I'm wondering if I can edit the .jar file and save it with errors inside? When I import the .jar file and save it without any changes or even if I change a single message, I get tons of errors so can I save it with errors or I have to manually find a way to fix it?

**Comment by Amejonah1200** [comment]
Use Assembler: https://www.coley.software/Recaf-documentation/use-assembler.html
