### ISSUE TITLE
Code isn't working plz help

### ISSUE THREAD

**Issue by MajonezaEU** [Col-E/Recaf#628]
Also, I use Recaf but it's says that the code doesn't work and I can't save but I didn't change anything from before and it worked 2 days ago wtf why

**Comment by Col-E** [comment]
If you can't give specific details we can't help you.

**Comment by MajonezaEU** [comment]
Ok yeah so I found out the problem isn't just with jar files but something with recaf because every file I put into recaf it says that there are errors I tried with 4 different that worked 2 days ago normally

**Comment by MajonezaEU** [comment]
I also tried reinstalling it but It doesn't change anything

**Comment by MajonezaEU** [comment]
![image](https://user-images.githubusercontent.com/103072326/209428932-38dc3f3b-35fb-479b-95b2-8947c4d2652e.png)

**Comment by MajonezaEU** [comment]
And the jar files still work like normal just recaf it's diving me errors

**Comment by Col-E** [comment]
> And I don't care that it shows me error but the problem is that I can't save code because of them

I'm gonna let you think about that sentence for a bit.
