### ISSUE TITLE
JADX ERROR: Failed to decode insn: 0x0017: INVOKE_CUSTOM 

### ISSUE THREAD

**Issue by billpeace** [Col-E/Recaf#631]
JADX ERROR: Failed to decode insn: 0x0017: INVOKE_CUSTOM 

jadx.core.utils.exceptions.JadxRuntimeException: 'invoke-custom' instruction processing error: Failed to process invoke-custom instruction: CallSite{[{ENCODED_METHOD_HANDLE: INVOKE_STATIC: Ljava/lang/invoke/LambdaMetafactory;->altMetafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;}, apply, {ENCODED_METHOD_TYPE: ()Lcom/baomidou/mybatisplus/core/toolkit/support/SFunction;}, {ENCODED_METHOD_TYPE: (Ljava/lang/Object;)Ljava/lang/Object;},

**Comment by Col-E** [comment]
Problems with decompilers should be opened in their respective libraries.

You can find JADX here: https://github.com/skylot/jadx
