### ISSUE TITLE
SRG mapping's PK aren't applied

### ISSUE THREAD

**Issue by HowardZHY** [Col-E/Recaf#633]
My SRG mapping contain this:

PK: net/minecraft/server/v1_8_R3 net/minecraft/server

and package net/minecraft/server/v1_8_R3 classes won't remap to net/minecraft/server

**Comment by Col-E** [comment]
Will be done in [3x](https://github.com/Col-E/recaf-3x-rewrite-temp/commit/f7a161f1d877238fda0fa539cf95ce6f99cf6d3b) once that work gets copied over to this repo
