### ISSUE TITLE
Auto Generated Bug?

### ISSUE THREAD

**Issue by none283** [Col-E/Recaf#638]
**Describe the bug**

I just opened a jar file, then press Ctrl + S to save, after that, Recaf found error?

**To Reproduce**

1. Open sample a jar file (https://www.curseforge.com/minecraft/mc-mods/custom-player-models/download/4378446)
2. Navigate to package com.tom.cpm.shared.editor.Exporter;
3. Do nothing (Not edited or touched anything)
4. Pressed Ctrl + S
5. And got error?

**Screenshots**
Before Ctrl + S
![Screenshot 2023-03-04 143508](https://user-images.githubusercontent.com/61675554/222898170-cfe1c6c2-2b39-4595-8a4c-9d2206d42081.png)

After Ctrl + S
![Screenshot 2023-03-04 143527](https://user-images.githubusercontent.com/61675554/222898194-b5097c5e-c9e3-4beb-8b8f-2e145aa107be.png)

**Comment by none283** [comment]
My aim is to add a simple function to this jar file, but when i add it and save it with Ctrl + S, Recaf gives error, then I tried adding nothing and pressing Ctrl + S, Recaf still says above error

**Comment by Col-E** [comment]
1. Decompiler output is not something we handle. Recaf bundles multiple decompilers and offers multiple ways to make changes. For simple cases, you can recompile the decompiled code with `Control + S`. For more cases where that does not work, you use the assembler. This is explained in the docs which you are prompted to read when opening Recaf for the first time.

2. The error message is quite clear and easy to resolve. The variable `cos` is already defined in that method. change the name so it does not conflict.
