### ISSUE TITLE
Can't fix "can't find symbol" error

### ISSUE THREAD

**Issue by thepen2** [Col-E/Recaf#639]
You folks have obviously put an enormous amount of thought, time and labor into creating this resource.  Currently have what I believe is the latest version, 2.21.13-J8.

But it's just not working for me.

I load a jar file I need to patch, but when I try to make a change and Ctrl-S it throws a "can't find symbol" error, related to import org.springframework.transaction.annotation.Propagation

OK, so I highlight the original jar file in the right column after loading it into your program, click on "add sources" and load the CORRECT jar file (for example, spring-tx-5.2.0-RELEASE..jar) which contains the correct package path above.  I have confirmed this by looking inside the jar file.  I have further confirmed that the major version number is a match.

Still the same problem.

Is there no way to SEE what sources Recaf THINKS it has loaded to make sure of that much.? Curiously, if I load a later source of the same jar (major version 61) SOMETIMES your program complains about that, but only sometimes.

Now what??

Peace,

Pen

**Comment by xxDark** [comment]
Are you sure that you are pressing the correct button? Please try reading [this](https://www.coley.software/Recaf-documentation/use-editing.html) first.

**Comment by thepen2** [comment]
Dear xxDark

Thank you so much for your most speedy comment.

Yes, I have read that page.  What do mean by the correct "button?"  The procedure given is to right click on the name of the original jar, then click on "Add sources" (the context pulldown menu) and then I select the jar file of the additional source and then "Open" (button in Windows file selector window).  I might mention I'm working in Win X64.

The fact that Recaf SOMETIMES complains (upon Ctrl-S) about a jar file that is NOT the correct major version would seem to confirm that it at least thinks it is loading something on occasion by doing what I describe above.

Peace,

Pen

**Comment by xxDark** [comment]
I assume that this issue is solved, re-open it again if you encounter that problem again.
