### ISSUE TITLE
Recaf loads large Jar file slowly

### ISSUE THREAD

**Issue by zwb1988** [Col-E/Recaf#64]
[INFO:6/17/18 12:16 PM] Adding method hierarchy
[INFO:6/17/18 12:23 PM] Finished generating inheritence hierarchy

It took nearly 7 mins to load all methods hierarchy on the machine. 
This wasn't the issue prior in v1.3.

The jar file contains approximately 1400+ class files.

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/41504789-1570964c-71c8-11e8-9e58-fa6ab9c776b8.png)

Do you have this option enabled? If so you can disable it and this will skip the hierarchy generation. The option should be off by default.

**Comment by zwb1988** [comment]
I didn't touch that option when I launch the new version in a new folder without any previous config files. I've checked that option again and it is turned off in the UI. 

A correction for my previous statement, that there are 4000+ classes in my jar file. I tried to open it in v1.2.3, it's lightning fast. But the problem persists in the 1.3.0

**Comment by Col-E** [comment]
Oh opps, looks like the 1.3.0 release jar doesn't check for the option... I'll fix that in a second.

**Comment by Col-E** [comment]
Fixing a bug and changing an `O(n)` operation into an `O(1)` operation should greatly improve performance with this feature. I'll post a release soon _(But you can also DL the source and compile via maven to get it now)_

**Comment by Col-E** [comment]
207758e42e2c4157c818f83a4c86239009112269 You can now multi-thread the linked method renaming feature. By multi-thread, I mean that the process is technically single-threaded but the actual process of generating maps is threaded so it can get done faster. The default is 1, I've bumped it up to 4 and the performance boost is very noticeable. 

In the future perhaps I'll have this process parallel to the main thread.
