### ISSUE TITLE
Typo in documentation: Assembler: Common errors

### ISSUE THREAD

**Issue by airvzxf** [Col-E/Recaf#640]
There is a typo in “Assembler: Common errors”, subsection “Cannot pop operand off an empty stack”, word “frrom” needs to be fixed to “from”.

https://github.com/Col-E/Recaf/blob/3877b1a840b0fd8bfc4c3b655f5f9e080e621f65/docs/doc-edit-assembler-errors.html#L136

**Comment by Col-E** [comment]
Those doc files are currently unused. If you click the documentation link in the project URL it redirects to https://www.coley.software/Recaf-documentation/
