### ISSUE TITLE
Linux: agent-1.x.x.jar not found

### ISSUE THREAD

**Issue by airvzxf** [Col-E/Recaf#641]
**Describe the bug**

> I am using Arch Linux, also I cloned the repository from GitHub. When I try to open the attach window it is disable. I track with logs the secuences and the problems is about the missing file `agentPath: /home/wolf/.config/Recaf/agent/agent-1.3.4.jar`. I wonder how to generate the `agent-1.3.4.jar` since I ran all the gradle options?
> 
> Arch Linux:
> `Linux MSIGT73EVR7RF 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux`

**To Reproduce**

1. Navigate to 'File > Attach to remote'
2. The window with all the Java processes is disabled.

**Exception**

If applicable, add the exception/stacktrace.
```
04:39:46.194 [AttachPane/JavaFX Application Thread] INFO : private void extractAgent()
04:39:46.242 [AttachPane/JavaFX Application Thread] INFO : agentPath: /home/wolf/.config/Recaf/agent/agent-1.3.4.jar
04:39:46.258 [AttachPane/JavaFX Application Thread] INFO : Files.isRegularFile(agentPath): false
04:39:46.274 [AttachPane/JavaFX Application Thread] INFO : agentPath.getFileName(): agent-1.3.4.jar
04:39:46.288 [AttachPane/JavaFX Application Thread] INFO : Directories.getAgentDirectory(): /home/wolf/.config/Recaf/agent
04:39:46.297 [AttachPane/JavaFX Application Thread] DEBUG: Extracting agent jar to Recaf directory: agent-1.3.4.jar
```

**Screenshots**

![Recaf application running](https://user-images.githubusercontent.com/831380/229099536-62d2ebb3-0973-44b7-9d84-527fb125f048.png)

![Recaf source code](https://user-images.githubusercontent.com/831380/229099541-ab2f7125-bc59-4336-8a8d-5b99b27da22b.png)

![Linux local directory searching for agent dot jar](https://user-images.githubusercontent.com/831380/229099543-8c2a076a-b8f0-406b-aabb-2098d8e8ccc3.png)

**Comment by airvzxf** [comment]
Sure, let me check this project https://github.com/Col-E/InstrumentationServer, and try to set up the Col-E/Recaf with the Col-E/InstrumentationServer jars.

**Comment by Col-E** [comment]
Problem in instrumentation server solved, I'll update the 3x snapshot in a little bit to include the changes 👍
