### ISSUE TITLE
Unable to "Edit with assembler" constructors

### ISSUE THREAD

**Issue by pv835** [Col-E/Recaf#646]
When I right click on class constructors there, there is no "Edit with assembler" menu item.
So I cant patch constructors.

**To Reproduce**
1. Open any class
2. Go to any constructor
3. Right click on it and look at popup menu
4. There is no "Edit with assembler" menu item

**Screenshots**
![image](https://github.com/Col-E/Recaf/assets/133887019/e827cf68-cc70-4b8f-af44-b86ae481ceaf)

**Comment by Col-E** [comment]
https://www.coley.software/Recaf-documentation/use-editing.html - Use the alternative UI modes for classes when situations like this occur.

There are a number of reasons why your specific case could have failed:

- JavaParser cannot resolve the parameter type of `MainClass`. As far as I can tell, its not part of your workspace. Just the `$Test` inner class is.
    - JPhantom can fail to regenerate missing types, preventing the missing type from being generated in the workspace.
- JavaParser fails to resolve constructor declarations of desugared inner classes _(I think it works, but there are other variables of concern here)_
