### ISSUE TITLE
when trying to save a edited file it gives a huge error

### ISSUE THREAD

**Issue by qwertqwertzuzu** [Col-E/Recaf#647]
**After editing the file I tried to save the changes but it just gives a huge error**

1. Open Reza
2. Edit anything
3. press keybind to save changes

https://media.discordapp.net/attachments/1102127424793231392/1111039533342003300/image.png?width=1088&height=614

**Comment by Col-E** [comment]
Relevant docs:

- https://www.coley.software/Recaf-documentation/use-edit-via-decompile.html
- https://www.coley.software/Recaf-documentation/use-workspace.html#phantom-resource

Editing decompiled code is a lossy process. If JPhantom isn't able to generate missing classes for some reason _(3rd party tooling issue)_ then you'll need to make your changes with the assembler instead.
