### ISSUE TITLE
Add the ability to edit bytecode even if decompilation is incomplete.

### ISSUE THREAD

**Issue by st1064870** [Col-E/Recaf#648]
The feature is mainly stated in the title. Using the latest version, I tried to edit the bytecode of a jar file where multiple anti debugging techniques that resulted in the failure of decompilation. Unfortunately, I wasn't able to achieve my goal. What do you think on implementing this feature? I think it will be very useful to have such a feature, since most of the classes that have been passed from an obfuscator are not able to be decompiled completely.

**Comment by Col-E** [comment]
You're missing the fact that Recaf has a bytecode assembler _in addition to the recompile feature_ and has multiple display modes if the decompilation is not legible or parsable.

Read the documentation.

**Comment by st1064870** [comment]
Of course I have read the documentation. But I didn't found somewhere to be mentioned on how to access the disassembler of the class apart from right clicking on the class which doesn't show the disassembler option when the class partially failed decompilation.

**Comment by Col-E** [comment]
https://www.coley.software/Recaf-documentation/use-modes.html
