### ISSUE TITLE
NullPointerException: Cannot invoke "me.coley.recaf.workspace.Workspace.getPrimary()" because the return value of "me.coley.recaf.control.gui.GuiController.getWorkspace()" is null

### ISSUE THREAD

**Issue by CrytoPal** [Col-E/Recaf#653]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Exception**

If applicable, add the exception/stacktrace.
```
stacktrace goes here
```

**Screenshots**

**Comment by Col-E** [comment]
Put some kind of details into the issue before hitting post
