### ISSUE TITLE
Please add support for XSRG mappings

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf#657]
## Feature_Name
XSRG MAPPINGS SUPPORT
Description of the feature
XSRG is a variant of SRG and is kinda widely used, in this application, i can;t load XSRG configs

**Comment by Col-E** [comment]
I need a sample or some documentation on the format

**Comment by neilhuang007** [comment]
[mappings.zip](https://github.com/Col-E/Recaf/files/12215545/mappings.zip)
there u go
