### ISSUE TITLE
Not Able to EDIT AND SAVE DECOMPILED CODE -ANDROID

### ISSUE THREAD

**Issue by banditAmit** [Col-E/Recaf#658]
<img width="1074" alt="image" src="https://github.com/Col-E/Recaf/assets/99014487/39733b7a-fef6-4695-8452-0d86b7a48155">

**Comment by Col-E** [comment]
Read the sections on editing here: https://www.coley.software/Recaf-documentation/use-editing.html

And to similar issues such as:

- #656
- #535
