### ISSUE TITLE
Creating new class methods behaves wierdly

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#669]
Open a .jar file, and then open a class within that jar.
Edit the assembly for a new method.
Try to create a new method, by prepending:
```
.method .private test ()V
A:
    aload this
    pop
    return
.end
```
This will give an error: `Cannot resolve usage of 'this' to end label!`
Now do the same, but postpend the method. 
It "works" to save the assembly.
Close the assembly.

Now inspect the decompilation of that class, and try to find that method...
It will not be there.
Now open the assembly again: The newly created method has vanished into nothingness.

**Comment by Col-E** [comment]
Closing as this has since been resolved in 4.X
