### ISSUE TITLE
Able to open Archives in Files

### ISSUE THREAD

**Issue by Amejonah1200** [Col-E/Recaf#683]
When working with ZIP/TAR/WAR Files, it would be quite handy to be able to open them as either new Workspace (either new window or in the current one) or add it in this workspace.

Must:
- [ ] Open nested Archives
  - [ ] New Workspace (new window or current one)
  - [ ] Add to Workspace

Also nice to have:
- [ ] Able to configure click action (as an addition to the context menu entry)
- [ ] Able to configure if it should open recursively:
 - [ ] When it's just nested, like TAR -> WAR -> JAR
 - [ ] Add all to workspace
- [ ] A new Category "Archives" (can be seen as an independent feature to add: "categorizing" files: images, archives, json...)
- [ ] Expanding directly in this workspace

**Comment by Col-E** [comment]
While not handled exactly like outlined in this issue, jar-in-jar support exists in 4.x
