### ISSUE TITLE
[SUGGESTION] Add an "Export as script / patch" option to the Modifications window

### ISSUE THREAD

**Issue by Xanax-C-137** [Col-E/Recaf#685]
I was thinking of this for a while, and it would be a pretty cool feature to easily and automatically patch a jar file that, for example, got a minor update with your previous patches.

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/commit/817aa24da25565a610479cdcda038a3210bd602b - A more proper patch-like system has been added to the 4.X API - UI pending
