### ISSUE TITLE
Better logo

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#69]
I kinda just threw this together during the rewrite. Something more professional _(but not too boring)_ would be nice.

**Current design**:
![logo](https://user-images.githubusercontent.com/21371686/42158985-34e49506-7dc0-11e8-8694-15345b1b220d.png)

**Comment by mirzazulfan** [comment]
Hi @Col-E ,, what about this logo?
![recaf](https://user-images.githubusercontent.com/36124339/48337554-d736ab80-e695-11e8-81b6-f217e9478da3.png)

**Comment by Col-E** [comment]
I like how the top-middle one has a faint gradient and is a light-on-dark. I'm not sure about the double ring design. I see how it works aesthetically, simply removing one of the rings would break the composition. But as a whole the pattern doesn't vibe with me. 

That being said I'm notoriously indecisive among my friends  ¯\\_(ツ)\_/¯

I'd like to hear what others have to say.

**Comment by nsknyc** [comment]
Good job! A bit of constructive criticism here, I think the logo is just a bit confusing. I do love the line approach though, its simplicity adds a bit more of a professional touch. Would it be ok to ask to see others with a similar touch?

**Comment by newUserRepo** [comment]
I think that at least one R inside a C would not be the best idea?

**Comment by Col-E** [comment]
New logo for now is a mix of the old logo and the Volkswagen logo aesthetics.

![logo-full](https://user-images.githubusercontent.com/21371686/59729767-f0946d00-920d-11e9-9f1b-1be0f02a4749.png)

Closing, but if you have interesting ideas/examples feel free to share.
