### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by duester** [Col-E/Recaf#71]
**Describe the bug**

While translating _en.json_ I've accidentally noticed that in the source code there are some references to strings missing in the resource file. Those are: 
- "ui.bean.class.extended.interfaces.name"
- "ui.bean.class.extended.innerclasses.name"
- "ui.bean.class.extended.innerclasses.name.tooltip"
- "ui.bean.class.extended.innerclasses.inner.tooltip"
- "ui.bean.class.extended.innerclasses.outer.tooltip",

probably some others.

**Comment by Col-E** [comment]
Treat them as if they don't exist. I thought I replaced them but I missed any references I'll fix that when I can.

For example I changed `ui.bean.class.extended.interfaces.name` to `ui.bean.class.interfaces.name`

**Comment by Col-E** [comment]
Removed the extended references.
