### ISSUE TITLE
Use Mappings cannot to anti obfuscation jar file

### ISSUE THREAD

**Issue by Vamco2022** [Col-E/Recaf#719]
I use the recaf to anti obfuscation the mincraft 1.20.1 jar file, but import the mapping text file, can't anti obfuscation it.

**Comment by Col-E** [comment]
What version of Recaf are you using, and what kind of mapping file are you trying to import?

**Comment by Vamco2022** [comment]
Use the version of recaf is 2.21.13-J8,  use the Proguard  for the jar file to anti obfuscation.
When me import the mapping file, the program will no response and flush,
but the codes is not anti obfuscation.

**Comment by Vamco2022** [comment]
> What version of Recaf are you using, and what kind of mapping file are you trying to import?
Use the version of recaf is 2.21.13-J8, use the Proguard for the jar file to anti obfuscation.
When me import the mapping file, the program is no response and flush,
but the codes is not anti obfuscation.

**Comment by Vamco2022** [comment]
Use the version of recaf is 2.21.13-J8, use the Proguard for the jar file to anti obfuscation.
When me import the mapping file, the program is no response and flush,but the codes is not anti obfuscation.
