### ISSUE TITLE
String replace

### ISSUE THREAD

**Issue by PandaHaxor** [Col-E/Recaf#73]
Please support String replace, thanks.

**Comment by Col-E** [comment]
Do you man like a mass automated string replace?

You can search for text, click the results then edit them there.

**Comment by PandaHaxor** [comment]
I have a much same string to edit.

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf-plugin-workspace/releases/tag/example-str-replace _(Includes usage details)_

I see you've closed the issue, but I've made the plugin if you wish to use it. Extract the zip to your `/plugins` folder adjacent to the recaf jar.

![image](https://user-images.githubusercontent.com/21371686/43362225-1d958e52-92b3-11e8-9f1a-a629789a169b.png)

**Comment by erxson** [comment]
update plugin, please
