### ISSUE TITLE
Recaf can't read the jar file

### ISSUE THREAD

**Issue by Gusandr** [Col-E/Recaf#733]
**Describe the bug**

Recaf can't read the jar file
Link to jar file: https://workupload.com/file/27xYB8xBNwW
(12 hours valid.)

**Exception**
// Decompiled with: CFR 0.152
// Class Version: 8
// ERROR: Failed to decompile 'org/ney/neyupcrystal damage/NeyUPCrystalDamage'|
**Screenshots**
![image](https://github.com/Col-E/Recaf/assets/125789471/84d9f914-230a-4af6-9dc4-2efc5857ff53)

**Comment by xxDark** [comment]
Recaf can read this file, decompiler can't.
Strip debug attributes with the option in the config, use other decompiler, and use new Recaf version.
