### ISSUE TITLE
Decompiled code with errors can't be edited through right clicking, but can be properly edited using the search menu

### ISSUE THREAD

**Issue by mcunlocked** [Col-E/Recaf#736]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

1. Open a class file with decompilation errors
2. Try to right click and bytecode edit (the menu shouldn't appear)
3. Open the search and find the value or piece of text to edit
4. Right click to bytecode edit
5. The editor should appear and you can edit and properly save the code.
6. Look at the decompiled code, the code should look the exact same as before, as if the edits weren't even made.
7. Export it, then look at it again and it should update

**Screenshots**

https://github.com/Col-E/Recaf/assets/146917292/a89ed86d-a402-44ce-9c7b-19d3212e5d5b

**Comment by Col-E** [comment]
2X: Change the class display mode - https://www.coley.software/Recaf-documentation/use-modes.html
3X: Use the side panel to interact with members when the code cannot be parsed into an AST

**Comment by Col-E** [comment]
Changing the title as this is normal behavior outlined in the documentation
