### ISSUE TITLE
Changes not being saved

### ISSUE THREAD

**Issue by Akhron** [Col-E/Recaf#738]
First of all i must say that i'm not experienced in java whatsoever, however what i'm trying to do is just so simple that i don't understand how it could be something i'm doing that is wrong.

I'm opening a .jar minecraft mod for 1.16.5, changing a single number from a "1" to a "3" (a 'ToolType' property) and exporting it out.
The changes simply do not save...

**Comment by Col-E** [comment]
If the decompiled code cannot be recompiled use the assembler, see the documentation: https://www.coley.software/Recaf-documentation/use-editing.html
