### ISSUE TITLE
Please tell me where is the vertue button in recaf 3.X and 4.X to remove reflection obfuscation

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf#744]
![image](https://github.com/Col-E/Recaf/assets/102778463/29b6a930-c3e3-4ea2-bfed-d92077ac4fb2)
found this in the author's video
but my recaf says this
![image](https://github.com/Col-E/Recaf/assets/102778463/c1ff5b7c-80ae-4d54-9b51-d60cba8d5446)
 please help

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/assets/21371686/9615ac0c-0539-4e28-87d7-a910d2ec00d8

Ensure SSVM is enabled in the settings. For 3X you should also specify the address of a JDK 8 location. If you don't it pulls class definitions from the current runtime which can confuse it. The version of SSVM used in 3X mostly targets Java 8, we've been working on adding support for back-end changes from JDK 8 --> JDK 11 for newer SSVM versions, but its a lengthy process.
