### ISSUE TITLE
recaf build script failed

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf#750]
cannot load the maven buildscript for 4.X series, here is the error
`A problem occurred configuring project ':recaf-ui'.
> Could not resolve all files for configuration ':recaf-ui:classpath'.
   > Could not resolve org.openjfx:javafx-plugin:0.1.0.
     Required by:
         project :recaf-ui > org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin:0.1.0
      > No matching variant of org.openjfx:javafx-plugin:0.1.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability org.openjfx:javafx-plugin:0.1.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'javadocElements' capability org.openjfx:javafx-plugin:0.1.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability org.openjfx:javafx-plugin:0.1.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability org.openjfx:javafx-plugin:0.1.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')`

**Comment by xxDark** [comment]
You are trying to build with JDK 8.
Use JDK 17 instead.

**Comment by Col-E** [comment]
xxDark is correct, read the message in your build failure logging.
