### ISSUE TITLE
Rethrows Missing in Decompiled code

### ISSUE THREAD

**Issue by 0xbadb0d00** [Col-E/Recaf#751]
**Describe the bug**

When you try to recompile a class that contains methods that rethrow to the caller an Exception, it generate the error:

`unreported exception <ExceptionClass>; must be caught or declared to be thrown`

The workaround is to modify manually the method declaration, by adding the throws instruction:

`public static Type MethodName(Parameters) throws ExceptionClass {`

**Comment by Col-E** [comment]
Can you provide a sample or be more specific with the description?

**Comment by Col-E** [comment]
Going to assume this is a decompiler issue, in which this is a 3rd party problem where the decompiler is not adding the thrown type to the method signature.
