### ISSUE TITLE
Decomile class with line number

### ISSUE THREAD

**Issue by sagasm** [Col-E/Recaf#753]
like jd-gui-duo:
![image](https://github.com/Col-E/Recaf/assets/14829950/f809cff4-3c80-4560-b845-42c3f0747286)
Sometims it is difficult to find the corresponding line of the byte code when decompilation without linenumber。

**Comment by Col-E** [comment]
Recaf has multiple decompilers it can pull from, and not all of them provide this information. If we plug in JD we can do this with _just_ JD, but none of the others would get it. Its not something we can build on top of the existing structure of each decompiler.

**Comment by Col-E** [comment]
Marking as `wontfix` for the Recaf-wide idea, but like stated if we add JD it can be enabled specifically with the JD config.
