### ISSUE TITLE
A question. Is it possible to compile decompiled j2me-code?

### ISSUE THREAD

**Issue by klaxons1** [Col-E/Recaf#762]
When I tried to do that, it required missing jsr-s libs, and I don't know where to put them.

**Comment by Col-E** [comment]
Never tried. If you can point to a sample I'll see what can be done.

**Comment by klaxons1** [comment]
![image](https://github.com/Col-E/Recaf/assets/59658354/98609a10-e3b3-4758-802e-58e66db480bf)
For example

**Comment by Col-E** [comment]
With targeting Java 4? Not easily. Recaf uses the JDK's `javac` to recompile, and it does not go back that far. You could of course down-sample code compiled against the lowest possible target, but we don't have downgraders that go that far back.

Also the app you loaded is obfuscated, so I wouldn't even recommend using the recompile feature even if j2me was not part of the equation.

Use the assembler for such cases.
