### ISSUE TITLE
Classes not being updated in the information panel.

### ISSUE THREAD

**Issue by mkeo102** [Col-E/Recaf#777]
**Describe the bug**

> When updating classes through the information panel (eg. removing illegal signatures / renaming), the classes shown in the information panel for main methods do not update. 

**To Reproduce**

1. Open sample '[OBFTEST.jar-out.zip](https://github.com/Col-E/Recaf/files/14983277/OBFTEST.jar-out.zip)' or any file with illegal signature/names.
2. Click the patch button
3. Attempt to open main class
4. Class has not been updated (in the case of the sample it fails to decompile).

**Comment by Col-E** [comment]
The class is updated, but the link in the entry point summary doesn't update to point to the new class. Will push up the UI fix for that in a bit.

https://github.com/Col-E/Recaf/assets/21371686/c56f707d-8c17-46cd-9582-68b4510ba57a
