### ISSUE TITLE
Methods to have their argument types on sides

### ISSUE THREAD

**Issue by memory-hunter** [Col-E/Recaf#778]
## Method classification

Description of the feature:
an indicatior to which method we are selecting and their arguments.
Comes in handy when there are a lot of overrides.
![image](https://github.com/Col-E/Recaf/assets/59766692/5d734bc9-bac8-44c6-aa70-bf3c849ad871)
So for this string to be on the side in the graph in gray for example
![image](https://github.com/Col-E/Recaf/assets/59766692/23e7f3c0-f509-4bcd-b543-2856ada2a1ab)

**Comment by memory-hunter** [comment]
Looks like settings had that option.

**Comment by Col-E** [comment]
Correct 
![image](https://github.com/Col-E/Recaf/assets/21371686/065a2415-9d24-46c0-952f-8cec00387412)
