### ISSUE TITLE
The `default` window style gives unreadable white text

### ISSUE THREAD

**Issue by stevenxxiu** [Col-E/Recaf#779]
**Describe the bug**

The `default` window style gives unreadable white text.

**To Reproduce**

- Use (the latest) commit e5669cd90c7ea6e1a3851ff9065ee687cf7bdeb9.
- `Config` -> `Display` -> `Window style`: `default`

**Exception**

**Screenshots**

![Screenshot_2024-04-28_03-22-33](https://github.com/Col-E/Recaf/assets/2058940/66382acb-8891-4d16-adc0-e94ec7000337)

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/commit/e5669cd90c7ea6e1a3851ff9065ee687cf7bdeb9#diff-fc0da4df019e4cada2c30c2695a51602c685b6a9e4ac07e12323d47ee57a61bdR151
