### ISSUE TITLE
Impossible class rename

### ISSUE THREAD

**Issue by Liticane** [Col-E/Recaf#786]
You can leave the name filed completely empty during renaming, which results in an invalid name that cannot be reverted back.

1. Open any jarfile.
2. Refactor -> Rename on any class.
3. Leave the name field empty.
4. Try renaming again.

**Exception**
`Unhandled exception on thread 'mapping-applier-x'`

**Screenshots**
![image](https://github.com/Col-E/Recaf/assets/124876745/106d9758-70a6-4a85-bb57-e3d39e522da0)

**Comment by ishan-gupt** [comment]
Hi, I would Like to work on it

**Comment by Col-E** [comment]
24d156f9db1af25ec85ddd445eaa33c9a29fdcd2
