### ISSUE TITLE
Cannot rename or open unicode named classes / variables in the code editor.

### ISSUE THREAD

**Issue by Liticane** [Col-E/Recaf#788]
**To Reproduce**

1. Open any jarfile that contains classes with unicode names.
2. Open any class that has a variable of that class' type.
3. Try right clicking on the type or on the name (if unicode).

**Comment by Col-E** [comment]
For 2.X switch to table mode.

For 3.X or 4.X use the `Fields and Methods` tab on the top right.

**Comment by eleses** [comment]
> For 2.X switch to table mode.

How does one do that?
