### ISSUE TITLE
Restore FallbackDecompiler on 4.x branch

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#790]
## FallbackDecompiler

There is a `FallbackDecompiler` in the 3.x branch, which is very useful in certain complex obfuscated code that most decompilers cannot handle correctly. Will this feature be restored in the 4.x branch?

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/commit/3766c60775271ed07c4b29d7422ca157bb3f2b0a
