### ISSUE TITLE
How can I disable decompiling with Recaf?

### ISSUE THREAD

**Issue by handy-git** [Col-E/Recaf#795]
How can I disable decompiling with Recaf?

**Comment by Col-E** [comment]
In 4.X you can do one of the following:

- Change the `User Interfface` > `Class Editing` : `Default Editor for JVM classes` value
- Change the `Decompilation` > `Decompilation manager` : `Preferred Java decompiler` value to `Fallback`

The `Fallback` decompiler is really just a half-way between decompilation and disassembling. Its way faster than a decompile, but still gives you the general class structure in Java source form.

Changing the class editing value will also work, but I'm still working on porting alternative editing modes in so you'll just get a blank screen in those cases. For classes we'll eventually support:

- Decompilation
- Hex editing
- Low level model display

**Comment by handy-git** [comment]
> In 4.X you can do one of the following:
> 
> * Change the `User Interfface` > `Class Editing` : `Default Editor for JVM classes` value
> * Change the `Decompilation` > `Decompilation manager` : `Preferred Java decompiler` value to `Fallback`
> 
> The `Fallback` decompiler is really just a half-way between decompilation and disassembling. Its way faster than a decompile, but still gives you the general class structure in Java source form.
> 
> Changing the class editing value will also work, but I'm still working on porting alternative editing modes in so you'll just get a blank screen in those cases. For classes we'll eventually support:
> 
> * Decompilation
> * Hex editing
> * Low level model display

How can I prevent my JAR from being opened by Recaf?

**Comment by Amejonah1200** [comment]
> How can I prevent my JAR from being opened by Recaf?

By not running Recaf? How do you want to reverse engineer the jar while not opening it?

**Comment by Janmm14** [comment]
@handy-git
Recaf is created to decompile, not to prevent it.

**Comment by Col-E** [comment]
Lmao
