### ISSUE TITLE
Variable exception after modifying bytecode

### ISSUE THREAD

**Issue by 1470429149** [Col-E/Recaf#797]
This is very strange. I changed iconst_0 of a certain row to iconst_1, but a strange prompt appeared when running

java.lang.ClassFormatError: Duplicated LocalVariableTable attribute entry for 'e' in class file net/playavalon/mythicdungeons/dungeons/Instance

![image](https://github.com/Col-E/Recaf-Launcher/assets/96332168/cf514a40-f772-4a79-acd6-8479895fe5dd)

[MythicDungeons2.zip](https://github.com/user-attachments/files/15514995/MythicDungeons2.zip)

**Comment by Col-E** [comment]
This got fixed in d07739627c5482320d17cc67cfccbec4a253c275 unintentionally. Editing the methods and checking the `javap` outputs no longer shows duplicate `e` entries in the local var table.
