### ISSUE TITLE
Index out of range error with unmodified assembly listing of class

### ISSUE THREAD

**Issue by Sukasa** [Col-E/Recaf#799]
**Describe the bug**

Trying to open and modify a class via the assembler view, I am unable to make modifications.  The unmodified assembly listing cannot save due to an index out of bounds error

**To Reproduce**

1. Open sample 'Railcraft_1.7.10-9.12.2.1.jar' [Railcraft_1.7.10-9.12.2.1.jar.zip](https://github.com/user-attachments/files/15527129/Railcraft_1.7.10-9.12.2.1.jar.zip)
2. Navigate to `mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine`
3. Right-click a member and select Edit -> Edit Class in Assembler
4. Error marker in upper right, unable to save assembled class

**Exception**
No exception is present in the recaf log
[recaf-log-noJPhantom.txt](https://github.com/user-attachments/files/15527128/recaf-log-noJPhantom.txt)

**Comment by Col-E** [comment]
Looks like a problem handling `multianewarray`, can reproduce with:
```java
.class Foo {           
    .method static foo ()V {
        code: {
        A: 
            iconst_4 
            multianewarray [[[C 3
            astore map2
        B:
            return 
        }
    }
}
```

**Comment by Col-E** [comment]
38d52a65f3b3da45f01abc299baf56ebce06d46f
