### ISSUE TITLE
The decompiler configuration options are not working

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#801]
**Describe the bug**

The decompiler configuration options are not working, at least some or all of VineFlower's. Change the decompiler configuration options and then observe the decompiled results. As shown in the screenshot, I turned on both options of Vineflower, but the decompiled results did not display the strings as ASCII and dump the line numbers as expected.

**To Reproduce**

1. Change the decompiler configuration options and observe the decompilation results.

**Screenshots**

![image](https://github.com/Col-E/Recaf/assets/39942874/b091f061-d6da-4d1e-8b0b-7412a9073e54)

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/assets/21371686/433b7792-4eb1-43a4-90a9-65e8a5eb7ff2

**Comment by Col-E** [comment]
https://github.com/Col-E/Recaf/assets/21371686/4eadeb0b-8c64-4df6-8afa-f20168fed0d0

**Comment by Geolykt** [comment]
As per the issue that mentions this one, I suggest that the Dump Code Lines option is removed. I don't see much use in enabling it and will only confuse the vast majority of users.

**Comment by meiMingle** [comment]
@Col-E If you have time, can you investigate this issue again? I just tested it with the latest code (505af81), and `Dump Code Lines` still doesn't work for Vineflower. My ultimate goal is to see the original line numbers in the decompiled code, just like the behavior of the IDEA registry key `decompiler.dump.original.lines`.According to Geolykt's statement, maybe there should be an option DUMP_ORIGINAL_LINES
![image](https://github.com/Col-E/Recaf/assets/39942874/677f0756-393a-4700-a63a-9ae975e0c55a)

**Comment by Col-E** [comment]
I swapped the key out for `__dump_original_lines__` which should let you do what you want. Do note, you need to also enable the bytecode mapping setting.

**Comment by meiMingle** [comment]
@Col-E @Geolykt Thank you my friends, this will help me a lot in my work.I just tested it and it works fine!!
