### ISSUE TITLE
After closing a workspace, you cannot open any jar/class by dragging it.

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#803]
**Describe the bug**

> Some exceptions are thrown after closing the workspace, and the workspace cannot be opened by dragging files until Recaf is restarted

**To Reproduce**

1. Open any jar/class by Reacf
2. Close the workspace by `File -> Close`.At this time, the Logging window of Recaf will display `Exception thrown when closing workspace`
![image](https://github.com/Col-E/Recaf/assets/39942874/7269e1c8-5051-4bbd-bedd-21bd33d09ce9)

3. Drag any jar/class file to the Recaf window and it cannot be opened
![image](https://github.com/Col-E/Recaf/assets/39942874/472c98f2-dbf6-482b-8a2a-b4913734d247)

**Exception**
`java.lang.NullPointerException: 'workspace' must not be null`
Log
[log-2024-06-06.txt](https://github.com/user-attachments/files/15598985/log-2024-06-06.txt)

**Screenshots**

**Comment by Col-E** [comment]
47ee1024e2952ff8d23a63bb64465ae8b03c147f
