### ISSUE TITLE
error in Recaf

### ISSUE THREAD

**Issue by alexthermite546** [Col-E/Recaf#808]
I tried to open .jar file, but it turned out to be:
![image](https://github.com/Col-E/Recaf/assets/173156046/f3fc50e1-72da-4c40-85d5-cadc700493bf)
I think it's not good things
(The class names are like this because it is used renamer).

**Comment by Amejonah1200** [comment]
You are using an old version of Recaf which has an old ASM version. This makes classes not being able to be parsed and so not opened.
Please download the recaf launcher and with this then the new 4.x version.

**Comment by alexthermite546** [comment]
![image](https://github.com/Col-E/Recaf/assets/173156046/248ac54f-7e74-47e1-a7b2-11d788a1faab)

**Comment by rucko24** [comment]
- https://github.com/Col-E/Recaf/releases/tag/2.21.14

![image](https://github.com/Col-E/Recaf/assets/17187599/5bf9c519-3553-4b69-9556-2f582eca034d)

**Comment by Col-E** [comment]
Provide a sample if you can or logs. We cannot help you with just a screenshot.

**Comment by alexthermite546** [comment]
[rclog.txt](https://github.com/user-attachments/files/15886834/rclog.txt)
[log-2024-06-18.txt](https://github.com/user-attachments/files/15886835/log-2024-06-18.txt)

**Comment by alexthermite546** [comment]
if you need, I can give you this jar file.

**Comment by jumanji144** [comment]
Please send them to me on discord, if you can
id: jumanji144.

**Comment by xxDark** [comment]
This file won't open in Recaf.

**Comment by Col-E** [comment]
To elaborate: The files in the jar have the extension `.class` but do not model the class file format:

![image](https://github.com/Col-E/Recaf/assets/21371686/c183d43a-006e-49cf-a239-1915b1d9a4a2)

We are unable to magically convert this back into a format that can be operated on. Its likely protected with some external loading mechanism.
