### ISSUE TITLE
Misidentified file type

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#809]
**Describe the bug**

> Some text resource files (txt, js, html, etc.) are mistakenly identified as binary files

**Screenshots**

![image](https://github.com/Col-E/Recaf/assets/39942874/4113e8fb-f07f-415c-bd03-d23234aaf6be)

**Comment by meiMingle** [comment]
https://www.wenshushu.cn/f/eefoopyxuul

**Comment by Col-E** [comment]
It looks like the buffering we used in checking `byte[]` for string encodings wasn't being managed correctly. Fixing buffer usage makes the HTML/Js files recognizable as text again. Will push the fix up in a bit after some cleanup.

**Comment by Col-E** [comment]
b5dae14c96ecd3f93baaddd34993d785a00a9550
