### ISSUE TITLE
"OpCodes Window" improvements

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#81]
**OpCodes Window (Open any Class -> Methods -> Instructions)**

## OpCodes always on top
The OPCodes window  (Open any Class -> Methods -> Instructions) is always on top. It should let other windows be on top of the screen.

## Opcodes in ComboBox
The window that let modify the opcodes  show the "Opecodes" with "Radio buttons" instead of "ComboBox". I think that the ComboBox is more intuitive. And the available OpCodes should be in alphabetical order.

## Opecodes saving and discarding changes
The same window should have two buttons: [Save] and [Cancel] for saving the change and for cancel the changes. Right now any change is automatically applied.

**Comment by Col-E** [comment]
> Always on top

This is a config option that can be disabled: `Top-most editor windows`

> Opcodes in ComboBox _(vs group of radios)_

Fair point.

> Change automatic saving to manual

I think allowing the user to swap between automatic and manual modes would be another path to consider. The UI code is quite messy so this will take a bit to implement.

**Comment by pedroflor** [comment]
Thank you!

**Comment by pedroflor** [comment]
Thanks!
