### ISSUE TITLE
Uncaught exception when trying to open assembler panel for method

### ISSUE THREAD

**Issue by Decencies** [Col-E/Recaf#814]
**Describe the bug**

When trying to open the assembler for a specific sample method, it throws `Uncahight exception on thread 'JavaFX Application Thread'`

**To Reproduce**

1. Open 'a.class' from [a.zip](https://github.com/user-attachments/files/16041125/a.zip)
2. Navigate to 'public void b(lv, long)'
3. Try opening the assembler panel

**Exception**

Unfortunately, I was unable to get any verbose logging information when running Recaf through the recaf launcher.

**Comment by Decencies** [comment]
Edit: this appears to happen for every method

**Comment by Decencies** [comment]
**System**
| Name | Architecture | Processors |
| -------- | -------- | -------- |
| `Windows 10` | `amd64` | `12` |

**Java**
| Version | VM name | VM vendor | Home | Supports compiler |
| -------- | -------- | -------- | -------- | -------- |
| `21.0.3` | `OpenJDK 64-Bit Server VM` | `Eclipse Adoptium` | `C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot` | `true` |

**JavaFX**
| Version |
| -------- |
| `19.0.2` |

**Comment by Col-E** [comment]
Had to try it a few times before I got it:
```
java.lang.IllegalStateException: Called endChange before beginChange
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:538)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:210)
	at com.sun.javafx.collections.ObservableListWrapper.clear(ObservableListWrapper.java:157)
	at software.coley.recaf.ui.pane.editing.assembler.JvmVariablesPane.clearData(JvmVariablesPane.java:268)
	at software.coley.recaf.ui.pane.editing.assembler.JvmVariablesPane.onClassSelected(JvmVariablesPane.java:140)
```

**Comment by Col-E** [comment]
85ed3586a5c50d5661a3dba537f376912ce2d555 - Wasn't clearing data on FX thread which caused a race
