### ISSUE TITLE
Unable to find Assembler Option

### ISSUE THREAD

**Issue by VishnuRameshbabu** [Col-E/Recaf#816]
Hello,

I have a problem with accessing the assembler, not sure If I am doing it correctly or missing something. I read the documentation but I couldn't replicate it. 

Since the class file is giving errors, I can't do the modification and recompile it. So, I am trying to use the assembler to modify the bytecode instead, but the problem is I can't right click on a method to modify it. Not sure If I am missing something entirely.

![image](https://github.com/Col-E/Recaf/assets/51319688/2aa0bfbd-d624-4c35-b927-4addc53becf9)

Thanks in Advance.

**Comment by Col-E** [comment]
In 2.X switch to table mode if right-click context analysis is failing - https://www.coley.software/Recaf-documentation/use-modes.html

**Comment by VishnuRameshbabu** [comment]
Thanks for the letting me know. I was able to solve what I required.
