### ISSUE TITLE
Add Discord Rich Presence Support

### ISSUE THREAD

**Issue by b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0** [Col-E/Recaf#819]
Hi,

I would like to suggest adding a "Rich Presence" feature for Discord to Recaf. This feature would enhance the user experience by allowing users to display their current activity in Recaf directly on their Discord profile. Here are some potential benefits and details:

Benefits:

Increased Engagement: Users can show off their activity in Recaf, which could spark interest among their friends and community.
Real-Time Status: Provides real-time updates on what users are doing in Recaf, such as "Editing a class file", "Decompiling code", etc.
Customization: Users can customize their Rich Presence to include specific details about their work, adding a personal touch to their Discord profile.

**Comment by Col-E** [comment]
People have made plugins for this in the past. But it is something I will not be building into the core of Recaf.
