### ISSUE TITLE
Add keybinds to rename packages and classes in the file tree

### ISSUE THREAD

**Issue by TheEntropyShard** [Col-E/Recaf#820]
## Rename classes and packages in file tree using keyboard

Currently to do this you need to right click an item, choose Refactor then choose Rename. It is not very convenient, would be cool to have a shortcut, for example F2 like in windows explorer or Shift+F6 like in IntelliJ

**Comment by Col-E** [comment]
90cceb69c9997d1de2d0865d3e55dd7107d63219
