### ISSUE TITLE
idk if am dumb

### ISSUE THREAD

**Issue by itsRGB** [Col-E/Recaf#821]
i got the build of recaf from Artifacts and cant seem to work it
i have JRE 8,11,17,21,22 installed 
and JDK 8,11,17 and the JAVA_HOME is set to 8

C:\Users\kendrick>java -jar C:\Users\kendrick\OneDrive\Desktop\recaf-ui-4.0.0-SNAPSHOT-all.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: software/coley/recaf/Main has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)

**Comment by Amejonah1200** [comment]
What does `java -version` give you? Spoiler: Java 8

What does matter is the version `java` is, it doesn't select it automatically. Also, consider using the launcher!

**Comment by itsRGB** [comment]
when i launch recaf or its launcher it gives me the error "Error: A JNI error has occurred, please check your installation and try again"

**Comment by itsRGB** [comment]
when i run the launcher it does nothing and this is what the log says

Attempting to resolve installed Recaf version...
Found Recaf's build config, checking contents...
 - MAVEN_GROUP = software.coley
 - MAVEN_NAME = recaf-core
 - VERSION = 4.0.0-SNAPSHOT
 - GIT_REVISION = 1
 - GIT_SHA = 30f5f2d59cb59eb7d4fb97abaa3e65a65cc10f99
 - GIT_DATE = 2024 07/07 01:58
 - GIT_BRANCH = dev4
 - BUILD_DATE = 2024 07/07 01:59
 - BUILD_UNIX_TIME = 1720317553496
 - DIRTY = 0

**Comment by meiMingle** [comment]
You should probably use JDK22 instead of JDK8

**Comment by itsRGB** [comment]
switched over to JDK22 and still says crashes 10:48:09.009 
[JFXValidation/main] ERROR: JFX validation failed, could not find 'VersionInfo' class
java.lang.ClassNotFoundException: com.sun.javafx.runtime.VersionInfo
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:413)
        at java.base/java.lang.Class.forName(Class.java:404)
        at software.coley.recaf.util.JFXValidation.validateJFX(JFXValidation.java:33)
        at software.coley.recaf.Main.main(Main.java:72)

**Comment by Col-E** [comment]
The two links for using 4.X at the moment point you either to:

- [Using the launcher](https://github.com/Col-E/Recaf-Launcher) to handle things for you
- [Using the release artifacts](https://github.com/Col-E/Recaf-Launcher/blob/master/MANUAL.md) but setting things up manually yourself _(Doing what the launcher does but doing it yourself)_

If your errors are about unsupported class versions, you need to update the version of Java used to run Recaf.

If your errors are about a missing JavaFX class, you are not including JavaFX in the classpath when running Recaf.

**Comment by itsRGB** [comment]
> The two links for using 4.X at the moment point you either to:
> 
>     * [Using the launcher](https://github.com/Col-E/Recaf-Launcher) to handle things for you
> 
>     * [Using the release artifacts](https://github.com/Col-E/Recaf-Launcher/blob/master/MANUAL.md) but setting things up manually yourself _(Doing what the launcher does but doing it yourself)_
> 
> 
> If your errors are about unsupported class versions, you need to update the version of Java used to run Recaf.
> 
> If your errors are about a missing JavaFX class, you are not including JavaFX in the classpath when running Recaf.

how do i add JavaFx to my classpath?

**Comment by Amejonah1200** [comment]
> how do i add JavaFx to my classpath?

technically, you shouldn't with the launcher...

**Comment by itsRGB** [comment]
even when trying to use the launcher 

Attempting to resolve installed Recaf version...
Found Recaf's build config, checking contents...
 - MAVEN_GROUP = software.coley
 - MAVEN_NAME = recaf-core
 - VERSION = 4.0.0-SNAPSHOT
 - GIT_REVISION = 1
 - GIT_SHA = 30f5f2d59cb59eb7d4fb97abaa3e65a65cc10f99
 - GIT_DATE = 2024 07/07 01:58
 - GIT_BRANCH = dev4
 - BUILD_DATE = 2024 07/07 01:59
 - BUILD_UNIX_TIME = 1720317553496
 - DIRTY = 0
Attempting to resolve JFX version...
No JavaFX version class found in the current classpath
Java Properties:
 - java.home = C:\Program Files\Eclipse Adoptium\jdk-22.0.1.8-hotspot
 - java.version = 22.0.1
 - java.vm.vendor = Eclipse Adoptium
 - java.vm.version = 22.0.1+8
 - javafx.platform = win
 - javafx.version = -1
 - os.arch = amd64
 - os.bitness = 64
 - os.name = Windows 10
 - os.processors = 4
 - os.version = 10.0
 - recaf.version = 4.0.0-SNAPSHOT


===============================================================
You did not provide any launch arguments, or specify a default
to run in the launcher config.

You can open the GUI by running with 'javaw' instead of 'java'.
If you meant to provide launch arguments, their usage is below.
===============================================================


Usage: <launcher> auto
Runs the suggested commands in order:
 - compatibility
 - update-jfx -maxc 30 -maxs 60000000 -k
 - update
 - run
If one of the commands fails, the following ones are skipped.

Usage: <launcher> compatibility [-ifx] [-ss]
Checks the local system for compatibility with Recaf 4.X
      -ifx, --ignoreBundledFx
         Ignore problems with the local system's bundled JavaFX version
      -ss, --skipSuggestions
         Skip solutions to detected problems

Usage: <launcher> update-jfx [-cfk] [-maxc=<maxCacheCount>]
                             [-maxs=<maxCacheSize>] [-v=<version>]
Updates JavaFX
  -c, --clear               Clear the dependency cache
  -f, --force               Force re-downloading even if the local install
                              looks up-to-date
  -k, --keepLatest          Keep latest cached dependency in the cache when
                              clearing
      -maxc, --maxCacheCount=<maxCacheCount>
                            Clear the dependency cache when this many files
                              occupy it
      -maxs, --maxCacheSize=<maxCacheSize>
                            Clear the dependency cache when this many bytes
                              occupy it
  -v, --version=<version>   Target JavaFX version to use, instead of whatever
                              is the latest

Usage: <launcher> update
Updates Recaf

Usage: <launcher> update-ci [-b=<branch>]
Installs the latest artifact from CI
  -b, --branch=<branch>   Branch name to pull from.
                          By default, no branch is used.
                          Whatever is found first on the CI will be grabbed.

Usage: <launcher> version
Checks what version of Recaf is installed locally

Usage: <launcher> run [-j=<javaExecutable>]
Runs the installed version of Recaf
  -j, --java=<javaExecutable>
         Path of Java executable to use when running Recaf.
         Not specifying a value will use the same Java executable used by the
           launcher.

Usage: <launcher> set-default-action <action>
Allows specifying a default action to run when no arguments are specified. For
commands with spaces in them, surround the whole command with quotes.
      <action>   The action to run. Should match one of the launcher commands.

**Comment by Amejonah1200** [comment]
Literally read what the messages are saying, bruh
