### ISSUE TITLE
Please only rename inner classes via mapping operations.

### ISSUE THREAD

**Issue by cheechNC** [Col-E/Recaf#826]
just trying to recompile a class that normally recompiles on recaf v2.. on v4 im getting: "Please only rename inner classes via mapping operations." and  a yellow flash instead of green.. 
any clues?
Thanks..

**Comment by Col-E** [comment]
Cases like this need a sample to see what's causing the bug

**Comment by cheechNC** [comment]
@Col-E  Can private email? or...

**Comment by Col-E** [comment]
For now my primary contact for samples would be discord: `invokecoley`

**Comment by cheechNC** [comment]
> For now my primary contact for samples would be discord: `invokecoley`

sent.
