### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by pedroflor** [Col-E/Recaf#83]
Hi... I'm Peter
I enjoy to use your software... thanks for all your effort.

I really would like to contribute with some minor improvements. I'm not a good programmer but I want to help.
If you agree, could you give me some basic orientation/guides?
Compiling, software to use, tips, etc.

Best regards.

**Comment by Col-E** [comment]
Sure, if you hop on the discord server (https://discord.gg/Bya5HaA) I'll be able to fill you in on anything you want information on. College classes are draining a lot of my time as of late, but I'll be online later in the day almost daily.

**Comment by Col-E** [comment]
I see that you're in. Closing.

**Comment by pedroflor** [comment]
Thanks
