### ISSUE TITLE
Class Copy Feature

### ISSUE THREAD

**Issue by 1337kat** [Col-E/Recaf#831]
## **Additional Right-Click context menu support**
When hovering over a class, provide a right-click context menu with options: "Copy", "Remove", "Paste", "Duplicate" etc.

Note: The content you see in this GIF is not part of Recaf; it’s merely a demonstration. I used photoshop to make this possible

![recaf suggestion](https://github.com/user-attachments/assets/2e1737ba-ae9f-4d92-8a54-b72e4a6a5ed9)

## **Right click context menu support:**
- Jar
- Class (folders included)
- War
- Directories

**Comment by Col-E** [comment]
We already have this in Recaf 4.X

![image](https://github.com/user-attachments/assets/2f80f3dd-0d7f-4187-ab2a-065e090e8cb9)
