### ISSUE TITLE
Field Value Inserting (Recaf 4x)

### ISSUE THREAD

**Issue by 3000IQPlay** [Col-E/Recaf#832]
**Describe the bug**

> So whenever you try and insert brackets first "{}" and then go backwards in between the brackets using arrow keys and you type something, it will be typed backwards.

**To Reproduce**

1. Open any Jar that has a class with a field to which you can assign value.
2. First type "{}".
3. After go backwards between the brackets (I used arrow keys to get between the brackets).
4. Type in anything.
4. See error.

**Video**

https://youtu.be/y2T-ssM9pMg

**Comment by Col-E** [comment]
Seems like an odd interaction between the improper handling of an invalid AST and the UI thread. Adding a [null check](7cdd2e00d5f0627df6a8d703bc6271fbb9db2569) seems to have resolved the issue.
