### ISSUE TITLE
Text on recaf are wrong cant read

### ISSUE THREAD

**Issue by lexcorp** [Col-E/Recaf#833]
**Describe the bug**

>Recaf dont show fonts correctly 

**To Reproduce**

1. Open recaf via cli cmd with java -jar command
2. Applications Open
3. The texts of appication its wrong

**Exception**
>java -jar recaf-2.21.14-J8-jar-with-dependencies.jar
19:55:41.742 [main] INFO : Recaf-2.21.14
19:55:41.745 [main] INFO : - Java: 11.0.12 (OpenJDK 64-Bit Server VM)
19:55:41.902 [main] TRACE: Loading configuration
Jul 28, 2024 7:55:43 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1554909b'

**Screenshots**

![image](https://github.com/user-attachments/assets/08a07fbe-0188-4e61-8092-29b1b9b00183)

**Comment by lexcorp** [comment]
Ok, I solve this changing font in menu config -> Monospace font 
![image](https://github.com/user-attachments/assets/a4da9ee0-4412-4480-9eb8-2fd9f21f8047)

**Comment by Amejonah1200** [comment]
Please use Recaf 4, Recaf 2 is deprecated and unsupported now.

You can download it using the Col-E/Recaf-Launcher repository
