### ISSUE TITLE
Support Latest LTS Release/Java 21

### ISSUE THREAD

**Issue by amplitudesxd** [Col-E/Recaf#834]
I think that Recaf 4 should support the latest LTS version of Java, which is currently Java 21, instead of requiring Java 22.

**Comment by Amejonah1200** [comment]
Java 22 is used because the FFM (Foreign function and memory) API is much better to use than JNI.

You don't need to have JDK 22 as a main JDK either, you can point to a JDK 22 installationusing the launcher.
