### ISSUE TITLE
Recaf accepts `multianewarray` with `0` dimensions

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#839]
**Describe the bug**

> A clear and concise description of what the bug is.

> The dimensions operand is an unsigned byte that must be greater than or equal to 1
\- https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.multianewarray

`multianewarray` with `0` dimensions is invalid 

**To Reproduce**

Create a class named `L` and add a static method.
Add the following to the bytecode:
```
multianewarray LL; 0
pop
```

**Comment by Col-E** [comment]
upstream: 8f5a10727dbfca40f3f21c777d00982821ccb7ed
