### ISSUE TITLE
Recaf cannot identify any functions

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf#850]
Recaf cannot correctly identify function so i can view them in assenbler
im a forge mod creator and i need to use recaf to look at jvm instructions, but it cannot identify
![image](https://github.com/user-attachments/assets/2fde5909-04a1-492e-8fae-aebd9dd404ee)
enable blend is suppose to be a function where i can click into assembler to see(without mappings applied), but after i applied mappings i cannot click into it
mappings are attached(its a srg file)
[vanilla.zip](https://github.com/user-attachments/files/16692575/vanilla.zip)
here;s the class:
[bfl.zip](https://github.com/user-attachments/files/16692579/bfl.zip)

**Comment by Col-E** [comment]
If the code is obfuscated the parser can sometimes get confused. This is why you have the `fields and methods` tab in the top right. You can interact with things through it while still being able to see the decompiled code.

**Comment by Col-E** [comment]
Also fwiw, I cannot reproduce this with the provided files and steps:

![image](https://github.com/user-attachments/assets/3463fb13-43cf-4363-a3d1-94bb20161fe3)
