### ISSUE TITLE
String out of bounds Error when applying mappings

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf#854]
Parse error from source of: net/minecraft/client/renderer/EntityRenderer after 492ms, err=java.lang.StringIndexOutOfBoundsException: Range [78655, 78655) out of bounds for length 78644
  java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
  java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
  java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
  java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
  java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
  java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
  java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
  java.base/java.lang.String.substring(String.java:2876)
  org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1667)
  org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitAssignment(ReloadableJava17ParserVisitor.java:195)
  org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitAssignment(ReloadableJava17ParserVisitor.java:73)
  com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:2070)
  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
  com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:503)
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1611)
  ...
here's the java class and my mappings
[New folder.zip](https://github.com/user-attachments/files/16913798/New.folder.zip)
should have somethin to do with the method description ig, its too long and inorder to fix we probably have to parse another list for the busted part and then treat them as one

**Comment by Col-E** [comment]
This doesn't happen when applying the mappings. Opening the class without mapping applied will show this message. That being said you can ignore this. We expect these sorts of problems with obfuscated code. So when the AST parser fails you should use the _"Fields & Methods"_ tab on the right.

What is likely happening is the AST parser is incrementing a cursor offset that doesn't line up with the actual source string being parsed. The discrepancy down the line leads to the cursor extending beyond the length of the string by 4 characters. This is a problem upstream with the parser library we're using.
