### ISSUE TITLE
Empty inner classes with CFR

### ISSUE THREAD

**Issue by ME1312** [Col-E/Recaf#855]
**Describe the bug**

When using CFR with the default settings on an outer class, inner classes appear to be devoid of code.
<br>

**To Reproduce**

1. Open a class that contains an inner class with CFR in Recaf 4
2. Scroll to the inner class
3. Zero, false, null, etc. 
<br>

**Screenshots**

![Outer class](https://i.postimg.cc/nLx1hFJG/outer.png)

![Inner class](https://i.postimg.cc/CxkN0ZWK/inner.png)

**Comment by Col-E** [comment]
Can you provide a sample which reproduces the issue consistently?

**Comment by ME1312** [comment]
Yes. [Problem.zip](https://github.com/user-attachments/files/17180151/Problem.zip) contains a class that contains an inner class that you can have a look at.

**Comment by Col-E** [comment]
78093b848c1ca74e8b6bec7c03ebd6c90d3601b9 - I don't recall why that was added in the first place but that would certainly do it 🫠
