### ISSUE TITLE
Output is quarantined

### ISSUE THREAD

**Issue by delanym** [Col-E/Recaf#856]
The output file of Recaf is immediately quarantined by Windows Defender and flagged as `Trojan:Script/Sabsik.TE.B!ml`

Besides disabling the anti-virus, is there any advice on how to work around this?

**Comment by Col-E** [comment]
What files was the input?

**Comment by delanym** [comment]
A proprietary JAR artifact that I created. I changed a method to always return true by swapping the `iconst_0` at L: with `iconst_1`

![image-2024-9-18_15-36-51](https://github.com/user-attachments/assets/1774ab3a-f14b-4083-9f19-83733ebc7baa)

I appended "-MODIFIED" to the filename and saved to a new artifact.
