### ISSUE TITLE
反编译器报错 解析 4.x版本

### ISSUE THREAD

**Issue by haishen668** [Col-E/Recaf#859]
**bug描述**

>反编译器报错  

**堆栈信息**

>java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.DCTree$DCDocComment >com.sun.tools.javac.tree.DocCommentTable.getCommentTree(com.sun.tools.javac.tree.JCTree)'
>  org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1669)
>  org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:539)
>  org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:73)
>  com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:625)
>  com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)

**环境**
**系统**
| Name | Architecture | Processors |
| -------- | -------- | -------- |
| `Windows 11` | `amd64` | `20` |

**Java**
| Version | VM name | VM vendor | Home | Supports compiler |
| -------- | -------- | -------- | -------- | -------- |
| `23` | `OpenJDK 64-Bit Server VM` | `Oracle Corporation` | `C:\Users\Administrator\.jdks\openjdk-23` | `true` |

**JavaFX**
| Version |
| -------- |
| `24-ea` |

**Recaf**
| Version | Build | Settings directory |
| -------- | -------- | -------- |
| `4.0.0-SNAPSHOT` | `e060831 2024 09/22 08:08` | `C:/Users/Administrator/AppData/Roaming/Recaf` |

**截图**

![image](https://github.com/user-attachments/assets/428a065d-76a1-4be4-8b52-07aad5cb1234)

**Comment by Col-E** [comment]
Should be easy on our end, just bump the OpenRewrite dependency to address https://github.com/openrewrite/rewrite/pull/4516

**Comment by haishen668** [comment]
所以我应该做些什么，使用其他平台或者版本的java吗，能否给我推荐一下合适的版本，非常感谢 ！我现在的javafx版本应该是24

**Comment by Col-E** [comment]
Should be solved as of 16ec6ae25098697cadbb51451938a18a67f0fa73

**Comment by Col-E** [comment]
Its not solved :/

**Comment by Col-E** [comment]
I opened https://github.com/openrewrite/rewrite/issues/4540 for a follow on-fix upstream

**Comment by Col-E** [comment]
The upstream follow on fix has been merged and added
