### ISSUE TITLE
Style issue in Decompile window

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#86]
![decompile-view](https://user-images.githubusercontent.com/12008103/46188392-6e7cb500-c31b-11e8-8de5-130ab1682d5b.png)
![decompile-view-hover](https://user-images.githubusercontent.com/12008103/46188421-923ffb00-c31b-11e8-9b84-f5ccab855e47.png)

**Steps to reproduce**:
1. Open any jar.
2. Navigate to any method in any class.
3. Right click on method -> `Decompile`.
4. Right click anywhere in `Decompile` window.

Stylesheet `none` also has this problem.

**Comment by Col-E** [comment]
Also the method recompilation has been unsupported since the `1.0` rewrite. It was buggy before and I haven't gotten around to properly re-adding it.
