### ISSUE TITLE
Making it possible for vineflower and fernflower to coexist

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#866]
## Feature_Name

Use the Relocating Packagesg function of the com.github.johnrengelman.shadow plugin to process the decompiler class library. This can theoretically allow vineflower and fernflower and other similar decompilers to coexist in Recaf. This has the following benefits: 
① Recaf users can get more compiler results as references 
② Vineflower and fernflower and other similar decompilers developers can compare the differences between their decompilation results, promoting the update and iteration of decompilers

**Comment by Col-E** [comment]
The issue is compiling against both. They both share the same names, so even if we add the dependency for both on the classpath, shadow will just map both of them to whatever is being shaded since it cannot tell the difference.

**Comment by meiMingle** [comment]
This may be of reference value https://github.com/Earthcomputer/class-file-indexer/blob/main/build.gradle.kts

**Comment by meiMingle** [comment]
I think it makes sense to do this, and I will work hard on it. At present, I have completed some work and realized the coexistence of fernflower, vineflower, and forgeflower libraries. The next step is to implement 'AbstractJvmDecompiler` and `BaseDecompilerConfig` for fernflower and forgeflower. Wait for my good news! !

**Comment by meiMingle** [comment]
Currently, rough support for fernflower and forgeflower has been completed. The next step is to sort out the relevant configuration items and complete the configuration interface. Wait for my good news!!
