### ISSUE TITLE
Recaf not detect changing anymore

### ISSUE THREAD

**Issue by phucynwa** [Col-E/Recaf#869]
I edited a class method then Cmd + S to save. But when I File -> Export application it shows "nothing changed, do you want to save?". Please check and fix it. I'm using Mac OS.

**Comment by Col-E** [comment]
> I edited a class method then Cmd + S to save.

When I make a change via recompiling that is valid, I see the green success flash. Then when I export to a file and open that file I see my change has been applied.

Did you see the green success flash?

**Comment by phucynwa** [comment]
No I don't see any green success flash.

But when I try edit a method by Edit -> Make no-op then Export application, it works.

**Comment by Col-E** [comment]
Like stated, if there's no success flash and you encounter errors you either:

1. Fix them
     - Subject to incorrect fixes
     - Decompilation is lossy anyways, so some changes may not be inherently obvious or straight forward
2. Use the assembler

**Comment by phucynwa** [comment]
@Col-E It just works for making function's body empty, no changing can done.
