### ISSUE TITLE
Errors after launch. Unsupported JavaFX configuration.

### ISSUE THREAD

**Issue by vladimirlv17** [Col-E/Recaf#889]
After launching I get a message:
**Describe the bug**
17:58:50.611 [main] INFO : Recaf-2.21.14
17:58:50.616 [main] INFO : - Java: 17.0.8 (Java HotSpot(TM) 64-Bit Server VM)
17:58:50.826 [main] TRACE: Loading configuration
17:58:51.131 [main] INFO : Discovered plugin 'Resource Cleaner-1.3.0'
17:58:51.132 [main] INFO : Discovered plugin 'Batch Decompile-1.2.1'
17:58:51.132 [main] INFO : Discovered plugin 'Theme Editor-1.0.0'
17:58:51.133 [main] INFO : Discovered plugin 'String Replace-1.0.0'
17:58:51.133 [main] INFO : Discovered plugin 'NO-OP-1.0'
17:58:51.133 [main] INFO : Discovered plugin 'RPC-1.1.2'
17:58:51.133 [main] INFO : Loaded 6 plugins
Dec 01, 2024 5:58:52 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3952037b'
Exception in thread "RPC-Callback-Handler" java.lang.ClassCastException: class javafx.scene.control
.ScrollPane cannot be cast to class me.coley.recaf.ui.controls.view.EditorViewport (javafx.scene.co
ntrol.ScrollPane and me.coley.recaf.ui.controls.view.EditorViewport are in unnamed module of loader
 'app')
        at fr.flowarg.recafrpcplugin.FileType.getCurrentFileType(FileType.java:51)
        at fr.flowarg.recafrpcplugin.RPCPlugin.updateRPC(RPCPlugin.java:73)
        at fr.flowarg.recafrpcplugin.RPCPlugin.lambda$onStart$1(RPCPlugin.java:50)
        at java.base/java.lang.Thread.run(Thread.java:833)
17:58:57.147 [JavaFX Application Thread] INFO : Shutting down
17:58:57.151 [JavaFX Application Thread] TRACE: Saving configuration
17:58:57.173 [JavaFX Application Thread] TRACE: Shutting down thread executors

**Screenshots**
![image](https://github.com/user-attachments/assets/9cdb8a84-4a28-4fca-90c7-007d0f74fe3f)

OS: Ubuntu Mate 22.04
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

**Comment by xxDark** [comment]
Recaf 2 is not supported
Delete all plugins and see if anything changes. The exception is caused by a plugin "RPC-1.1.2"

**Comment by vladimirlv17** [comment]
I removed the plugins in /home/vladimir/.config/Recaf/plugins.
The following error appeared:
14:53:35.670 [main] INFO : Recaf-2.21.14
14:53:35.673 [main] INFO : - Java: 17.0.8 (Java HotSpot(TM) 64-Bit Server VM)
14:53:35.893 [main] TRACE: Loading configuration
Dec 02, 2024 2:53:36 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3952037b'
14:53:41.296 [JavaFX Application Thread] INFO : Shutting down
14:53:41.301 [JavaFX Application Thread] TRACE: Saving configuration
14:53:41.319 [JavaFX Application Thread] TRACE: Shutting down thread executors

**Comment by xxDark** [comment]
We will not offer support for Recaf 2.x.
`
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3952037b'` does not mean anything and could be safely ignored

**Comment by Amejonah1200** [comment]
Go to https://github.com/Col-E/Recaf-Launcher, get the gui jar and enjoy.

**Comment by vladimirlv17** [comment]
> Go to https://github.com/Col-E/Recaf-Launcher, get the gui jar and enjoy.

It's works.

**Comment by vladimirlv17** [comment]
This is not a bug, this is a feature.
