### ISSUE TITLE
Running scripts in Recaf launched from the GUI Launcher fails

### ISSUE THREAD

**Issue by RobDearling** [Col-E/Recaf#896]
**Describe the bug**

When running any script from Recaf 4 that has been launched from the Recaf GUI Launcher(0.8.0) it produces an error of `package.software.coley.recaf does not exist`

![image](https://github.com/user-attachments/assets/56fcc081-793e-453c-ab3a-4c4e14bdd043)

**To Reproduce**

1. Open GUI Launcher (0.8.0
2. Launch the latest Recaf (Using JDK 23)
3. Attempt to run any script

**Exception**

If applicable, add the exception/stacktrace.
```
package.software.coley.recaf does not exists
```

**Screenshots**

![image](https://github.com/user-attachments/assets/56fcc081-793e-453c-ab3a-4c4e14bdd043)

**Comment by Col-E** [comment]
> Attempt to run any script

Can you elaborate on this step? There's technically multiple ways you could run a script.

**Comment by Col-E** [comment]
I'll create a new launcher release `0.8.1` later today including the fix from xdark
