### ISSUE TITLE
Unreadable UI text (4.X)

### ISSUE THREAD

**Issue by codenulls** [Col-E/Recaf#897]
**Describe the bug**

I tried the launcher, but I couldn't see the UI after running it (no errors), so I'm running recaf directly:
```
java -cp recaf-ui-4.0.0-SNAPSHOT-all.jar;dependencies/* software.coley.recaf.Main
```
And the rest is history. No matter what I do, I just can't get the text to work.

Info about JDK: 
```
openjdk 23.0.1 2024-10-15
OpenJDK Runtime Environment Temurin-23.0.1+11 (build 23.0.1+11)
OpenJDK 64-Bit Server VM Temurin-23.0.1+11 (build 23.0.1+11, mixed mode, sharing)
```

Maybe I can change the font? I just don't know how to do it.

You can download the build from [here](https://drive.google.com/file/d/1uQYDehHqfoLu53REq3Xe5fTBhXqaD-s-/view?usp=sharing). I have also included the dependencies.

EDIT: I tested this in a VM, and there's no such issue. It's only a problem on my current machine. I have tried reinstalling the fonts, but issue persists. If you have an idea how to fix it (like maybe I need to install some fonts?), it would be nice, otherwise you can close the issue. Thank you!

**Screenshots**

![image](https://github.com/user-attachments/assets/3730d432-8b87-417c-a924-9453358ef898)

**Comment by codenulls** [comment]
I'm closing this because the issue is probably from my machine, since it works fine on a VM. Although, I haven't found a fix for it yet, but I can spend some time on this get it fixed later.

**Comment by Col-E** [comment]
Possibly related to this? https://stackoverflow.com/questions/66747171/why-javafx-application-and-scene-builder-is-showing-garbled-text

**Comment by codenulls** [comment]
> Possibly related to this? https://stackoverflow.com/questions/66747171/why-javafx-application-and-scene-builder-is-showing-garbled-text

Sorry, I forgot to respond. Yes, that's the reason. I had the same issue with Eclipse because of `Segoe UI` font. Thank you for your help!
