### ISSUE TITLE
Wrong font on home page

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#91]
Wrong on Firefox: 
![image](https://user-images.githubusercontent.com/21371686/46244256-3f615480-c3aa-11e8-94d3-e5df0a73b8a3.png)

Correct on Chrome: 
![image](https://user-images.githubusercontent.com/21371686/46244262-4daf7080-c3aa-11e8-8c1e-fcb2ac214ba1.png)

**Comment by andylizi** [comment]
![home-page](https://user-images.githubusercontent.com/12008103/46244383-e4af1380-c410-11e8-9677-f5d15c4988ca.png)
Actually... I don't think Firefox is the problem...

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/47693153-ea924300-dbce-11e8-9c98-51cd9b6ab8eb.png)

Looks fine on my phone + firefox now, so should be good to go.
